syntax = "proto2";
package futupb;

import "Types.proto";

option go_package = "github.com/santsai/futu-go/pb";

message QotGetUserSecurityRequest {
  required string groupName = 1; //分组名,有同名的返回排序首个
  optional QotHeader header = 100; //行情公共参数头
}

message QotGetUserSecurityResponse {
  repeated SecurityStaticInfo staticInfoList = 1; //自选股分组下的股票列表
}

message QotGetUserSecurityRequest_Internal {
  required QotGetUserSecurityRequest payload = 1;
}

message QotGetUserSecurityResponse_Internal {
  required RetType retType = 1 [default = RetType_Unknown]; //RetType,返回结果
  optional string retMsg = 2;
  optional int32 errCode = 3;

  optional QotGetUserSecurityResponse payload = 4;
}
