syntax = "proto2";
package futupb;

import "Types.proto";

option go_package = "github.com/santsai/futu-go/pb";

//内部使用
message TestCmdRequest {
  required string cmd = 1;
  optional string paramStr = 2;
  optional bytes paramBytes = 3;
}

message TestCmdResponse {
  required string cmd = 1;
  optional string resultStr = 2;
  optional bytes resultBytes = 3;
}

message TestCmdRequest_Internal {
  required TestCmdRequest payload = 1;
}

message TestCmdResponse_Internal {
  required RetType retType = 1 [default = RetType_Unknown]; //返回结果，参见Common.RetType的枚举定义
  optional string retMsg = 2; //返回结果描述
  optional int32 errCode = 3; //错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用

  optional TestCmdResponse payload = 4;
}
