syntax = "proto2";
package futupb;

import "Types.proto";

option go_package = "github.com/santsai/futu-go/pb";

message TrdGetComboMaxTrdQtysRequest {
  required TrdHeader header = 1; //交易公共参数头

  repeated ComboLeg comboLegs = 2; //组合的腿信息
  required double qty = 4; //数量，实际数量为 qty * 腿的 qty_ratio
  optional double price = 5; //价格
  required OrderType orderType = 6; //订单类型, 参见Trd_Common.OrderType的枚举定义
  optional string orderIDEx = 7; //订单号，改单时使用
}

message TrdGetComboMaxTrdQtysResponse {
  required TrdHeader header = 1; //交易公共参数头
  optional ComboMaxTrdQtys maxTrdQtys = 2; //组合最大可交易数量结构
}

message TrdGetComboMaxTrdQtysRequest_Internal {
  required TrdGetComboMaxTrdQtysRequest payload = 1;
}

message TrdGetComboMaxTrdQtysResponse_Internal {
  //以下3个字段每条协议都有，注释说明在InitConnect.proto中
  required RetType retType = 1 [default = RetType_Unknown];
  optional string retMsg = 2;
  optional int32 errCode = 3;

  optional TrdGetComboMaxTrdQtysResponse payload = 4;
}
