{
enum_replaces["optional int32 accStatus = 9; //账号状态，取值见TrdAccStatus"] = "TrdAccStatus"
enum_replaces["optional int32 accType = 4;   //账户类型，取值见TrdAccType"] = "TrdAccType"
enum_replaces["optional int32 cashFlowDirection = "] = "TrdCashFlowDirection"
enum_replaces["optional int32 condition = 3; //OptionCondType，价内价外，可选字段，不指定则表示都返回"] = "OptionCondType"
enum_replaces["optional int32 currency = "] = "Currency"
enum_replaces["optional int32 cycle = 4; //Qot_Common.ExpirationCycle,交割周期（仅用于香港指数期权）"] = "ExpirationCycle"
enum_replaces["optional int32 darkStatus = 15; //DarkStatus, 暗盘交易状态	"] = "DarkStatus"
enum_replaces["optional int32 dtStatus = 29;				//日内交易限制情况，取值见DTStatus"] = "DTStatus"
enum_replaces["optional int32 exchType = 9; //Qot_Common.ExchType,所属交易所"] = "ExchType"
enum_replaces["optional int32 expirationCycle = 9; // ExpirationCycle，交割周期"] = "ExpirationCycle"
enum_replaces["optional int32 filterMarket = 6; //指定交易市场, 参见TrdMarket的枚举定义"] = "TrdMarket"
enum_replaces["optional int32 freq = 7; // Qot_Common::PriceReminderFreq，提醒频率类型，删除、启用、禁用的情况下会忽略该字段"] = "PriceReminderFreq"
enum_replaces["optional int32 hkFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 hkOptionQotRight = "] = "QotRight"
enum_replaces["optional int32 hkQotRight = 4; //港股行情权限, QotRight"] = "QotRight"
enum_replaces["optional int32 indexOptionType = "] = "IndexOptionType"
enum_replaces["optional int32 inLinePriceStatus = "] = "PriceType"
enum_replaces["optional int32 ipoPeriod = 10; //Qot_Common.IpoPeriod，上市日"] = "IpoPeriod"
enum_replaces["optional int32 jpFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 market = "] = "QotMarket"
enum_replaces["optional int32 marketJPFuture = 18; //Qot_Common.QotMarketState,日本期货市场状态"] = "QotMarketState"
enum_replaces["optional int32 marketSGFuture = 17; //Qot_Common.QotMarketState,新加坡期货市场状态 "] = "QotMarketState"
enum_replaces["optional int32 marketUSFuture = 15; //Qot_Common.QotMarketState,美国期货市场状态 "] = "QotMarketState"
enum_replaces["optional int32 optionAreaType = "] = "OptionAreaType"
enum_replaces["optional int32 optionSettlementMode = 11; // OptionSettlementMode，结算方式"] = "OptionSettlementMode"
enum_replaces["optional int32 optionStandardType = 10; // OptionStandardType，标准期权"] = "OptionStandardType"
enum_replaces["optional int32 packetEncAlgo = 4; //指定包加密算法，参见Common.PacketEncAlgo的枚举定义"] = "PacketEncAlgo"
enum_replaces["optional int32 periodType = 2; // Qot_Common.PeriodType 周期类型"] = "PeriodType"
enum_replaces["optional int32 plateType = 3; //PlateSetType 板块类型, 仅3207（获取股票所属板块）协议返回该字段"] = "PlateSetType"
enum_replaces["optional int32 priceType = 11; //Qot_Common.PriceType，价内/价外（暂不支持界内证的界内外筛选）"] = "PriceType"
enum_replaces["optional int32 pushDataType = 10; //用于区分推送情况"] = "PushDataType"
enum_replaces["optional int32 pushProtoFmt = 5; //指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项"] = "ProtoFmt"
enum_replaces["optional int32 qotPushStage = 2; //行情推送统计的区间，行情推送统计时有效，QotPushStage"] = "QotPushStage"
enum_replaces["optional int32 riskLevel = 12;           //风控状态，参见 CltRiskLevel, 期货适用"] = "CltRiskLevel"
enum_replaces["optional int32 riskStatus = 22;              //风险状态，参见 [CltRiskStatus]，证券账户适用，共分 9 个等级，LEVEL1是最安全，LEVEL9是最危险"] = "CltRiskStatus"
enum_replaces["optional int32 secMarket = "] = "TrdSecMarket"
enum_replaces["optional int32 secStatus = "] = "SecurityStatus"
enum_replaces["optional int32 secType = 2; //Qot_Common.SecurityType,股票类型"] = "SecurityType"
enum_replaces["optional int32 securityFirm = "] = "SecurityFirm"
enum_replaces["optional int32 session = "] = "Session"
enum_replaces["optional int32 sgFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 shQotRight = "] = "QotRight"
enum_replaces["optional int32 simAccType = 7; //模拟交易账号类型，取值见SimAccType"] = "SimAccType"
enum_replaces["optional int32 sortDir = 5; // SortDir 排序方向，默认不排序。"] = "SortDir"
enum_replaces["optional int32 sortField = 2;//Qot_Common.SortField,根据哪个字段排序,不填默认Code排序"] = "SortField"
enum_replaces["optional int32 status = 12; //Qot_Common.WarrantStatus，窝轮状态"] = "WarrantStatus"
enum_replaces["optional int32 status = 16; //成交状态, 参见OrderFillStatus的枚举定义"] = "OrderFillStatus"
enum_replaces["optional int32 szQotRight = "] = "QotRight"
enum_replaces["optional int32 timeInForce = "] = "TimeInForce"
enum_replaces["optional int32 tradeDateType = 3; //Qot_Common.TradeDateType,交易时间类型"] = "TradeDateType"
enum_replaces["optional int32 trailType = "] = "TrailType"
enum_replaces["optional int32 trdCategory = 2; //交易品类，参考 Trd_Common.TrdCategory"] = "TrdCategory"
enum_replaces["optional int32 trdMarket = "] = "TrdMarket"
enum_replaces["optional int32 type = 2; //Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回"] = "OptionType"
enum_replaces["optional int32 type = 4; // Qot_Common::PriceReminderType，提醒类型，删除、启用、禁用的情况下会忽略该字段"] = "PriceReminderType"
enum_replaces["optional int32 type = 8; // Qot_Common::PriceReminderType，提醒类型"] = "PriceReminderType"
enum_replaces["optional int32 type = 8; //TickerType, 逐笔类型"] = "TickerType"
enum_replaces["optional int32 updateType = 9; //升级类型，UpdateType"] = "UpdateType"
enum_replaces["optional int32 usCBOEFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 usCMEFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 usCOMEXFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 userAttribution = 19; //用户注册归属地, Common.UserAttribution"] = "UserAttribution"
enum_replaces["optional int32 userAttribution = 7; //用户类型，牛牛用户或MooMoo用户"] = "UserAttribution"
enum_replaces["optional int32 usIndexQotRight = "] = "QotRight"
enum_replaces["optional int32 usNYMEXFutureQotRight = "] = "QotRight"
enum_replaces["optional int32 usOptionQotRight = "] = "QotRight"
enum_replaces["optional int32 usOtcQotRight = "] = "QotRight"
enum_replaces["optional int32 usQotRight = 5; //美股行情权限, QotRight"] = "QotRight"
enum_replaces["repeated int32 filterStatusList = 3; //需要过滤的订单状态列表"] = "OrderStatus"
enum_replaces["repeated int32 issuerList = 7; //Qot_Common.Issuer，发行人过滤列表"] = "Issuer"
enum_replaces["repeated int32 regPushRehabTypeList = 5; //Qot_Common.RehabType,复权类型,注册推送并且是K线类型才生效,其他订阅类型忽略该参数,注册K线推送时该参数不指定默认前复权"] = "RehabType"
enum_replaces["repeated int32 rehabTypeList = 3; //Qot_Common.RehabType,复权类型,注册K线类型才生效,其他订阅类型忽略该参数,注册K线时该参数不指定默认前复权"] = "RehabType"
enum_replaces["repeated int32 reminderSessionList = "] = "PriceReminderMarketStatus"
enum_replaces["repeated int32 subTypeList = 2; //Qot_Common.SubType,"] = "SubType"
enum_replaces["repeated int32 trdMarketAuthList = 3; //业务账户支持的交易市场权限，即此账户能交易那些市场, 可拥有多个交易市场权限，目前仅单个，取值参见TrdMarket的枚举定义"] = "TrdMarket"
enum_replaces["repeated int32 typeList = 1; //统计数据类型，DelayStatisticsType"] = "DelayStatisticsType"
enum_replaces["repeated int32 typeList = 4; //CodeChangeType，根据类型筛选"] = "CodeChangeType"
enum_replaces["repeated int32 typeList = 6; //Qot_Common.WarrantType，窝轮类型过滤列表"] = "WarrantType"
enum_replaces["required int32 assetClass = 6; //Qot_Common.AssetClass，资产类别"] = "AssetClass"
enum_replaces["required int32 dir = 3; //TickerDirection, 买卖方向"] = "TickerDirection"
enum_replaces["required int32 eventType = 1; //GtwEventType,事件类型"] = "GtwEventType"
enum_replaces["required int32 fieldName = 1; // AccumulateField 累积属性"] = "AccumulateField"
enum_replaces["required int32 fieldName = 1; // CustomIndicatorField 自定义技术指标属性"] = "CustomIndicatorField"
enum_replaces["required int32 fieldName = 1; // FinancialField 财务属性"] = "FinancialField"
enum_replaces["required int32 fieldName = 1; // PatternField 形态技术指标属性"] = "PatternField"
enum_replaces["required int32 fieldName = 1; // StockField 简单属性"] = "StockField"
enum_replaces["required int32 firstFieldName = 1; // CustomIndicatorField 自定义技术指标属性"] = "CustomIndicatorField"
enum_replaces["required int32 freq = 5; // Qot_Common::PriceReminderFreq 提醒频率类型"] = "PriceReminderFreq"
enum_replaces["required int32 groupType = 1; // GroupType,自选股分组类型。"] = "GroupType"
enum_replaces["required int32 groupType = 2; // GroupType,自选股分组类型。"] = "GroupType"
enum_replaces["required int32 hkQotRight = 4; //港股行情权限, Qot_Common.QotRight"] = "QotRight"
enum_replaces["required int32 holderCategory = 2; //持有者类别（1机构、2基金、3高管）"] = "HolderCategory"
enum_replaces["required int32 issuer = 4; //Qot_Common.Issuer，发行人"] = "Issuer"
enum_replaces["required int32 klType = "] = "KLType"
enum_replaces["required int32 market = 1; // Qot_Common::QotMarket股票市场，支持沪股和深股，且沪股和深股不做区分都代表A股市场。"] = "QotMarket"
enum_replaces["required int32 market = 1; //Qot_Common.QotMarket,股票市场"] = "QotMarket"
enum_replaces["required int32 market = 1; //Qot_Common.TradeDateMarket,要查询的市场"] = "TradeDateMarket"
enum_replaces["required int32 market = 1; //QotMarket,股票市场"] = "QotMarket"
enum_replaces["required int32 market= 3; // Qot_Common::QotMarket股票市场，支持沪股和深股，且沪股和深股不做区分都代表A股市场。"] = "QotMarket"
enum_replaces["required int32 marketHK = 1; //Qot_Common.QotMarketState,港股主板市场状态 "] = "QotMarketState"
enum_replaces["required int32 marketHKFuture = 5; //Qot_Common.QotMarketState,港股期货市场状态 "] = "QotMarketState"
enum_replaces["required int32 marketSH = 3; //Qot_Common.QotMarketState,沪市状态 "] = "QotMarketState"
enum_replaces["required int32 marketState = 3; //Qot_Common.QotMarketState,市场状态"] = "QotMarketState"
enum_replaces["required int32 marketStatus = 4; //市场状态,Qot_Common::PriceReminderMarketStatus"] = "PriceReminderMarketStatus"
enum_replaces["required int32 marketSZ = 4; //Qot_Common.QotMarketState,深市状态 "] = "QotMarketState"
enum_replaces["required int32 marketUS = 2; //Qot_Common.QotMarketState,美股Nasdaq市场状态 "] = "QotMarketState"
enum_replaces["required int32 modifyOrderOp = 4; //修改操作类型，参见Trd_Common.ModifyOrderOp的枚举定义"] = "ModifyOrderOp"
enum_replaces["required int32 noDataMode = 3; //NoDataMode,当请求时间点数据为空时，如何返回数据"] = "NoDataMode"
enum_replaces["required int32 op = 2; // SetPriceReminderOp，操作类型"] = "SetPriceReminderOp"
enum_replaces["required int32 op = 2; //操作, VerificationOp"] = "VerificationOp"
enum_replaces["required int32 op = 2; //ModifyUserSecurityOp,操作类型"] = "ModifyUserSecurityOp"
enum_replaces["required int32 orderStatus = 3; //订单状态, 参见OrderStatus的枚举定义"] = "OrderStatus"
enum_replaces["required int32 orderType = 2; //订单类型, 参见OrderType的枚举定义"] = "OrderType"
enum_replaces["required int32 orderType = 2; //订单类型, 参见Trd_Common.OrderType的枚举定义"] = "OrderType"
enum_replaces["required int32 orderType = 4; //订单类型, 参见Trd_Common.OrderType的枚举定义"] = "OrderType"
enum_replaces["required int32 plateSetType = 2; //Qot_Common.PlateSetType,板块集合的类型"] = "PlateSetType"
enum_replaces["required int32 positionSide = 2;    //持仓方向，参见PositionSide的枚举定义"] = "PositionSide"
enum_replaces["required int32 qotPushType = 1; //行情推送类型,QotPushType"] = "QotPushType"
enum_replaces["required int32 quarter = 3; // FinancialQuarter 财报累积时间"] = "FinancialQuarter"
enum_replaces["required int32 quarter = 6; // FinancialQuarter 财报累积时间"] = "FinancialQuarter"
# ReconfirmOrderReason does not exist
#enum_replaces["required int32 reconfirmReason = 4; //需要再次确认订单的原因，参见Trd_Common.ReconfirmOrderReason的枚举定义"] = "ReconfirmOrderReason"
enum_replaces["required int32 referenceType = 2; // ReferenceType, 相关类型"] = "ReferenceType"
enum_replaces["required int32 rehabType = 1; //Qot_Common.RehabType,复权类型"] = "RehabType"
enum_replaces["required int32 relativePosition = 3; // RelativePosition 相对位置"] = "RelativePosition"
enum_replaces["required int32 retType = 1 [default = -400];"] = "RetType"
enum_replaces["required int32 secondFieldName = 2; // CustomIndicatorField 自定义技术指标属性"] = "CustomIndicatorField"
enum_replaces["required int32 secType = 4; //Qot_Common.SecurityType,股票类型"] = "SecurityType"
enum_replaces["required int32 sortField = 3;//Qot_Common.SortField，根据哪个字段排序"] = "SortField"
enum_replaces["required int32 status = 1; //DataStatus,数据状态"] = "DataStatus"
enum_replaces["required int32 status = 20; //Qot_Common.WarrantStatus，窝轮状态	"] = "WarrantStatus"
enum_replaces["required int32 subType = 1; //Qot_Common.SubType,订阅类型"] = "SubType"
enum_replaces["required int32 trdEnv = 1; //交易环境, 参见TrdEnv的枚举定义"] = "TrdEnv"
enum_replaces["required int32 trdEnv = 1; //交易环境，参见TrdEnv的枚举定义"] = "TrdEnv"
enum_replaces["required int32 trdMarket = 3; //交易市场, 参见TrdMarket的枚举定义"] = "TrdMarket"
enum_replaces["required int32 trdSide = 1; //交易方向, 参见TrdSide的枚举定义"] = "TrdSide"
enum_replaces["required int32 trdSide = 3; //交易方向, 参见Trd_Common.TrdSide的枚举定义"] = "TrdSide"
enum_replaces["required int32 type = 1; //验证码类型, VerificationType"] = "VerificationType"
enum_replaces["required int32 type = 1; //通知类型"] = "NotifyType"
enum_replaces["required int32 type = 1; //CodeChangeType,代码变化或者新增临时代码的事件类型"] = "CodeChangeType"
enum_replaces["required int32 type = 1; //Qot_Common.OptionType,期权"] = "OptionType"
enum_replaces["required int32 type = 1; //Qot_Common.WarrantType,窝轮类型"] = "WarrantType"
enum_replaces["required int32 type = 1; //TimeFilterType, 过滤类型"] = "TimeFilterType"
enum_replaces["required int32 type = 2; // Qot_Common::PriceReminderType 提醒类型"] = "PriceReminderType"
enum_replaces["required int32 type = 2; //Qot_Common.SecurityType,股票类型"] = "SecurityType"
enum_replaces["required int32 type = 3; //Qot_Common.WarrantType，窝轮类型"] = "WarrantType"
enum_replaces["required int32 usQotRight = 5; //美股行情权限, Qot_Common.QotRight"] = "QotRight"
enum_replaces["required int32 warrantType = 2; //Qot_Common.WarrantType,窝轮类型"] = "WarrantType"
}
