// Code generated by protoc-gen-go-futu. DO NOT EDIT.

package pb

type ProtoId uint32

const (
	ProtoId_InitConnect                ProtoId = 1001
	ProtoId_GetGlobalState             ProtoId = 1002
	ProtoId_Notify                     ProtoId = 1003
	ProtoId_KeepAlive                  ProtoId = 1004
	ProtoId_GetUserInfo                ProtoId = 1005
	ProtoId_Verification               ProtoId = 1006
	ProtoId_GetDelayStatistics         ProtoId = 1007
	ProtoId_TestCmd                    ProtoId = 1008
	ProtoId_InitQuantMode              ProtoId = 1009
	ProtoId_TrdGetAccList              ProtoId = 2001
	ProtoId_TrdUnlockTrade             ProtoId = 2005
	ProtoId_TrdSubAccPush              ProtoId = 2008
	ProtoId_TrdGetFunds                ProtoId = 2101
	ProtoId_TrdGetPositionList         ProtoId = 2102
	ProtoId_TrdGetMaxTrdQtys           ProtoId = 2111
	ProtoId_TrdGetOrderList            ProtoId = 2201
	ProtoId_TrdPlaceOrder              ProtoId = 2202
	ProtoId_TrdModifyOrder             ProtoId = 2205
	ProtoId_TrdUpdateOrder             ProtoId = 2208
	ProtoId_TrdGetOrderFillList        ProtoId = 2211
	ProtoId_TrdUpdateOrderFill         ProtoId = 2218
	ProtoId_TrdGetHistoryOrderList     ProtoId = 2221
	ProtoId_TrdGetHistoryOrderFillList ProtoId = 2222
	ProtoId_TrdGetMarginRatio          ProtoId = 2223
	ProtoId_TrdGetOrderFee             ProtoId = 2225
	ProtoId_TrdFlowSummary             ProtoId = 2226
	ProtoId_QotSub                     ProtoId = 3001
	ProtoId_QotRegQotPush              ProtoId = 3002
	ProtoId_QotGetSubInfo              ProtoId = 3003
	ProtoId_QotGetBasicQot             ProtoId = 3004
	ProtoId_QotUpdateBasicQot          ProtoId = 3005
	ProtoId_QotGetKL                   ProtoId = 3006
	ProtoId_QotUpdateKL                ProtoId = 3007
	ProtoId_QotGetRT                   ProtoId = 3008
	ProtoId_QotUpdateRT                ProtoId = 3009
	ProtoId_QotGetTicker               ProtoId = 3010
	ProtoId_QotUpdateTicker            ProtoId = 3011
	ProtoId_QotGetOrderBook            ProtoId = 3012
	ProtoId_QotUpdateOrderBook         ProtoId = 3013
	ProtoId_QotGetBroker               ProtoId = 3014
	ProtoId_QotUpdateBroker            ProtoId = 3015
	ProtoId_QotUpdatePriceReminder     ProtoId = 3019
	ProtoId_QotRequestHistoryKL        ProtoId = 3103
	ProtoId_QotRequestHistoryKLQuota   ProtoId = 3104
	ProtoId_QotRequestRehab            ProtoId = 3105
	ProtoId_QotGetSuspend              ProtoId = 3201
	ProtoId_QotGetStaticInfo           ProtoId = 3202
	ProtoId_QotGetSecuritySnapshot     ProtoId = 3203
	ProtoId_QotGetPlateSet             ProtoId = 3204
	ProtoId_QotGetPlateSecurity        ProtoId = 3205
	ProtoId_QotGetReference            ProtoId = 3206
	ProtoId_QotGetOwnerPlate           ProtoId = 3207
	ProtoId_QotGetHoldingChangeList    ProtoId = 3208
	ProtoId_QotGetOptionChain          ProtoId = 3209
	ProtoId_QotGetWarrant              ProtoId = 3210
	ProtoId_QotGetCapitalFlow          ProtoId = 3211
	ProtoId_QotGetCapitalDistribution  ProtoId = 3212
	ProtoId_QotGetUserSecurity         ProtoId = 3213
	ProtoId_QotModifyUserSecurity      ProtoId = 3214
	ProtoId_QotStockFilter             ProtoId = 3215
	ProtoId_QotGetCodeChange           ProtoId = 3216
	ProtoId_QotGetIpoList              ProtoId = 3217
	ProtoId_QotGetFutureInfo           ProtoId = 3218
	ProtoId_QotRequestTradeDate        ProtoId = 3219
	ProtoId_QotSetPriceReminder        ProtoId = 3220
	ProtoId_QotGetPriceReminder        ProtoId = 3221
	ProtoId_QotGetUserSecurityGroup    ProtoId = 3222
	ProtoId_QotGetMarketState          ProtoId = 3223
	ProtoId_QotGetOptionExpirationDate ProtoId = 3224
	ProtoId_Unknown                    ProtoId = 4294967295
)

func (id ProtoId) String() string {
	switch id {
	case ProtoId_InitConnect:
		return "ProtoId_InitConnect"
	case ProtoId_GetGlobalState:
		return "ProtoId_GetGlobalState"
	case ProtoId_Notify:
		return "ProtoId_Notify"
	case ProtoId_KeepAlive:
		return "ProtoId_KeepAlive"
	case ProtoId_GetUserInfo:
		return "ProtoId_GetUserInfo"
	case ProtoId_Verification:
		return "ProtoId_Verification"
	case ProtoId_GetDelayStatistics:
		return "ProtoId_GetDelayStatistics"
	case ProtoId_TestCmd:
		return "ProtoId_TestCmd"
	case ProtoId_InitQuantMode:
		return "ProtoId_InitQuantMode"
	case ProtoId_TrdGetAccList:
		return "ProtoId_TrdGetAccList"
	case ProtoId_TrdUnlockTrade:
		return "ProtoId_TrdUnlockTrade"
	case ProtoId_TrdSubAccPush:
		return "ProtoId_TrdSubAccPush"
	case ProtoId_TrdGetFunds:
		return "ProtoId_TrdGetFunds"
	case ProtoId_TrdGetPositionList:
		return "ProtoId_TrdGetPositionList"
	case ProtoId_TrdGetMaxTrdQtys:
		return "ProtoId_TrdGetMaxTrdQtys"
	case ProtoId_TrdGetOrderList:
		return "ProtoId_TrdGetOrderList"
	case ProtoId_TrdPlaceOrder:
		return "ProtoId_TrdPlaceOrder"
	case ProtoId_TrdModifyOrder:
		return "ProtoId_TrdModifyOrder"
	case ProtoId_TrdUpdateOrder:
		return "ProtoId_TrdUpdateOrder"
	case ProtoId_TrdGetOrderFillList:
		return "ProtoId_TrdGetOrderFillList"
	case ProtoId_TrdUpdateOrderFill:
		return "ProtoId_TrdUpdateOrderFill"
	case ProtoId_TrdGetHistoryOrderList:
		return "ProtoId_TrdGetHistoryOrderList"
	case ProtoId_TrdGetHistoryOrderFillList:
		return "ProtoId_TrdGetHistoryOrderFillList"
	case ProtoId_TrdGetMarginRatio:
		return "ProtoId_TrdGetMarginRatio"
	case ProtoId_TrdGetOrderFee:
		return "ProtoId_TrdGetOrderFee"
	case ProtoId_TrdFlowSummary:
		return "ProtoId_TrdFlowSummary"
	case ProtoId_QotSub:
		return "ProtoId_QotSub"
	case ProtoId_QotRegQotPush:
		return "ProtoId_QotRegQotPush"
	case ProtoId_QotGetSubInfo:
		return "ProtoId_QotGetSubInfo"
	case ProtoId_QotGetBasicQot:
		return "ProtoId_QotGetBasicQot"
	case ProtoId_QotUpdateBasicQot:
		return "ProtoId_QotUpdateBasicQot"
	case ProtoId_QotGetKL:
		return "ProtoId_QotGetKL"
	case ProtoId_QotUpdateKL:
		return "ProtoId_QotUpdateKL"
	case ProtoId_QotGetRT:
		return "ProtoId_QotGetRT"
	case ProtoId_QotUpdateRT:
		return "ProtoId_QotUpdateRT"
	case ProtoId_QotGetTicker:
		return "ProtoId_QotGetTicker"
	case ProtoId_QotUpdateTicker:
		return "ProtoId_QotUpdateTicker"
	case ProtoId_QotGetOrderBook:
		return "ProtoId_QotGetOrderBook"
	case ProtoId_QotUpdateOrderBook:
		return "ProtoId_QotUpdateOrderBook"
	case ProtoId_QotGetBroker:
		return "ProtoId_QotGetBroker"
	case ProtoId_QotUpdateBroker:
		return "ProtoId_QotUpdateBroker"
	case ProtoId_QotUpdatePriceReminder:
		return "ProtoId_QotUpdatePriceReminder"
	case ProtoId_QotRequestHistoryKL:
		return "ProtoId_QotRequestHistoryKL"
	case ProtoId_QotRequestHistoryKLQuota:
		return "ProtoId_QotRequestHistoryKLQuota"
	case ProtoId_QotRequestRehab:
		return "ProtoId_QotRequestRehab"
	case ProtoId_QotGetSuspend:
		return "ProtoId_QotGetSuspend"
	case ProtoId_QotGetStaticInfo:
		return "ProtoId_QotGetStaticInfo"
	case ProtoId_QotGetSecuritySnapshot:
		return "ProtoId_QotGetSecuritySnapshot"
	case ProtoId_QotGetPlateSet:
		return "ProtoId_QotGetPlateSet"
	case ProtoId_QotGetPlateSecurity:
		return "ProtoId_QotGetPlateSecurity"
	case ProtoId_QotGetReference:
		return "ProtoId_QotGetReference"
	case ProtoId_QotGetOwnerPlate:
		return "ProtoId_QotGetOwnerPlate"
	case ProtoId_QotGetHoldingChangeList:
		return "ProtoId_QotGetHoldingChangeList"
	case ProtoId_QotGetOptionChain:
		return "ProtoId_QotGetOptionChain"
	case ProtoId_QotGetWarrant:
		return "ProtoId_QotGetWarrant"
	case ProtoId_QotGetCapitalFlow:
		return "ProtoId_QotGetCapitalFlow"
	case ProtoId_QotGetCapitalDistribution:
		return "ProtoId_QotGetCapitalDistribution"
	case ProtoId_QotGetUserSecurity:
		return "ProtoId_QotGetUserSecurity"
	case ProtoId_QotModifyUserSecurity:
		return "ProtoId_QotModifyUserSecurity"
	case ProtoId_QotStockFilter:
		return "ProtoId_QotStockFilter"
	case ProtoId_QotGetCodeChange:
		return "ProtoId_QotGetCodeChange"
	case ProtoId_QotGetIpoList:
		return "ProtoId_QotGetIpoList"
	case ProtoId_QotGetFutureInfo:
		return "ProtoId_QotGetFutureInfo"
	case ProtoId_QotRequestTradeDate:
		return "ProtoId_QotRequestTradeDate"
	case ProtoId_QotSetPriceReminder:
		return "ProtoId_QotSetPriceReminder"
	case ProtoId_QotGetPriceReminder:
		return "ProtoId_QotGetPriceReminder"
	case ProtoId_QotGetUserSecurityGroup:
		return "ProtoId_QotGetUserSecurityGroup"
	case ProtoId_QotGetMarketState:
		return "ProtoId_QotGetMarketState"
	case ProtoId_QotGetOptionExpirationDate:
		return "ProtoId_QotGetOptionExpirationDate"
	case ProtoId_Unknown:
		return "ProtoId_Unknown"
	}
	return "(Unknown)"
}
func IsPushProtoId(id ProtoId) bool {
	switch id {
	case ProtoId_Notify:
		return true
	case ProtoId_KeepAlive:
		return true
	case ProtoId_TrdUpdateOrder:
		return true
	case ProtoId_TrdUpdateOrderFill:
		return true
	case ProtoId_QotUpdateBroker:
		return true
	case ProtoId_QotUpdateOrderBook:
		return true
	case ProtoId_QotUpdateKL:
		return true
	case ProtoId_QotUpdateRT:
		return true
	case ProtoId_QotUpdateBasicQot:
		return true
	case ProtoId_QotUpdateTicker:
		return true
	case ProtoId_QotUpdatePriceReminder:
		return true
	}
	return false
}
