// Code generated by protoc-gen-go-futu. DO NOT EDIT.

package pb

import "context"
import "google.golang.org/protobuf/proto"

type Request interface {
	proto.Message
	GetRequestPayload() proto.Message
}

type RequestHandler interface {
	Request(context.Context, ProtoId, Request, Response) (proto.Message, error)
}

func (m *GetDelayStatisticsRequest) Dispatch(ctx context.Context, rh RequestHandler) (*GetDelayStatisticsResponse, error) {
	req := &GetDelayStatisticsRequest_Internal{Payload: m}
	resp_internal := &GetDelayStatisticsResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_GetDelayStatistics, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*GetDelayStatisticsResponse), nil
	}
}

func (m *GetDelayStatisticsRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *GetGlobalStateRequest) Dispatch(ctx context.Context, rh RequestHandler) (*GetGlobalStateResponse, error) {
	req := &GetGlobalStateRequest_Internal{Payload: m}
	resp_internal := &GetGlobalStateResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_GetGlobalState, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*GetGlobalStateResponse), nil
	}
}

func (m *GetGlobalStateRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *GetUserInfoRequest) Dispatch(ctx context.Context, rh RequestHandler) (*GetUserInfoResponse, error) {
	req := &GetUserInfoRequest_Internal{Payload: m}
	resp_internal := &GetUserInfoResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_GetUserInfo, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*GetUserInfoResponse), nil
	}
}

func (m *GetUserInfoRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *InitConnectRequest) Dispatch(ctx context.Context, rh RequestHandler) (*InitConnectResponse, error) {
	req := &InitConnectRequest_Internal{Payload: m}
	resp_internal := &InitConnectResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_InitConnect, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*InitConnectResponse), nil
	}
}

func (m *InitConnectRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *KeepAliveRequest) Dispatch(ctx context.Context, rh RequestHandler) (*KeepAliveResponse, error) {
	req := &KeepAliveRequest_Internal{Payload: m}
	resp_internal := &KeepAliveResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_KeepAlive, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*KeepAliveResponse), nil
	}
}

func (m *KeepAliveRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetBasicQotRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetBasicQotResponse, error) {
	req := &QotGetBasicQotRequest_Internal{Payload: m}
	resp_internal := &QotGetBasicQotResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetBasicQot, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetBasicQotResponse), nil
	}
}

func (m *QotGetBasicQotRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetBrokerRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetBrokerResponse, error) {
	req := &QotGetBrokerRequest_Internal{Payload: m}
	resp_internal := &QotGetBrokerResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetBroker, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetBrokerResponse), nil
	}
}

func (m *QotGetBrokerRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetCapitalDistributionRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetCapitalDistributionResponse, error) {
	req := &QotGetCapitalDistributionRequest_Internal{Payload: m}
	resp_internal := &QotGetCapitalDistributionResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetCapitalDistribution, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetCapitalDistributionResponse), nil
	}
}

func (m *QotGetCapitalDistributionRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetCapitalFlowRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetCapitalFlowResponse, error) {
	req := &QotGetCapitalFlowRequest_Internal{Payload: m}
	resp_internal := &QotGetCapitalFlowResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetCapitalFlow, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetCapitalFlowResponse), nil
	}
}

func (m *QotGetCapitalFlowRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetCodeChangeRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetCodeChangeResponse, error) {
	req := &QotGetCodeChangeRequest_Internal{Payload: m}
	resp_internal := &QotGetCodeChangeResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetCodeChange, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetCodeChangeResponse), nil
	}
}

func (m *QotGetCodeChangeRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetFutureInfoRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetFutureInfoResponse, error) {
	req := &QotGetFutureInfoRequest_Internal{Payload: m}
	resp_internal := &QotGetFutureInfoResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetFutureInfo, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetFutureInfoResponse), nil
	}
}

func (m *QotGetFutureInfoRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

/* ProtoId Not Exist: QotGetHistoryKL

func (m *QotGetHistoryKLRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetHistoryKLResponse, error) {
	req := &QotGetHistoryKLRequest_Internal{ Payload: m }
	resp_internal := &QotGetHistoryKLResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetHistoryKL, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetHistoryKLResponse), nil
	}
}


func (m *QotGetHistoryKLRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

*/
/* ProtoId Not Exist: QotGetHistoryKLPoints

func (m *QotGetHistoryKLPointsRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetHistoryKLPointsResponse, error) {
	req := &QotGetHistoryKLPointsRequest_Internal{ Payload: m }
	resp_internal := &QotGetHistoryKLPointsResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetHistoryKLPoints, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetHistoryKLPointsResponse), nil
	}
}


func (m *QotGetHistoryKLPointsRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

*/

func (m *QotGetHoldingChangeListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetHoldingChangeListResponse, error) {
	req := &QotGetHoldingChangeListRequest_Internal{Payload: m}
	resp_internal := &QotGetHoldingChangeListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetHoldingChangeList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetHoldingChangeListResponse), nil
	}
}

func (m *QotGetHoldingChangeListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetIpoListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetIpoListResponse, error) {
	req := &QotGetIpoListRequest_Internal{Payload: m}
	resp_internal := &QotGetIpoListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetIpoList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetIpoListResponse), nil
	}
}

func (m *QotGetIpoListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetKLRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetKLResponse, error) {
	req := &QotGetKLRequest_Internal{Payload: m}
	resp_internal := &QotGetKLResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetKL, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetKLResponse), nil
	}
}

func (m *QotGetKLRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetMarketStateRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetMarketStateResponse, error) {
	req := &QotGetMarketStateRequest_Internal{Payload: m}
	resp_internal := &QotGetMarketStateResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetMarketState, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetMarketStateResponse), nil
	}
}

func (m *QotGetMarketStateRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetOptionChainRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetOptionChainResponse, error) {
	req := &QotGetOptionChainRequest_Internal{Payload: m}
	resp_internal := &QotGetOptionChainResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetOptionChain, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetOptionChainResponse), nil
	}
}

func (m *QotGetOptionChainRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetOptionExpirationDateRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetOptionExpirationDateResponse, error) {
	req := &QotGetOptionExpirationDateRequest_Internal{Payload: m}
	resp_internal := &QotGetOptionExpirationDateResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetOptionExpirationDate, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetOptionExpirationDateResponse), nil
	}
}

func (m *QotGetOptionExpirationDateRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetOrderBookRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetOrderBookResponse, error) {
	req := &QotGetOrderBookRequest_Internal{Payload: m}
	resp_internal := &QotGetOrderBookResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetOrderBook, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetOrderBookResponse), nil
	}
}

func (m *QotGetOrderBookRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetOwnerPlateRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetOwnerPlateResponse, error) {
	req := &QotGetOwnerPlateRequest_Internal{Payload: m}
	resp_internal := &QotGetOwnerPlateResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetOwnerPlate, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetOwnerPlateResponse), nil
	}
}

func (m *QotGetOwnerPlateRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetPlateSecurityRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetPlateSecurityResponse, error) {
	req := &QotGetPlateSecurityRequest_Internal{Payload: m}
	resp_internal := &QotGetPlateSecurityResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetPlateSecurity, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetPlateSecurityResponse), nil
	}
}

func (m *QotGetPlateSecurityRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetPlateSetRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetPlateSetResponse, error) {
	req := &QotGetPlateSetRequest_Internal{Payload: m}
	resp_internal := &QotGetPlateSetResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetPlateSet, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetPlateSetResponse), nil
	}
}

func (m *QotGetPlateSetRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetPriceReminderRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetPriceReminderResponse, error) {
	req := &QotGetPriceReminderRequest_Internal{Payload: m}
	resp_internal := &QotGetPriceReminderResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetPriceReminder, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetPriceReminderResponse), nil
	}
}

func (m *QotGetPriceReminderRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetReferenceRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetReferenceResponse, error) {
	req := &QotGetReferenceRequest_Internal{Payload: m}
	resp_internal := &QotGetReferenceResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetReference, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetReferenceResponse), nil
	}
}

func (m *QotGetReferenceRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

/* ProtoId Not Exist: QotGetRehab

func (m *QotGetRehabRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetRehabResponse, error) {
	req := &QotGetRehabRequest_Internal{ Payload: m }
	resp_internal := &QotGetRehabResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetRehab, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetRehabResponse), nil
	}
}


func (m *QotGetRehabRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

*/

func (m *QotGetRTRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetRTResponse, error) {
	req := &QotGetRTRequest_Internal{Payload: m}
	resp_internal := &QotGetRTResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetRT, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetRTResponse), nil
	}
}

func (m *QotGetRTRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetSecuritySnapshotRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetSecuritySnapshotResponse, error) {
	req := &QotGetSecuritySnapshotRequest_Internal{Payload: m}
	resp_internal := &QotGetSecuritySnapshotResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetSecuritySnapshot, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetSecuritySnapshotResponse), nil
	}
}

func (m *QotGetSecuritySnapshotRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetStaticInfoRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetStaticInfoResponse, error) {
	req := &QotGetStaticInfoRequest_Internal{Payload: m}
	resp_internal := &QotGetStaticInfoResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetStaticInfo, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetStaticInfoResponse), nil
	}
}

func (m *QotGetStaticInfoRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetSubInfoRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetSubInfoResponse, error) {
	req := &QotGetSubInfoRequest_Internal{Payload: m}
	resp_internal := &QotGetSubInfoResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetSubInfo, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetSubInfoResponse), nil
	}
}

func (m *QotGetSubInfoRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetSuspendRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetSuspendResponse, error) {
	req := &QotGetSuspendRequest_Internal{Payload: m}
	resp_internal := &QotGetSuspendResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetSuspend, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetSuspendResponse), nil
	}
}

func (m *QotGetSuspendRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetTickerRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetTickerResponse, error) {
	req := &QotGetTickerRequest_Internal{Payload: m}
	resp_internal := &QotGetTickerResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetTicker, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetTickerResponse), nil
	}
}

func (m *QotGetTickerRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetUserSecurityRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetUserSecurityResponse, error) {
	req := &QotGetUserSecurityRequest_Internal{Payload: m}
	resp_internal := &QotGetUserSecurityResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetUserSecurity, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetUserSecurityResponse), nil
	}
}

func (m *QotGetUserSecurityRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetUserSecurityGroupRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetUserSecurityGroupResponse, error) {
	req := &QotGetUserSecurityGroupRequest_Internal{Payload: m}
	resp_internal := &QotGetUserSecurityGroupResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetUserSecurityGroup, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetUserSecurityGroupResponse), nil
	}
}

func (m *QotGetUserSecurityGroupRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotGetWarrantRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotGetWarrantResponse, error) {
	req := &QotGetWarrantRequest_Internal{Payload: m}
	resp_internal := &QotGetWarrantResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotGetWarrant, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotGetWarrantResponse), nil
	}
}

func (m *QotGetWarrantRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotModifyUserSecurityRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotModifyUserSecurityResponse, error) {
	req := &QotModifyUserSecurityRequest_Internal{Payload: m}
	resp_internal := &QotModifyUserSecurityResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotModifyUserSecurity, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotModifyUserSecurityResponse), nil
	}
}

func (m *QotModifyUserSecurityRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotRegQotPushRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotRegQotPushResponse, error) {
	req := &QotRegQotPushRequest_Internal{Payload: m}
	resp_internal := &QotRegQotPushResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotRegQotPush, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotRegQotPushResponse), nil
	}
}

func (m *QotRegQotPushRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotRequestHistoryKLRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotRequestHistoryKLResponse, error) {
	req := &QotRequestHistoryKLRequest_Internal{Payload: m}
	resp_internal := &QotRequestHistoryKLResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotRequestHistoryKL, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotRequestHistoryKLResponse), nil
	}
}

func (m *QotRequestHistoryKLRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotRequestHistoryKLQuotaRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotRequestHistoryKLQuotaResponse, error) {
	req := &QotRequestHistoryKLQuotaRequest_Internal{Payload: m}
	resp_internal := &QotRequestHistoryKLQuotaResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotRequestHistoryKLQuota, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotRequestHistoryKLQuotaResponse), nil
	}
}

func (m *QotRequestHistoryKLQuotaRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotRequestRehabRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotRequestRehabResponse, error) {
	req := &QotRequestRehabRequest_Internal{Payload: m}
	resp_internal := &QotRequestRehabResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotRequestRehab, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotRequestRehabResponse), nil
	}
}

func (m *QotRequestRehabRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotRequestTradeDateRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotRequestTradeDateResponse, error) {
	req := &QotRequestTradeDateRequest_Internal{Payload: m}
	resp_internal := &QotRequestTradeDateResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotRequestTradeDate, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotRequestTradeDateResponse), nil
	}
}

func (m *QotRequestTradeDateRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotSetPriceReminderRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotSetPriceReminderResponse, error) {
	req := &QotSetPriceReminderRequest_Internal{Payload: m}
	resp_internal := &QotSetPriceReminderResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotSetPriceReminder, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotSetPriceReminderResponse), nil
	}
}

func (m *QotSetPriceReminderRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotStockFilterRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotStockFilterResponse, error) {
	req := &QotStockFilterRequest_Internal{Payload: m}
	resp_internal := &QotStockFilterResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotStockFilter, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotStockFilterResponse), nil
	}
}

func (m *QotStockFilterRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *QotSubRequest) Dispatch(ctx context.Context, rh RequestHandler) (*QotSubResponse, error) {
	req := &QotSubRequest_Internal{Payload: m}
	resp_internal := &QotSubResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_QotSub, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*QotSubResponse), nil
	}
}

func (m *QotSubRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TestCmdRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TestCmdResponse, error) {
	req := &TestCmdRequest_Internal{Payload: m}
	resp_internal := &TestCmdResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TestCmd, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TestCmdResponse), nil
	}
}

func (m *TestCmdRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdFlowSummaryRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdFlowSummaryResponse, error) {
	req := &TrdFlowSummaryRequest_Internal{Payload: m}
	resp_internal := &TrdFlowSummaryResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdFlowSummary, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdFlowSummaryResponse), nil
	}
}

func (m *TrdFlowSummaryRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetAccListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetAccListResponse, error) {
	req := &TrdGetAccListRequest_Internal{Payload: m}
	resp_internal := &TrdGetAccListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetAccList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetAccListResponse), nil
	}
}

func (m *TrdGetAccListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetFundsRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetFundsResponse, error) {
	req := &TrdGetFundsRequest_Internal{Payload: m}
	resp_internal := &TrdGetFundsResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetFunds, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetFundsResponse), nil
	}
}

func (m *TrdGetFundsRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetHistoryOrderFillListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetHistoryOrderFillListResponse, error) {
	req := &TrdGetHistoryOrderFillListRequest_Internal{Payload: m}
	resp_internal := &TrdGetHistoryOrderFillListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetHistoryOrderFillList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetHistoryOrderFillListResponse), nil
	}
}

func (m *TrdGetHistoryOrderFillListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetHistoryOrderListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetHistoryOrderListResponse, error) {
	req := &TrdGetHistoryOrderListRequest_Internal{Payload: m}
	resp_internal := &TrdGetHistoryOrderListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetHistoryOrderList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetHistoryOrderListResponse), nil
	}
}

func (m *TrdGetHistoryOrderListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetMarginRatioRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetMarginRatioResponse, error) {
	req := &TrdGetMarginRatioRequest_Internal{Payload: m}
	resp_internal := &TrdGetMarginRatioResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetMarginRatio, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetMarginRatioResponse), nil
	}
}

func (m *TrdGetMarginRatioRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetMaxTrdQtysRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetMaxTrdQtysResponse, error) {
	req := &TrdGetMaxTrdQtysRequest_Internal{Payload: m}
	resp_internal := &TrdGetMaxTrdQtysResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetMaxTrdQtys, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetMaxTrdQtysResponse), nil
	}
}

func (m *TrdGetMaxTrdQtysRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetOrderFeeRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetOrderFeeResponse, error) {
	req := &TrdGetOrderFeeRequest_Internal{Payload: m}
	resp_internal := &TrdGetOrderFeeResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetOrderFee, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetOrderFeeResponse), nil
	}
}

func (m *TrdGetOrderFeeRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetOrderFillListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetOrderFillListResponse, error) {
	req := &TrdGetOrderFillListRequest_Internal{Payload: m}
	resp_internal := &TrdGetOrderFillListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetOrderFillList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetOrderFillListResponse), nil
	}
}

func (m *TrdGetOrderFillListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetOrderListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetOrderListResponse, error) {
	req := &TrdGetOrderListRequest_Internal{Payload: m}
	resp_internal := &TrdGetOrderListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetOrderList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetOrderListResponse), nil
	}
}

func (m *TrdGetOrderListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdGetPositionListRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdGetPositionListResponse, error) {
	req := &TrdGetPositionListRequest_Internal{Payload: m}
	resp_internal := &TrdGetPositionListResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdGetPositionList, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdGetPositionListResponse), nil
	}
}

func (m *TrdGetPositionListRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdModifyOrderRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdModifyOrderResponse, error) {
	req := &TrdModifyOrderRequest_Internal{Payload: m}
	resp_internal := &TrdModifyOrderResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdModifyOrder, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdModifyOrderResponse), nil
	}
}

func (m *TrdModifyOrderRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdPlaceOrderRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdPlaceOrderResponse, error) {
	req := &TrdPlaceOrderRequest_Internal{Payload: m}
	resp_internal := &TrdPlaceOrderResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdPlaceOrder, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdPlaceOrderResponse), nil
	}
}

func (m *TrdPlaceOrderRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

/* ProtoId Not Exist: TrdReconfirmOrder

func (m *TrdReconfirmOrderRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdReconfirmOrderResponse, error) {
	req := &TrdReconfirmOrderRequest_Internal{ Payload: m }
	resp_internal := &TrdReconfirmOrderResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdReconfirmOrder, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdReconfirmOrderResponse), nil
	}
}


func (m *TrdReconfirmOrderRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

*/

func (m *TrdSubAccPushRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdSubAccPushResponse, error) {
	req := &TrdSubAccPushRequest_Internal{Payload: m}
	resp_internal := &TrdSubAccPushResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdSubAccPush, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdSubAccPushResponse), nil
	}
}

func (m *TrdSubAccPushRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

func (m *TrdUnlockTradeRequest) Dispatch(ctx context.Context, rh RequestHandler) (*TrdUnlockTradeResponse, error) {
	req := &TrdUnlockTradeRequest_Internal{Payload: m}
	resp_internal := &TrdUnlockTradeResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_TrdUnlockTrade, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*TrdUnlockTradeResponse), nil
	}
}

func (m *TrdUnlockTradeRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

/* ProtoId Not Exist: UsedQuota

func (m *UsedQuotaRequest) Dispatch(ctx context.Context, rh RequestHandler) (*UsedQuotaResponse, error) {
	req := &UsedQuotaRequest_Internal{ Payload: m }
	resp_internal := &UsedQuotaResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_UsedQuota, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*UsedQuotaResponse), nil
	}
}


func (m *UsedQuotaRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

*/

func (m *VerificationRequest) Dispatch(ctx context.Context, rh RequestHandler) (*VerificationResponse, error) {
	req := &VerificationRequest_Internal{Payload: m}
	resp_internal := &VerificationResponse_Internal{}
	if resp, err := rh.Request(ctx, ProtoId_Verification, req, resp_internal); err != nil {
		return nil, err
	} else {
		return resp.(*VerificationResponse), nil
	}
}

func (m *VerificationRequest_Internal) GetRequestPayload() proto.Message {
	return m.GetPayload()
}

/* protoid: used/total (68/69)
unused:
InitQuantMode
*/
