// Code generated by protoc-gen-go-futu. DO NOT EDIT.

package pb

type UserIDSetter interface {
	SetUserID(uint64)
}

type PacketIDSetter interface {
	SetPacketID(*PacketID)
}

type HeaderSetter interface {
	SetHeader(*TrdHeader)
}

// AccumulateFilter
// 累积属性筛选

// 近几日，累积时间
func (s *AccumulateFilter) WithDays(o int32) *AccumulateFilter {
	s.Days = &o
	return s
}

func (s *AccumulateFilter) SetDays(o int32) {
	s.Days = &o
}

// AccumulateField 累积属性
func (s *AccumulateFilter) WithFieldName(o AccumulateField) *AccumulateFilter {
	s.FieldName = o.Enum()
	return s
}

func (s *AccumulateFilter) SetFieldName(o AccumulateField) {
	s.FieldName = o.Enum()
}

// 区间上限（闭区间），不传代表上限为 +∞
func (s *AccumulateFilter) WithFilterMax(o float64) *AccumulateFilter {
	s.FilterMax = &o
	return s
}

func (s *AccumulateFilter) SetFilterMax(o float64) {
	s.FilterMax = &o
}

// 区间下限（闭区间），不传代表下限为 -∞
func (s *AccumulateFilter) WithFilterMin(o float64) *AccumulateFilter {
	s.FilterMin = &o
	return s
}

func (s *AccumulateFilter) SetFilterMin(o float64) {
	s.FilterMin = &o
}

// 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
func (s *AccumulateFilter) WithIsNoFilter(o bool) *AccumulateFilter {
	s.IsNoFilter = &o
	return s
}

func (s *AccumulateFilter) SetIsNoFilter(o bool) {
	s.IsNoFilter = &o
}

// SortDir 排序方向，默认不排序。
func (s *AccumulateFilter) WithSortDir(o SortDir) *AccumulateFilter {
	s.SortDir = o.Enum()
	return s
}

func (s *AccumulateFilter) SetSortDir(o SortDir) {
	s.SortDir = o.Enum()
}

// BaseFilter
// 简单属性筛选

// StockField 简单属性
func (s *BaseFilter) WithFieldName(o StockField) *BaseFilter {
	s.FieldName = o.Enum()
	return s
}

func (s *BaseFilter) SetFieldName(o StockField) {
	s.FieldName = o.Enum()
}

// 区间上限（闭区间），不传代表上限为 +∞
func (s *BaseFilter) WithFilterMax(o float64) *BaseFilter {
	s.FilterMax = &o
	return s
}

func (s *BaseFilter) SetFilterMax(o float64) {
	s.FilterMax = &o
}

// 区间下限（闭区间），不传代表下限为 -∞
func (s *BaseFilter) WithFilterMin(o float64) *BaseFilter {
	s.FilterMin = &o
	return s
}

func (s *BaseFilter) SetFilterMin(o float64) {
	s.FilterMin = &o
}

// 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
func (s *BaseFilter) WithIsNoFilter(o bool) *BaseFilter {
	s.IsNoFilter = &o
	return s
}

func (s *BaseFilter) SetIsNoFilter(o bool) {
	s.IsNoFilter = &o
}

// SortDir 排序方向，默认不排序。
func (s *BaseFilter) WithSortDir(o SortDir) *BaseFilter {
	s.SortDir = o.Enum()
	return s
}

func (s *BaseFilter) SetSortDir(o SortDir) {
	s.SortDir = o.Enum()
}

// CustomIndicatorFilter
// 自定义技术指标属性筛选

// 筛选连续周期都符合条件的数据，填写范围为[1,12]
func (s *CustomIndicatorFilter) WithConsecutivePeriod(o int32) *CustomIndicatorFilter {
	s.ConsecutivePeriod = &o
	return s
}

func (s *CustomIndicatorFilter) SetConsecutivePeriod(o int32) {
	s.ConsecutivePeriod = &o
}

// 自定义数值。当 stock_field2 选择自定义数值时，value 为必传参数。支持与KDJ_K，KDJ_D，KDJ_J，MACD_DIFF，MACD_DEA，MACD，BOLL_UPPER，BOLL_MIDDLER，BOLL_LOWER 进行比较（stock_field1 不支持此字段）
func (s *CustomIndicatorFilter) WithFieldValue(o float64) *CustomIndicatorFilter {
	s.FieldValue = &o
	return s
}

func (s *CustomIndicatorFilter) SetFieldValue(o float64) {
	s.FieldValue = &o
}

// CustomIndicatorField 自定义技术指标属性
func (s *CustomIndicatorFilter) WithFirstFieldName(o CustomIndicatorField) *CustomIndicatorFilter {
	s.FirstFieldName = o.Enum()
	return s
}

func (s *CustomIndicatorFilter) SetFirstFieldName(o CustomIndicatorField) {
	s.FirstFieldName = o.Enum()
}

// 自定义指标参数 根据指标类型进行传参：1. MA：[平均移动周期] 2.EMA：[指数移动平均周期] 3.RSI：[RSI 指标周期] 4.MACD：[快速平均线值, 慢速平均线值, DIF值] 5.BOLL：[均线周期, 偏移值] 6.KDJ：[RSV 周期, K 值计算周期, D 值计算周期]
func (s *CustomIndicatorFilter) WithFirstFieldParaList(o ...int32) *CustomIndicatorFilter {
	s.FirstFieldParaList = o
	return s
}

func (s *CustomIndicatorFilter) SetFirstFieldParaList(o ...int32) {
	s.FirstFieldParaList = o
}

// 该字段是否不需要筛选，True代表不筛选，False代表筛选。不传默认为不筛选
func (s *CustomIndicatorFilter) WithIsNoFilter(o bool) *CustomIndicatorFilter {
	s.IsNoFilter = &o
	return s
}

func (s *CustomIndicatorFilter) SetIsNoFilter(o bool) {
	s.IsNoFilter = &o
}

// KLType，K线类型，仅支持K_60M，K_DAY，K_WEEK，K_MON 四种时间周期
func (s *CustomIndicatorFilter) WithKlType(o KLType) *CustomIndicatorFilter {
	s.KlType = o.Enum()
	return s
}

func (s *CustomIndicatorFilter) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// RelativePosition 相对位置
func (s *CustomIndicatorFilter) WithRelativePosition(o RelativePosition) *CustomIndicatorFilter {
	s.RelativePosition = o.Enum()
	return s
}

func (s *CustomIndicatorFilter) SetRelativePosition(o RelativePosition) {
	s.RelativePosition = o.Enum()
}

// CustomIndicatorField 自定义技术指标属性
func (s *CustomIndicatorFilter) WithSecondFieldName(o CustomIndicatorField) *CustomIndicatorFilter {
	s.SecondFieldName = o.Enum()
	return s
}

func (s *CustomIndicatorFilter) SetSecondFieldName(o CustomIndicatorField) {
	s.SecondFieldName = o.Enum()
}

// 自定义指标参数 根据指标类型进行传参：1. MA：[平均移动周期] 2.EMA：[指数移动平均周期] 3.RSI：[RSI 指标周期] 4.MACD：[快速平均线值, 慢速平均线值, DIF值] 5.BOLL：[均线周期, 偏移值] 6.KDJ：[RSV 周期, K 值计算周期, D 值计算周期]
func (s *CustomIndicatorFilter) WithSecondFieldParaList(o ...int32) *CustomIndicatorFilter {
	s.SecondFieldParaList = o
	return s
}

func (s *CustomIndicatorFilter) SetSecondFieldParaList(o ...int32) {
	s.SecondFieldParaList = o
}

// DataFilter
//以下为数据字段筛选，可选字段，不填表示不过滤

// 希腊值 Delta过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithDeltaMax(o float64) *DataFilter {
	s.DeltaMax = &o
	return s
}

func (s *DataFilter) SetDeltaMax(o float64) {
	s.DeltaMax = &o
}

// 希腊值 Delta过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithDeltaMin(o float64) *DataFilter {
	s.DeltaMin = &o
	return s
}

func (s *DataFilter) SetDeltaMin(o float64) {
	s.DeltaMin = &o
}

// 希腊值 Gamma过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithGammaMax(o float64) *DataFilter {
	s.GammaMax = &o
	return s
}

func (s *DataFilter) SetGammaMax(o float64) {
	s.GammaMax = &o
}

// 希腊值 Gamma过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithGammaMin(o float64) *DataFilter {
	s.GammaMin = &o
	return s
}

func (s *DataFilter) SetGammaMin(o float64) {
	s.GammaMin = &o
}

// 隐含波动率过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithImpliedVolatilityMax(o float64) *DataFilter {
	s.ImpliedVolatilityMax = &o
	return s
}

func (s *DataFilter) SetImpliedVolatilityMax(o float64) {
	s.ImpliedVolatilityMax = &o
}

// 隐含波动率过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithImpliedVolatilityMin(o float64) *DataFilter {
	s.ImpliedVolatilityMin = &o
	return s
}

func (s *DataFilter) SetImpliedVolatilityMin(o float64) {
	s.ImpliedVolatilityMin = &o
}

// 净未平仓合约数过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithNetOpenInterestMax(o float64) *DataFilter {
	s.NetOpenInterestMax = &o
	return s
}

func (s *DataFilter) SetNetOpenInterestMax(o float64) {
	s.NetOpenInterestMax = &o
}

// 净未平仓合约数过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithNetOpenInterestMin(o float64) *DataFilter {
	s.NetOpenInterestMin = &o
	return s
}

func (s *DataFilter) SetNetOpenInterestMin(o float64) {
	s.NetOpenInterestMin = &o
}

// 未平仓合约数过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithOpenInterestMax(o float64) *DataFilter {
	s.OpenInterestMax = &o
	return s
}

func (s *DataFilter) SetOpenInterestMax(o float64) {
	s.OpenInterestMax = &o
}

// 未平仓合约数过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithOpenInterestMin(o float64) *DataFilter {
	s.OpenInterestMin = &o
	return s
}

func (s *DataFilter) SetOpenInterestMin(o float64) {
	s.OpenInterestMin = &o
}

// 希腊值 Rho过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithRhoMax(o float64) *DataFilter {
	s.RhoMax = &o
	return s
}

func (s *DataFilter) SetRhoMax(o float64) {
	s.RhoMax = &o
}

// 希腊值 Rho过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithRhoMin(o float64) *DataFilter {
	s.RhoMin = &o
	return s
}

func (s *DataFilter) SetRhoMin(o float64) {
	s.RhoMin = &o
}

// 希腊值 Theta过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithThetaMax(o float64) *DataFilter {
	s.ThetaMax = &o
	return s
}

func (s *DataFilter) SetThetaMax(o float64) {
	s.ThetaMax = &o
}

// 希腊值 Theta过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithThetaMin(o float64) *DataFilter {
	s.ThetaMin = &o
	return s
}

func (s *DataFilter) SetThetaMin(o float64) {
	s.ThetaMin = &o
}

// 希腊值 Vega过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithVegaMax(o float64) *DataFilter {
	s.VegaMax = &o
	return s
}

func (s *DataFilter) SetVegaMax(o float64) {
	s.VegaMax = &o
}

// 希腊值 Vega过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
func (s *DataFilter) WithVegaMin(o float64) *DataFilter {
	s.VegaMin = &o
	return s
}

func (s *DataFilter) SetVegaMin(o float64) {
	s.VegaMin = &o
}

// 成交量过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithVolMax(o float64) *DataFilter {
	s.VolMax = &o
	return s
}

func (s *DataFilter) SetVolMax(o float64) {
	s.VolMax = &o
}

// 成交量过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
func (s *DataFilter) WithVolMin(o float64) *DataFilter {
	s.VolMin = &o
	return s
}

func (s *DataFilter) SetVolMin(o float64) {
	s.VolMin = &o
}

// FinancialFilter
// 财务属性筛选

// FinancialField 财务属性
func (s *FinancialFilter) WithFieldName(o FinancialField) *FinancialFilter {
	s.FieldName = o.Enum()
	return s
}

func (s *FinancialFilter) SetFieldName(o FinancialField) {
	s.FieldName = o.Enum()
}

// 区间上限（闭区间），不传代表上限为 +∞
func (s *FinancialFilter) WithFilterMax(o float64) *FinancialFilter {
	s.FilterMax = &o
	return s
}

func (s *FinancialFilter) SetFilterMax(o float64) {
	s.FilterMax = &o
}

// 区间下限（闭区间），不传代表下限为 -∞
func (s *FinancialFilter) WithFilterMin(o float64) *FinancialFilter {
	s.FilterMin = &o
	return s
}

func (s *FinancialFilter) SetFilterMin(o float64) {
	s.FilterMin = &o
}

// 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
func (s *FinancialFilter) WithIsNoFilter(o bool) *FinancialFilter {
	s.IsNoFilter = &o
	return s
}

func (s *FinancialFilter) SetIsNoFilter(o bool) {
	s.IsNoFilter = &o
}

// FinancialQuarter 财报累积时间
func (s *FinancialFilter) WithQuarter(o FinancialQuarter) *FinancialFilter {
	s.Quarter = o.Enum()
	return s
}

func (s *FinancialFilter) SetQuarter(o FinancialQuarter) {
	s.Quarter = o.Enum()
}

// SortDir 排序方向，默认不排序。
func (s *FinancialFilter) WithSortDir(o SortDir) *FinancialFilter {
	s.SortDir = o.Enum()
	return s
}

func (s *FinancialFilter) SetSortDir(o SortDir) {
	s.SortDir = o.Enum()
}

// GetDelayStatisticsRequest

// 行情推送统计的区间，行情推送统计时有效，QotPushStage
func (s *GetDelayStatisticsRequest) WithPushStage(o QotPushStage) *GetDelayStatisticsRequest {
	s.QotPushStage = o.Enum()
	return s
}

func (s *GetDelayStatisticsRequest) SetPushStage(o QotPushStage) {
	s.QotPushStage = o.Enum()
}

// 统计分段，默认100ms以下以2ms分段，100ms以上以500，1000，2000，-1分段，-1表示无穷大。
func (s *GetDelayStatisticsRequest) WithSegmentList(o ...int32) *GetDelayStatisticsRequest {
	s.SegmentList = o
	return s
}

func (s *GetDelayStatisticsRequest) SetSegmentList(o ...int32) {
	s.SegmentList = o
}

// 统计数据类型，DelayStatisticsType
func (s *GetDelayStatisticsRequest) WithTypeList(o ...DelayStatisticsType) *GetDelayStatisticsRequest {
	s.TypeList = o
	return s
}

func (s *GetDelayStatisticsRequest) SetTypeList(o ...DelayStatisticsType) {
	s.TypeList = o
}

// GetGlobalStateRequest

// 历史原因，目前已废弃，填0即可
func (s *GetGlobalStateRequest) WithUserID(o uint64) *GetGlobalStateRequest {
	s.UserID = &o
	return s
}

func (s *GetGlobalStateRequest) SetUserID(o uint64) {
	s.UserID = &o
}

// GetUserInfoRequest

// UserInfoField集合，不设置默认返回全部信息
func (s *GetUserInfoRequest) WithFlag(o int32) *GetUserInfoRequest {
	s.Flag = &o
	return s
}

func (s *GetUserInfoRequest) SetFlag(o int32) {
	s.Flag = &o
}

// InitConnectRequest

// 客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
func (s *InitConnectRequest) WithClientID(o string) *InitConnectRequest {
	s.ClientID = &o
	return s
}

func (s *InitConnectRequest) SetClientID(o string) {
	s.ClientID = &o
}

// 客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
func (s *InitConnectRequest) WithClientVer(o int32) *InitConnectRequest {
	s.ClientVer = &o
	return s
}

func (s *InitConnectRequest) SetClientVer(o int32) {
	s.ClientVer = &o
}

// 指定包加密算法，参见Common.PacketEncAlgo的枚举定义
func (s *InitConnectRequest) WithPacketEncAlgo(o PacketEncAlgo) *InitConnectRequest {
	s.PacketEncAlgo = o.Enum()
	return s
}

func (s *InitConnectRequest) SetPacketEncAlgo(o PacketEncAlgo) {
	s.PacketEncAlgo = o.Enum()
}

// 接口编程语言，用于统计语言偏好
func (s *InitConnectRequest) WithProgrammingLanguage(o string) *InitConnectRequest {
	s.ProgrammingLanguage = &o
	return s
}

func (s *InitConnectRequest) SetProgrammingLanguage(o string) {
	s.ProgrammingLanguage = &o
}

// 指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
func (s *InitConnectRequest) WithPushProtoFmt(o ProtoFmt) *InitConnectRequest {
	s.PushProtoFmt = o.Enum()
	return s
}

func (s *InitConnectRequest) SetPushProtoFmt(o ProtoFmt) {
	s.PushProtoFmt = o.Enum()
}

// 此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
func (s *InitConnectRequest) WithRecvNotify(o bool) *InitConnectRequest {
	s.RecvNotify = &o
	return s
}

func (s *InitConnectRequest) SetRecvNotify(o bool) {
	s.RecvNotify = &o
}

// KeepAliveRequest

// 客户端发包时的格林威治时间戳，单位秒
func (s *KeepAliveRequest) WithTime(o int64) *KeepAliveRequest {
	s.Time = &o
	return s
}

func (s *KeepAliveRequest) SetTime(o int64) {
	s.Time = &o
}

// PacketID
//包的唯一标识，用于回放攻击的识别和保护

// 当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
func (s *PacketID) WithConnID(o uint64) *PacketID {
	s.ConnID = &o
	return s
}

func (s *PacketID) SetConnID(o uint64) {
	s.ConnID = &o
}

// 自增序列号
func (s *PacketID) WithSerialNo(o uint32) *PacketID {
	s.SerialNo = &o
	return s
}

func (s *PacketID) SetSerialNo(o uint32) {
	s.SerialNo = &o
}

// PatternFilter
// 形态技术指标属性筛选

// 筛选连续周期都符合条件的数据，填写范围为[1,12]
func (s *PatternFilter) WithConsecutivePeriod(o int32) *PatternFilter {
	s.ConsecutivePeriod = &o
	return s
}

func (s *PatternFilter) SetConsecutivePeriod(o int32) {
	s.ConsecutivePeriod = &o
}

// PatternField 形态技术指标属性
func (s *PatternFilter) WithFieldName(o PatternField) *PatternFilter {
	s.FieldName = o.Enum()
	return s
}

func (s *PatternFilter) SetFieldName(o PatternField) {
	s.FieldName = o.Enum()
}

// 该字段是否不需要筛选，True代表不筛选，False代表筛选。不传默认为不筛选
func (s *PatternFilter) WithIsNoFilter(o bool) *PatternFilter {
	s.IsNoFilter = &o
	return s
}

func (s *PatternFilter) SetIsNoFilter(o bool) {
	s.IsNoFilter = &o
}

// KLType，K线类型，仅支持K_60M，K_DAY，K_WEEK，K_MON 四种时间周期
func (s *PatternFilter) WithKlType(o KLType) *PatternFilter {
	s.KlType = o.Enum()
	return s
}

func (s *PatternFilter) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// QotGetBasicQotRequest

// 股票
func (s *QotGetBasicQotRequest) WithSecurityList(o ...*Security) *QotGetBasicQotRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetBasicQotRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetBrokerRequest

// 股票
func (s *QotGetBrokerRequest) WithSecurity(o *Security) *QotGetBrokerRequest {
	s.Security = o
	return s
}

func (s *QotGetBrokerRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetCapitalDistributionRequest

// 股票
func (s *QotGetCapitalDistributionRequest) WithSecurity(o *Security) *QotGetCapitalDistributionRequest {
	s.Security = o
	return s
}

func (s *QotGetCapitalDistributionRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetCapitalFlowRequest

// 开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
func (s *QotGetCapitalFlowRequest) WithBeginTime(o string) *QotGetCapitalFlowRequest {
	s.BeginTime = &o
	return s
}

func (s *QotGetCapitalFlowRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
func (s *QotGetCapitalFlowRequest) WithEndTime(o string) *QotGetCapitalFlowRequest {
	s.EndTime = &o
	return s
}

func (s *QotGetCapitalFlowRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// PeriodType 周期类型
func (s *QotGetCapitalFlowRequest) WithPeriodType(o PeriodType) *QotGetCapitalFlowRequest {
	s.PeriodType = o.Enum()
	return s
}

func (s *QotGetCapitalFlowRequest) SetPeriodType(o PeriodType) {
	s.PeriodType = o.Enum()
}

// 股票
func (s *QotGetCapitalFlowRequest) WithSecurity(o *Security) *QotGetCapitalFlowRequest {
	s.Security = o
	return s
}

func (s *QotGetCapitalFlowRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetCodeChangeRequest

// 占位
func (s *QotGetCodeChangeRequest) WithPlaceHolder(o int32) *QotGetCodeChangeRequest {
	s.PlaceHolder = &o
	return s
}

func (s *QotGetCodeChangeRequest) SetPlaceHolder(o int32) {
	s.PlaceHolder = &o
}

// 根据股票筛选
func (s *QotGetCodeChangeRequest) WithSecurityList(o ...*Security) *QotGetCodeChangeRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetCodeChangeRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// 根据时间筛选
func (s *QotGetCodeChangeRequest) WithTimeFilterList(o ...*TimeFilter) *QotGetCodeChangeRequest {
	s.TimeFilterList = o
	return s
}

func (s *QotGetCodeChangeRequest) SetTimeFilterList(o ...*TimeFilter) {
	s.TimeFilterList = o
}

// CodeChangeType，根据类型筛选
func (s *QotGetCodeChangeRequest) WithTypeList(o ...CodeChangeType) *QotGetCodeChangeRequest {
	s.TypeList = o
	return s
}

func (s *QotGetCodeChangeRequest) SetTypeList(o ...CodeChangeType) {
	s.TypeList = o
}

// QotGetFutureInfoRequest

// 股票列表
func (s *QotGetFutureInfoRequest) WithSecurityList(o ...*Security) *QotGetFutureInfoRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetFutureInfoRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetHistoryKLPointsRequest

// Qot_Common.KLType,K线类型
func (s *QotGetHistoryKLPointsRequest) WithKlType(o KLType) *QotGetHistoryKLPointsRequest {
	s.KlType = o.Enum()
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// 最多返回多少只股票的数据，如果未指定表示不限制
func (s *QotGetHistoryKLPointsRequest) WithMaxReqSecurityNum(o int32) *QotGetHistoryKLPointsRequest {
	s.MaxReqSecurityNum = &o
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetMaxReqSecurityNum(o int32) {
	s.MaxReqSecurityNum = &o
}

// 指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
func (s *QotGetHistoryKLPointsRequest) WithNeedKLFieldsFlag(o int64) *QotGetHistoryKLPointsRequest {
	s.NeedKLFieldsFlag = &o
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetNeedKLFieldsFlag(o int64) {
	s.NeedKLFieldsFlag = &o
}

// NoDataMode,当请求时间点数据为空时，如何返回数据
func (s *QotGetHistoryKLPointsRequest) WithNoDataMode(o NoDataMode) *QotGetHistoryKLPointsRequest {
	s.NoDataMode = o.Enum()
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetNoDataMode(o NoDataMode) {
	s.NoDataMode = o.Enum()
}

// Qot_Common.RehabType,复权类型
func (s *QotGetHistoryKLPointsRequest) WithRehabType(o RehabType) *QotGetHistoryKLPointsRequest {
	s.RehabType = o.Enum()
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetRehabType(o RehabType) {
	s.RehabType = o.Enum()
}

// 股票市场以及股票代码
func (s *QotGetHistoryKLPointsRequest) WithSecurityList(o ...*Security) *QotGetHistoryKLPointsRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// 时间字符串
func (s *QotGetHistoryKLPointsRequest) WithTimeList(o ...string) *QotGetHistoryKLPointsRequest {
	s.TimeList = o
	return s
}

func (s *QotGetHistoryKLPointsRequest) SetTimeList(o ...string) {
	s.TimeList = o
}

// QotGetHistoryKLRequest

// 开始时间字符串
func (s *QotGetHistoryKLRequest) WithBeginTime(o string) *QotGetHistoryKLRequest {
	s.BeginTime = &o
	return s
}

func (s *QotGetHistoryKLRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间字符串
func (s *QotGetHistoryKLRequest) WithEndTime(o string) *QotGetHistoryKLRequest {
	s.EndTime = &o
	return s
}

func (s *QotGetHistoryKLRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// Qot_Common.KLType,K线类型
func (s *QotGetHistoryKLRequest) WithKlType(o KLType) *QotGetHistoryKLRequest {
	s.KlType = o.Enum()
	return s
}

func (s *QotGetHistoryKLRequest) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// 最多返回多少根K线，如果未指定表示不限制
func (s *QotGetHistoryKLRequest) WithMaxAckKLNum(o int32) *QotGetHistoryKLRequest {
	s.MaxAckKLNum = &o
	return s
}

func (s *QotGetHistoryKLRequest) SetMaxAckKLNum(o int32) {
	s.MaxAckKLNum = &o
}

// 指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
func (s *QotGetHistoryKLRequest) WithNeedKLFieldsFlag(o int64) *QotGetHistoryKLRequest {
	s.NeedKLFieldsFlag = &o
	return s
}

func (s *QotGetHistoryKLRequest) SetNeedKLFieldsFlag(o int64) {
	s.NeedKLFieldsFlag = &o
}

// Qot_Common.RehabType,复权类型
func (s *QotGetHistoryKLRequest) WithRehabType(o RehabType) *QotGetHistoryKLRequest {
	s.RehabType = o.Enum()
	return s
}

func (s *QotGetHistoryKLRequest) SetRehabType(o RehabType) {
	s.RehabType = o.Enum()
}

// 股票市场以及股票代码
func (s *QotGetHistoryKLRequest) WithSecurity(o *Security) *QotGetHistoryKLRequest {
	s.Security = o
	return s
}

func (s *QotGetHistoryKLRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetHoldingChangeListRequest

// 开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
func (s *QotGetHoldingChangeListRequest) WithBeginTime(o string) *QotGetHoldingChangeListRequest {
	s.BeginTime = &o
	return s
}

func (s *QotGetHoldingChangeListRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
func (s *QotGetHoldingChangeListRequest) WithEndTime(o string) *QotGetHoldingChangeListRequest {
	s.EndTime = &o
	return s
}

func (s *QotGetHoldingChangeListRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// 持有者类别（1机构、2基金、3高管）
func (s *QotGetHoldingChangeListRequest) WithHolderCategory(o HolderCategory) *QotGetHoldingChangeListRequest {
	s.HolderCategory = o.Enum()
	return s
}

func (s *QotGetHoldingChangeListRequest) SetHolderCategory(o HolderCategory) {
	s.HolderCategory = o.Enum()
}

// 股票
func (s *QotGetHoldingChangeListRequest) WithSecurity(o *Security) *QotGetHoldingChangeListRequest {
	s.Security = o
	return s
}

func (s *QotGetHoldingChangeListRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetIpoListRequest

// Qot_Common::QotMarket股票市场，支持沪股和深股，且沪股和深股不做区分都代表A股市场。
func (s *QotGetIpoListRequest) WithMarket(o QotMarket) *QotGetIpoListRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotGetIpoListRequest) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// QotGetKLRequest

// Qot_Common.KLType,K线类型
func (s *QotGetKLRequest) WithKlType(o KLType) *QotGetKLRequest {
	s.KlType = o.Enum()
	return s
}

func (s *QotGetKLRequest) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// Qot_Common.RehabType,复权类型
func (s *QotGetKLRequest) WithRehabType(o RehabType) *QotGetKLRequest {
	s.RehabType = o.Enum()
	return s
}

func (s *QotGetKLRequest) SetRehabType(o RehabType) {
	s.RehabType = o.Enum()
}

// 请求K线根数
func (s *QotGetKLRequest) WithReqNum(o int32) *QotGetKLRequest {
	s.ReqNum = &o
	return s
}

func (s *QotGetKLRequest) SetReqNum(o int32) {
	s.ReqNum = &o
}

// 股票
func (s *QotGetKLRequest) WithSecurity(o *Security) *QotGetKLRequest {
	s.Security = o
	return s
}

func (s *QotGetKLRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetMarketStateRequest

// 股票列表
func (s *QotGetMarketStateRequest) WithSecurityList(o ...*Security) *QotGetMarketStateRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetMarketStateRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetOptionChainRequest

// 期权到期日开始时间
func (s *QotGetOptionChainRequest) WithBeginTime(o string) *QotGetOptionChainRequest {
	s.BeginTime = &o
	return s
}

func (s *QotGetOptionChainRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// OptionCondType，价内价外，可选字段，不指定则表示都返回
func (s *QotGetOptionChainRequest) WithCondition(o OptionCondType) *QotGetOptionChainRequest {
	s.Condition = o.Enum()
	return s
}

func (s *QotGetOptionChainRequest) SetCondition(o OptionCondType) {
	s.Condition = o.Enum()
}

// 数据字段筛选
func (s *QotGetOptionChainRequest) WithDataFilter(o *DataFilter) *QotGetOptionChainRequest {
	s.DataFilter = o
	return s
}

func (s *QotGetOptionChainRequest) SetDataFilter(o *DataFilter) {
	s.DataFilter = o
}

// 期权到期日结束时间，时间跨度最多一个月
func (s *QotGetOptionChainRequest) WithEndTime(o string) *QotGetOptionChainRequest {
	s.EndTime = &o
	return s
}

func (s *QotGetOptionChainRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
func (s *QotGetOptionChainRequest) WithIndexOptionType(o IndexOptionType) *QotGetOptionChainRequest {
	s.IndexOptionType = o.Enum()
	return s
}

func (s *QotGetOptionChainRequest) SetIndexOptionType(o IndexOptionType) {
	s.IndexOptionType = o.Enum()
}

// 期权标的股，目前仅支持传入港美正股以及恒指国指
func (s *QotGetOptionChainRequest) WithOwner(o *Security) *QotGetOptionChainRequest {
	s.Owner = o
	return s
}

func (s *QotGetOptionChainRequest) SetOwner(o *Security) {
	s.Owner = o
}

// Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
func (s *QotGetOptionChainRequest) WithType(o OptionType) *QotGetOptionChainRequest {
	s.Type = o.Enum()
	return s
}

func (s *QotGetOptionChainRequest) SetType(o OptionType) {
	s.Type = o.Enum()
}

// QotGetOptionExpirationDateRequest

// Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
func (s *QotGetOptionExpirationDateRequest) WithIndexOptionType(o IndexOptionType) *QotGetOptionExpirationDateRequest {
	s.IndexOptionType = o.Enum()
	return s
}

func (s *QotGetOptionExpirationDateRequest) SetIndexOptionType(o IndexOptionType) {
	s.IndexOptionType = o.Enum()
}

// 期权标的股，目前仅支持传入港美正股以及恒指国指
func (s *QotGetOptionExpirationDateRequest) WithOwner(o *Security) *QotGetOptionExpirationDateRequest {
	s.Owner = o
	return s
}

func (s *QotGetOptionExpirationDateRequest) SetOwner(o *Security) {
	s.Owner = o
}

// QotGetOrderBookRequest

// 请求的摆盘个数
func (s *QotGetOrderBookRequest) WithNum(o int32) *QotGetOrderBookRequest {
	s.Num = &o
	return s
}

func (s *QotGetOrderBookRequest) SetNum(o int32) {
	s.Num = &o
}

// 股票
func (s *QotGetOrderBookRequest) WithSecurity(o *Security) *QotGetOrderBookRequest {
	s.Security = o
	return s
}

func (s *QotGetOrderBookRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetOwnerPlateRequest

// 股票
func (s *QotGetOwnerPlateRequest) WithSecurityList(o ...*Security) *QotGetOwnerPlateRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetOwnerPlateRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetPlateSecurityRequest

// 升序ture, 降序false, 不填默认升序
func (s *QotGetPlateSecurityRequest) WithAscend(o bool) *QotGetPlateSecurityRequest {
	s.Ascend = &o
	return s
}

func (s *QotGetPlateSecurityRequest) SetAscend(o bool) {
	s.Ascend = &o
}

// 板块
func (s *QotGetPlateSecurityRequest) WithPlate(o *Security) *QotGetPlateSecurityRequest {
	s.Plate = o
	return s
}

func (s *QotGetPlateSecurityRequest) SetPlate(o *Security) {
	s.Plate = o
}

// Qot_Common.SortField,根据哪个字段排序,不填默认Code排序
func (s *QotGetPlateSecurityRequest) WithSortField(o SortField) *QotGetPlateSecurityRequest {
	s.SortField = o.Enum()
	return s
}

func (s *QotGetPlateSecurityRequest) SetSortField(o SortField) {
	s.SortField = o.Enum()
}

// QotGetPlateSetRequest

// Qot_Common.QotMarket,股票市场
func (s *QotGetPlateSetRequest) WithMarket(o QotMarket) *QotGetPlateSetRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotGetPlateSetRequest) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// Qot_Common.PlateSetType,板块集合的类型
func (s *QotGetPlateSetRequest) WithPlateSetType(o PlateSetType) *QotGetPlateSetRequest {
	s.PlateSetType = o.Enum()
	return s
}

func (s *QotGetPlateSetRequest) SetPlateSetType(o PlateSetType) {
	s.PlateSetType = o.Enum()
}

// QotGetPriceReminderRequest

// Qot_Common::QotMarket 市场，查询市场下的到价提醒项，不区分沪深
func (s *QotGetPriceReminderRequest) WithMarket(o QotMarket) *QotGetPriceReminderRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotGetPriceReminderRequest) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// 查询股票下的到价提醒项，security和market二选一，都存在的情况下security优先。
func (s *QotGetPriceReminderRequest) WithSecurity(o *Security) *QotGetPriceReminderRequest {
	s.Security = o
	return s
}

func (s *QotGetPriceReminderRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetRTRequest

// 股票
func (s *QotGetRTRequest) WithSecurity(o *Security) *QotGetRTRequest {
	s.Security = o
	return s
}

func (s *QotGetRTRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetReferenceRequest

// ReferenceType, 相关类型
func (s *QotGetReferenceRequest) WithReferenceType(o ReferenceType) *QotGetReferenceRequest {
	s.ReferenceType = o.Enum()
	return s
}

func (s *QotGetReferenceRequest) SetReferenceType(o ReferenceType) {
	s.ReferenceType = o.Enum()
}

// 股票
func (s *QotGetReferenceRequest) WithSecurity(o *Security) *QotGetReferenceRequest {
	s.Security = o
	return s
}

func (s *QotGetReferenceRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetRehabRequest

// 股票
func (s *QotGetRehabRequest) WithSecurityList(o ...*Security) *QotGetRehabRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetRehabRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetSecuritySnapshotRequest

// 股票
func (s *QotGetSecuritySnapshotRequest) WithSecurityList(o ...*Security) *QotGetSecuritySnapshotRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetSecuritySnapshotRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetStaticInfoRequest

// Qot_Common.QotMarket,股票市场
func (s *QotGetStaticInfoRequest) WithMarket(o QotMarket) *QotGetStaticInfoRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotGetStaticInfoRequest) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// Qot_Common.SecurityType,股票类型
func (s *QotGetStaticInfoRequest) WithSecType(o SecurityType) *QotGetStaticInfoRequest {
	s.SecType = o.Enum()
	return s
}

func (s *QotGetStaticInfoRequest) SetSecType(o SecurityType) {
	s.SecType = o.Enum()
}

// 股票，若该字段存在，忽略其他字段，只返回该字段股票的静态信息
func (s *QotGetStaticInfoRequest) WithSecurityList(o ...*Security) *QotGetStaticInfoRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetStaticInfoRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetSubInfoRequest

// 是否返回所有连接的订阅状态,不传或者传false只返回当前连接数据
func (s *QotGetSubInfoRequest) WithIsReqAllConn(o bool) *QotGetSubInfoRequest {
	s.IsReqAllConn = &o
	return s
}

func (s *QotGetSubInfoRequest) SetIsReqAllConn(o bool) {
	s.IsReqAllConn = &o
}

// QotGetSuspendRequest

// 开始时间字符串
func (s *QotGetSuspendRequest) WithBeginTime(o string) *QotGetSuspendRequest {
	s.BeginTime = &o
	return s
}

func (s *QotGetSuspendRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间字符串
func (s *QotGetSuspendRequest) WithEndTime(o string) *QotGetSuspendRequest {
	s.EndTime = &o
	return s
}

func (s *QotGetSuspendRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// 股票
func (s *QotGetSuspendRequest) WithSecurityList(o ...*Security) *QotGetSuspendRequest {
	s.SecurityList = o
	return s
}

func (s *QotGetSuspendRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotGetTickerRequest

// 最多返回的逐笔个数,实际返回数量不一定会返回这么多,最多返回1000个
func (s *QotGetTickerRequest) WithMaxRetNum(o int32) *QotGetTickerRequest {
	s.MaxRetNum = &o
	return s
}

func (s *QotGetTickerRequest) SetMaxRetNum(o int32) {
	s.MaxRetNum = &o
}

// 股票
func (s *QotGetTickerRequest) WithSecurity(o *Security) *QotGetTickerRequest {
	s.Security = o
	return s
}

func (s *QotGetTickerRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotGetUserSecurityGroupRequest

// GroupType,自选股分组类型。
func (s *QotGetUserSecurityGroupRequest) WithGroupType(o GroupType) *QotGetUserSecurityGroupRequest {
	s.GroupType = o.Enum()
	return s
}

func (s *QotGetUserSecurityGroupRequest) SetGroupType(o GroupType) {
	s.GroupType = o.Enum()
}

// QotGetUserSecurityRequest

// 分组名,有同名的返回排序首个
func (s *QotGetUserSecurityRequest) WithGroupName(o string) *QotGetUserSecurityRequest {
	s.GroupName = &o
	return s
}

func (s *QotGetUserSecurityRequest) SetGroupName(o string) {
	s.GroupName = &o
}

// QotGetWarrantRequest

// 升序ture，降序false
func (s *QotGetWarrantRequest) WithAscend(o bool) *QotGetWarrantRequest {
	s.Ascend = &o
	return s
}

func (s *QotGetWarrantRequest) SetAscend(o bool) {
	s.Ascend = &o
}

// 数据起始点
func (s *QotGetWarrantRequest) WithBegin(o int32) *QotGetWarrantRequest {
	s.Begin = &o
	return s
}

func (s *QotGetWarrantRequest) SetBegin(o int32) {
	s.Begin = &o
}

// 换股比率的过滤上限（闭区间），不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithConversionMax(o float64) *QotGetWarrantRequest {
	s.ConversionMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetConversionMax(o float64) {
	s.ConversionMax = &o
}

// 换股比率的过滤下限（闭区间），不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithConversionMin(o float64) *QotGetWarrantRequest {
	s.ConversionMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetConversionMin(o float64) {
	s.ConversionMin = &o
}

// 最新价的过滤上限（闭区间），不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithCurPriceMax(o float64) *QotGetWarrantRequest {
	s.CurPriceMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetCurPriceMax(o float64) {
	s.CurPriceMax = &o
}

// 最新价的过滤下限（闭区间），不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithCurPriceMin(o float64) *QotGetWarrantRequest {
	s.CurPriceMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetCurPriceMin(o float64) {
	s.CurPriceMin = &o
}

// 对冲值的过滤上限（闭区间），仅认购认沽支持此字段过滤，不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithDeltaMax(o float64) *QotGetWarrantRequest {
	s.DeltaMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetDeltaMax(o float64) {
	s.DeltaMax = &o
}

// 对冲值的过滤下限（闭区间），仅认购认沽支持此字段过滤，不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithDeltaMin(o float64) *QotGetWarrantRequest {
	s.DeltaMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetDeltaMin(o float64) {
	s.DeltaMin = &o
}

// 引伸波幅的过滤上限（闭区间），仅认购认沽支持此字段过滤，不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithImpliedMax(o float64) *QotGetWarrantRequest {
	s.ImpliedMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetImpliedMax(o float64) {
	s.ImpliedMax = &o
}

// 引伸波幅的过滤下限（闭区间），仅认购认沽支持此字段过滤，不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithImpliedMin(o float64) *QotGetWarrantRequest {
	s.ImpliedMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetImpliedMin(o float64) {
	s.ImpliedMin = &o
}

// Qot_Common.IpoPeriod，上市日
func (s *QotGetWarrantRequest) WithIpoPeriod(o IpoPeriod) *QotGetWarrantRequest {
	s.IpoPeriod = o.Enum()
	return s
}

func (s *QotGetWarrantRequest) SetIpoPeriod(o IpoPeriod) {
	s.IpoPeriod = o.Enum()
}

// Qot_Common.Issuer，发行人过滤列表
func (s *QotGetWarrantRequest) WithIssuerList(o ...Issuer) *QotGetWarrantRequest {
	s.IssuerList = o
	return s
}

func (s *QotGetWarrantRequest) SetIssuerList(o ...Issuer) {
	s.IssuerList = o
}

// 杠杆比率的过滤上限（闭区间），不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithLeverageRatioMax(o float64) *QotGetWarrantRequest {
	s.LeverageRatioMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetLeverageRatioMax(o float64) {
	s.LeverageRatioMax = &o
}

// 杠杆比率的过滤下限（闭区间），不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithLeverageRatioMin(o float64) *QotGetWarrantRequest {
	s.LeverageRatioMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetLeverageRatioMin(o float64) {
	s.LeverageRatioMin = &o
}

// 到期日范围的结束时间戳
func (s *QotGetWarrantRequest) WithMaturityTimeMax(o string) *QotGetWarrantRequest {
	s.MaturityTimeMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetMaturityTimeMax(o string) {
	s.MaturityTimeMax = &o
}

// 到期日，到期日范围的开始时间戳
func (s *QotGetWarrantRequest) WithMaturityTimeMin(o string) *QotGetWarrantRequest {
	s.MaturityTimeMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetMaturityTimeMin(o string) {
	s.MaturityTimeMin = &o
}

// 请求数据个数，最大200
func (s *QotGetWarrantRequest) WithNum(o int32) *QotGetWarrantRequest {
	s.Num = &o
	return s
}

func (s *QotGetWarrantRequest) SetNum(o int32) {
	s.Num = &o
}

// 所属正股
func (s *QotGetWarrantRequest) WithOwner(o *Security) *QotGetWarrantRequest {
	s.Owner = o
	return s
}

func (s *QotGetWarrantRequest) SetOwner(o *Security) {
	s.Owner = o
}

// 溢价的过滤上限（闭区间），该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithPremiumMax(o float64) *QotGetWarrantRequest {
	s.PremiumMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetPremiumMax(o float64) {
	s.PremiumMax = &o
}

// 溢价的过滤下限（闭区间），该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithPremiumMin(o float64) *QotGetWarrantRequest {
	s.PremiumMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetPremiumMin(o float64) {
	s.PremiumMin = &o
}

// 正股距收回价，的过滤上限（闭区间），仅牛熊证支持此字段过滤。该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithPriceRecoveryRatioMax(o float64) *QotGetWarrantRequest {
	s.PriceRecoveryRatioMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetPriceRecoveryRatioMax(o float64) {
	s.PriceRecoveryRatioMax = &o
}

// 正股距收回价，的过滤下限（闭区间），仅牛熊证支持此字段过滤。该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithPriceRecoveryRatioMin(o float64) *QotGetWarrantRequest {
	s.PriceRecoveryRatioMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetPriceRecoveryRatioMin(o float64) {
	s.PriceRecoveryRatioMin = &o
}

// Qot_Common.PriceType，价内/价外（暂不支持界内证的界内外筛选）
func (s *QotGetWarrantRequest) WithPriceType(o PriceType) *QotGetWarrantRequest {
	s.PriceType = o.Enum()
	return s
}

func (s *QotGetWarrantRequest) SetPriceType(o PriceType) {
	s.PriceType = o.Enum()
}

// 收回价的过滤上限（闭区间），仅牛熊证支持此字段过滤，不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithRecoveryPriceMax(o float64) *QotGetWarrantRequest {
	s.RecoveryPriceMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetRecoveryPriceMax(o float64) {
	s.RecoveryPriceMax = &o
}

// 收回价的过滤下限（闭区间），仅牛熊证支持此字段过滤，不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithRecoveryPriceMin(o float64) *QotGetWarrantRequest {
	s.RecoveryPriceMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetRecoveryPriceMin(o float64) {
	s.RecoveryPriceMin = &o
}

// Qot_Common.SortField，根据哪个字段排序
func (s *QotGetWarrantRequest) WithSortField(o SortField) *QotGetWarrantRequest {
	s.SortField = o.Enum()
	return s
}

func (s *QotGetWarrantRequest) SetSortField(o SortField) {
	s.SortField = o.Enum()
}

// Qot_Common.WarrantStatus，窝轮状态
func (s *QotGetWarrantRequest) WithStatus(o WarrantStatus) *QotGetWarrantRequest {
	s.Status = o.Enum()
	return s
}

func (s *QotGetWarrantRequest) SetStatus(o WarrantStatus) {
	s.Status = o.Enum()
}

// 街货占比的过滤上限（闭区间），该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithStreetMax(o float64) *QotGetWarrantRequest {
	s.StreetMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetStreetMax(o float64) {
	s.StreetMax = &o
}

// 街货占比的过滤下限（闭区间），该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithStreetMin(o float64) *QotGetWarrantRequest {
	s.StreetMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetStreetMin(o float64) {
	s.StreetMin = &o
}

// 行使价的过滤上限（闭区间），不传代表上限为 +∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithStrikePriceMax(o float64) *QotGetWarrantRequest {
	s.StrikePriceMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetStrikePriceMax(o float64) {
	s.StrikePriceMax = &o
}

// 行使价的过滤下限（闭区间），不传代表下限为 -∞（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotGetWarrantRequest) WithStrikePriceMin(o float64) *QotGetWarrantRequest {
	s.StrikePriceMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetStrikePriceMin(o float64) {
	s.StrikePriceMin = &o
}

// Qot_Common.WarrantType，窝轮类型过滤列表
func (s *QotGetWarrantRequest) WithTypeList(o ...WarrantType) *QotGetWarrantRequest {
	s.TypeList = o
	return s
}

func (s *QotGetWarrantRequest) SetTypeList(o ...WarrantType) {
	s.TypeList = o
}

// 成交量的过滤上限（闭区间），不传代表上限为 +∞
func (s *QotGetWarrantRequest) WithVolMax(o uint64) *QotGetWarrantRequest {
	s.VolMax = &o
	return s
}

func (s *QotGetWarrantRequest) SetVolMax(o uint64) {
	s.VolMax = &o
}

// 成交量的过滤下限（闭区间），不传代表下限为 -∞
func (s *QotGetWarrantRequest) WithVolMin(o uint64) *QotGetWarrantRequest {
	s.VolMin = &o
	return s
}

func (s *QotGetWarrantRequest) SetVolMin(o uint64) {
	s.VolMin = &o
}

// QotModifyUserSecurityRequest

// 分组名,有同名的返回排序的首个
func (s *QotModifyUserSecurityRequest) WithGroupName(o string) *QotModifyUserSecurityRequest {
	s.GroupName = &o
	return s
}

func (s *QotModifyUserSecurityRequest) SetGroupName(o string) {
	s.GroupName = &o
}

// ModifyUserSecurityOp,操作类型
func (s *QotModifyUserSecurityRequest) WithOp(o ModifyUserSecurityOp) *QotModifyUserSecurityRequest {
	s.Op = o.Enum()
	return s
}

func (s *QotModifyUserSecurityRequest) SetOp(o ModifyUserSecurityOp) {
	s.Op = o.Enum()
}

// 新增、删除或移出该分组下的股票
func (s *QotModifyUserSecurityRequest) WithSecurityList(o ...*Security) *QotModifyUserSecurityRequest {
	s.SecurityList = o
	return s
}

func (s *QotModifyUserSecurityRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// QotRegQotPushRequest

// 注册后如果本地已有数据是否首推一次已存在数据,该参数不指定则默认true
func (s *QotRegQotPushRequest) WithIsFirstPush(o bool) *QotRegQotPushRequest {
	s.IsFirstPush = &o
	return s
}

func (s *QotRegQotPushRequest) SetIsFirstPush(o bool) {
	s.IsFirstPush = &o
}

// 注册或取消
func (s *QotRegQotPushRequest) WithIsRegOrUnReg(o bool) *QotRegQotPushRequest {
	s.IsRegOrUnReg = &o
	return s
}

func (s *QotRegQotPushRequest) SetIsRegOrUnReg(o bool) {
	s.IsRegOrUnReg = &o
}

// Qot_Common.RehabType,复权类型,注册K线类型才生效,其他订阅类型忽略该参数,注册K线时该参数不指定默认前复权
func (s *QotRegQotPushRequest) WithRehabTypeList(o ...RehabType) *QotRegQotPushRequest {
	s.RehabTypeList = o
	return s
}

func (s *QotRegQotPushRequest) SetRehabTypeList(o ...RehabType) {
	s.RehabTypeList = o
}

// 股票
func (s *QotRegQotPushRequest) WithSecurityList(o ...*Security) *QotRegQotPushRequest {
	s.SecurityList = o
	return s
}

func (s *QotRegQotPushRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// Qot_Common.SubType,要注册到该连接的订阅类型
func (s *QotRegQotPushRequest) WithSubTypeList(o ...SubType) *QotRegQotPushRequest {
	s.SubTypeList = o
	return s
}

func (s *QotRegQotPushRequest) SetSubTypeList(o ...SubType) {
	s.SubTypeList = o
}

// QotRequestHistoryKLQuotaRequest

// 是否返回详细拉取过的历史纪录
func (s *QotRequestHistoryKLQuotaRequest) WithBGetDetail(o bool) *QotRequestHistoryKLQuotaRequest {
	s.BGetDetail = &o
	return s
}

func (s *QotRequestHistoryKLQuotaRequest) SetBGetDetail(o bool) {
	s.BGetDetail = &o
}

// QotRequestHistoryKLRequest

// 开始时间字符串
func (s *QotRequestHistoryKLRequest) WithBeginTime(o string) *QotRequestHistoryKLRequest {
	s.BeginTime = &o
	return s
}

func (s *QotRequestHistoryKLRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间字符串
func (s *QotRequestHistoryKLRequest) WithEndTime(o string) *QotRequestHistoryKLRequest {
	s.EndTime = &o
	return s
}

func (s *QotRequestHistoryKLRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// 是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
func (s *QotRequestHistoryKLRequest) WithExtendedTime(o bool) *QotRequestHistoryKLRequest {
	s.ExtendedTime = &o
	return s
}

func (s *QotRequestHistoryKLRequest) SetExtendedTime(o bool) {
	s.ExtendedTime = &o
}

// Qot_Common.KLType,K线类型
func (s *QotRequestHistoryKLRequest) WithKlType(o KLType) *QotRequestHistoryKLRequest {
	s.KlType = o.Enum()
	return s
}

func (s *QotRequestHistoryKLRequest) SetKlType(o KLType) {
	s.KlType = o.Enum()
}

// 最多返回多少根K线，如果未指定表示不限制
func (s *QotRequestHistoryKLRequest) WithMaxAckKLNum(o int32) *QotRequestHistoryKLRequest {
	s.MaxAckKLNum = &o
	return s
}

func (s *QotRequestHistoryKLRequest) SetMaxAckKLNum(o int32) {
	s.MaxAckKLNum = &o
}

// 指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
func (s *QotRequestHistoryKLRequest) WithNeedKLFieldsFlag(o int64) *QotRequestHistoryKLRequest {
	s.NeedKLFieldsFlag = &o
	return s
}

func (s *QotRequestHistoryKLRequest) SetNeedKLFieldsFlag(o int64) {
	s.NeedKLFieldsFlag = &o
}

// 分页请求key
func (s *QotRequestHistoryKLRequest) WithNextReqKey(o []byte) *QotRequestHistoryKLRequest {
	s.NextReqKey = o
	return s
}

func (s *QotRequestHistoryKLRequest) SetNextReqKey(o []byte) {
	s.NextReqKey = o
}

// Qot_Common.RehabType,复权类型
func (s *QotRequestHistoryKLRequest) WithRehabType(o RehabType) *QotRequestHistoryKLRequest {
	s.RehabType = o.Enum()
	return s
}

func (s *QotRequestHistoryKLRequest) SetRehabType(o RehabType) {
	s.RehabType = o.Enum()
}

// 股票市场以及股票代码
func (s *QotRequestHistoryKLRequest) WithSecurity(o *Security) *QotRequestHistoryKLRequest {
	s.Security = o
	return s
}

func (s *QotRequestHistoryKLRequest) SetSecurity(o *Security) {
	s.Security = o
}

// Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
func (s *QotRequestHistoryKLRequest) WithSession(o Session) *QotRequestHistoryKLRequest {
	s.Session = o.Enum()
	return s
}

func (s *QotRequestHistoryKLRequest) SetSession(o Session) {
	s.Session = o.Enum()
}

// QotRequestRehabRequest

// 股票
func (s *QotRequestRehabRequest) WithSecurity(o *Security) *QotRequestRehabRequest {
	s.Security = o
	return s
}

func (s *QotRequestRehabRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotRequestTradeDateRequest

// 开始时间字符串
func (s *QotRequestTradeDateRequest) WithBeginTime(o string) *QotRequestTradeDateRequest {
	s.BeginTime = &o
	return s
}

func (s *QotRequestTradeDateRequest) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间字符串
func (s *QotRequestTradeDateRequest) WithEndTime(o string) *QotRequestTradeDateRequest {
	s.EndTime = &o
	return s
}

func (s *QotRequestTradeDateRequest) SetEndTime(o string) {
	s.EndTime = &o
}

// Qot_Common.TradeDateMarket,要查询的市场
func (s *QotRequestTradeDateRequest) WithMarket(o TradeDateMarket) *QotRequestTradeDateRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotRequestTradeDateRequest) SetMarket(o TradeDateMarket) {
	s.Market = o.Enum()
}

// 指定标的
func (s *QotRequestTradeDateRequest) WithSecurity(o *Security) *QotRequestTradeDateRequest {
	s.Security = o
	return s
}

func (s *QotRequestTradeDateRequest) SetSecurity(o *Security) {
	s.Security = o
}

// QotSetPriceReminderRequest

// Qot_Common::PriceReminderFreq，提醒频率类型，删除、启用、禁用的情况下会忽略该字段
func (s *QotSetPriceReminderRequest) WithFreq(o PriceReminderFreq) *QotSetPriceReminderRequest {
	s.Freq = o.Enum()
	return s
}

func (s *QotSetPriceReminderRequest) SetFreq(o PriceReminderFreq) {
	s.Freq = o.Enum()
}

// 到价提醒的标识，GetPriceReminder协议可获得，用于指定要操作的到价提醒项，对于新增的情况不需要填
func (s *QotSetPriceReminderRequest) WithKey(o int64) *QotSetPriceReminderRequest {
	s.Key = &o
	return s
}

func (s *QotSetPriceReminderRequest) SetKey(o int64) {
	s.Key = &o
}

// 用户设置到价提醒时的标注，仅支持 20 个以内的中文字符，删除、启用、禁用的情况下会忽略该字段
func (s *QotSetPriceReminderRequest) WithNote(o string) *QotSetPriceReminderRequest {
	s.Note = &o
	return s
}

func (s *QotSetPriceReminderRequest) SetNote(o string) {
	s.Note = &o
}

// SetPriceReminderOp，操作类型
func (s *QotSetPriceReminderRequest) WithOp(o SetPriceReminderOp) *QotSetPriceReminderRequest {
	s.Op = o.Enum()
	return s
}

func (s *QotSetPriceReminderRequest) SetOp(o SetPriceReminderOp) {
	s.Op = o.Enum()
}

// 到价提醒的时段列表，删除、启用、禁用的情况下会忽略该入参,枚举参考Qot_Common::PriceReminderMarketStatus
func (s *QotSetPriceReminderRequest) WithReminderSessionList(o ...PriceReminderMarketStatus) *QotSetPriceReminderRequest {
	s.ReminderSessionList = o
	return s
}

func (s *QotSetPriceReminderRequest) SetReminderSessionList(o ...PriceReminderMarketStatus) {
	s.ReminderSessionList = o
}

// 股票
func (s *QotSetPriceReminderRequest) WithSecurity(o *Security) *QotSetPriceReminderRequest {
	s.Security = o
	return s
}

func (s *QotSetPriceReminderRequest) SetSecurity(o *Security) {
	s.Security = o
}

// Qot_Common::PriceReminderType，提醒类型，删除、启用、禁用的情况下会忽略该字段
func (s *QotSetPriceReminderRequest) WithType(o PriceReminderType) *QotSetPriceReminderRequest {
	s.Type = o.Enum()
	return s
}

func (s *QotSetPriceReminderRequest) SetType(o PriceReminderType) {
	s.Type = o.Enum()
}

// 提醒值，删除、启用、禁用的情况下会忽略该字段（精确到小数点后 3 位，超出部分会被舍弃）
func (s *QotSetPriceReminderRequest) WithValue(o float64) *QotSetPriceReminderRequest {
	s.Value = &o
	return s
}

func (s *QotSetPriceReminderRequest) SetValue(o float64) {
	s.Value = &o
}

// QotStockFilterRequest

// 累积指标过滤器
func (s *QotStockFilterRequest) WithAccumulateFilterList(o ...*AccumulateFilter) *QotStockFilterRequest {
	s.AccumulateFilterList = o
	return s
}

func (s *QotStockFilterRequest) SetAccumulateFilterList(o ...*AccumulateFilter) {
	s.AccumulateFilterList = o
}

// 简单指标过滤器
func (s *QotStockFilterRequest) WithBaseFilterList(o ...*BaseFilter) *QotStockFilterRequest {
	s.BaseFilterList = o
	return s
}

func (s *QotStockFilterRequest) SetBaseFilterList(o ...*BaseFilter) {
	s.BaseFilterList = o
}

// 数据起始点
func (s *QotStockFilterRequest) WithBegin(o int32) *QotStockFilterRequest {
	s.Begin = &o
	return s
}

func (s *QotStockFilterRequest) SetBegin(o int32) {
	s.Begin = &o
}

// 自定义技术指标过滤器
func (s *QotStockFilterRequest) WithCustomIndicatorFilterList(o ...*CustomIndicatorFilter) *QotStockFilterRequest {
	s.CustomIndicatorFilterList = o
	return s
}

func (s *QotStockFilterRequest) SetCustomIndicatorFilterList(o ...*CustomIndicatorFilter) {
	s.CustomIndicatorFilterList = o
}

// 财务指标过滤器
func (s *QotStockFilterRequest) WithFinancialFilterList(o ...*FinancialFilter) *QotStockFilterRequest {
	s.FinancialFilterList = o
	return s
}

func (s *QotStockFilterRequest) SetFinancialFilterList(o ...*FinancialFilter) {
	s.FinancialFilterList = o
}

// Qot_Common::QotMarket股票市场，支持沪股和深股，且沪股和深股不做区分都代表A股市场。
func (s *QotStockFilterRequest) WithMarket(o QotMarket) *QotStockFilterRequest {
	s.Market = o.Enum()
	return s
}

func (s *QotStockFilterRequest) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// 请求数据个数，最大200
func (s *QotStockFilterRequest) WithNum(o int32) *QotStockFilterRequest {
	s.Num = &o
	return s
}

func (s *QotStockFilterRequest) SetNum(o int32) {
	s.Num = &o
}

// 形态技术指标过滤器
func (s *QotStockFilterRequest) WithPatternFilterList(o ...*PatternFilter) *QotStockFilterRequest {
	s.PatternFilterList = o
	return s
}

func (s *QotStockFilterRequest) SetPatternFilterList(o ...*PatternFilter) {
	s.PatternFilterList = o
}

// 板块
func (s *QotStockFilterRequest) WithPlate(o *Security) *QotStockFilterRequest {
	s.Plate = o
	return s
}

func (s *QotStockFilterRequest) SetPlate(o *Security) {
	s.Plate = o
}

// QotSubRequest

// 是否允许美股盘前盘后数据（仅用于订阅美股的实时K线、实时分时、实时逐笔）
func (s *QotSubRequest) WithExtendedTime(o bool) *QotSubRequest {
	s.ExtendedTime = &o
	return s
}

func (s *QotSubRequest) SetExtendedTime(o bool) {
	s.ExtendedTime = &o
}

// 注册后如果本地已有数据是否首推一次已存在数据,该参数不指定则默认true
func (s *QotSubRequest) WithIsFirstPush(o bool) *QotSubRequest {
	s.IsFirstPush = &o
	return s
}

func (s *QotSubRequest) SetIsFirstPush(o bool) {
	s.IsFirstPush = &o
}

// 是否注册或反注册该连接上面行情的推送,该参数不指定不做注册反注册操作
func (s *QotSubRequest) WithIsRegOrUnRegPush(o bool) *QotSubRequest {
	s.IsRegOrUnRegPush = &o
	return s
}

func (s *QotSubRequest) SetIsRegOrUnRegPush(o bool) {
	s.IsRegOrUnRegPush = &o
}

// ture表示订阅,false表示反订阅
func (s *QotSubRequest) WithIsSubOrUnSub(o bool) *QotSubRequest {
	s.IsSubOrUnSub = &o
	return s
}

func (s *QotSubRequest) SetIsSubOrUnSub(o bool) {
	s.IsSubOrUnSub = &o
}

// 订阅摆盘可用,是否订阅摆盘明细,仅支持SF行情,该参数不指定则默认false
func (s *QotSubRequest) WithIsSubOrderBookDetail(o bool) *QotSubRequest {
	s.IsSubOrderBookDetail = &o
	return s
}

func (s *QotSubRequest) SetIsSubOrderBookDetail(o bool) {
	s.IsSubOrderBookDetail = &o
}

// 当被设置为True时忽略其他参数，取消当前连接的所有订阅，并且反注册推送。
func (s *QotSubRequest) WithIsUnsubAll(o bool) *QotSubRequest {
	s.IsUnsubAll = &o
	return s
}

func (s *QotSubRequest) SetIsUnsubAll(o bool) {
	s.IsUnsubAll = &o
}

// Qot_Common.RehabType,复权类型,注册推送并且是K线类型才生效,其他订阅类型忽略该参数,注册K线推送时该参数不指定默认前复权
func (s *QotSubRequest) WithRegPushRehabTypeList(o ...RehabType) *QotSubRequest {
	s.RegPushRehabTypeList = o
	return s
}

func (s *QotSubRequest) SetRegPushRehabTypeList(o ...RehabType) {
	s.RegPushRehabTypeList = o
}

// 股票
func (s *QotSubRequest) WithSecurityList(o ...*Security) *QotSubRequest {
	s.SecurityList = o
	return s
}

func (s *QotSubRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// 时段 Session
func (s *QotSubRequest) WithSession(o Session) *QotSubRequest {
	s.Session = o.Enum()
	return s
}

func (s *QotSubRequest) SetSession(o Session) {
	s.Session = o.Enum()
}

// Qot_Common.SubType,订阅数据类型
func (s *QotSubRequest) WithSubTypeList(o ...SubType) *QotSubRequest {
	s.SubTypeList = o
	return s
}

func (s *QotSubRequest) SetSubTypeList(o ...SubType) {
	s.SubTypeList = o
}

// Security
//两个字段确定一支股票

// 股票代码
func (s *Security) WithCode(o string) *Security {
	s.Code = &o
	return s
}

func (s *Security) SetCode(o string) {
	s.Code = &o
}

// QotMarket,股票市场
func (s *Security) WithMarket(o QotMarket) *Security {
	s.Market = o.Enum()
	return s
}

func (s *Security) SetMarket(o QotMarket) {
	s.Market = o.Enum()
}

// TestCmdRequest
//内部使用

func (s *TestCmdRequest) WithCmd(o string) *TestCmdRequest {
	s.Cmd = &o
	return s
}

func (s *TestCmdRequest) SetCmd(o string) {
	s.Cmd = &o
}

func (s *TestCmdRequest) WithParams(o string) *TestCmdRequest {
	s.Params = &o
	return s
}

func (s *TestCmdRequest) SetParams(o string) {
	s.Params = &o
}

// TimeFilter

// 开始时间点
func (s *TimeFilter) WithBeginTime(o string) *TimeFilter {
	s.BeginTime = &o
	return s
}

func (s *TimeFilter) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 结束时间点
func (s *TimeFilter) WithEndTime(o string) *TimeFilter {
	s.EndTime = &o
	return s
}

func (s *TimeFilter) SetEndTime(o string) {
	s.EndTime = &o
}

// TimeFilterType, 过滤类型
func (s *TimeFilter) WithType(o TimeFilterType) *TimeFilter {
	s.Type = o.Enum()
	return s
}

func (s *TimeFilter) SetType(o TimeFilterType) {
	s.Type = o.Enum()
}

// TrdFilterConditions
//过滤条件，条件组合是"与"不是"或"，用于获取订单、成交、持仓等时二次过滤

// 开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
func (s *TrdFilterConditions) WithBeginTime(o string) *TrdFilterConditions {
	s.BeginTime = &o
	return s
}

func (s *TrdFilterConditions) SetBeginTime(o string) {
	s.BeginTime = &o
}

// 代码过滤，只返回包含这些代码的数据，没传不过滤
func (s *TrdFilterConditions) WithCodeList(o ...string) *TrdFilterConditions {
	s.CodeList = o
	return s
}

func (s *TrdFilterConditions) SetCodeList(o ...string) {
	s.CodeList = o
}

// 结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
func (s *TrdFilterConditions) WithEndTime(o string) *TrdFilterConditions {
	s.EndTime = &o
	return s
}

func (s *TrdFilterConditions) SetEndTime(o string) {
	s.EndTime = &o
}

// 指定交易市场, 参见TrdMarket的枚举定义
func (s *TrdFilterConditions) WithFilterMarket(o TrdMarket) *TrdFilterConditions {
	s.FilterMarket = o.Enum()
	return s
}

func (s *TrdFilterConditions) SetFilterMarket(o TrdMarket) {
	s.FilterMarket = o.Enum()
}

// ID主键过滤，只返回包含这些ID的数据，没传不过滤，订单是orderID、成交是fillID、持仓是positionID
func (s *TrdFilterConditions) WithIdList(o ...uint64) *TrdFilterConditions {
	s.IdList = o
	return s
}

func (s *TrdFilterConditions) SetIdList(o ...uint64) {
	s.IdList = o
}

// 服务器订单ID，可以用来替代orderID，二选一
func (s *TrdFilterConditions) WithOrderIDExList(o ...string) *TrdFilterConditions {
	s.OrderIDExList = o
	return s
}

func (s *TrdFilterConditions) SetOrderIDExList(o ...string) {
	s.OrderIDExList = o
}

// TrdFlowSummaryRequest

// 现金流方向 TrdCashFlowDirection
func (s *TrdFlowSummaryRequest) WithCashFlowDirection(o TrdCashFlowDirection) *TrdFlowSummaryRequest {
	s.CashFlowDirection = o.Enum()
	return s
}

func (s *TrdFlowSummaryRequest) SetCashFlowDirection(o TrdCashFlowDirection) {
	s.CashFlowDirection = o.Enum()
}

// 清算日期，格式 "2017-05-20"
func (s *TrdFlowSummaryRequest) WithClearingDate(o string) *TrdFlowSummaryRequest {
	s.ClearingDate = &o
	return s
}

func (s *TrdFlowSummaryRequest) SetClearingDate(o string) {
	s.ClearingDate = &o
}

// 交易公共参数头
func (s *TrdFlowSummaryRequest) WithHeader(o *TrdHeader) *TrdFlowSummaryRequest {
	s.Header = o
	return s
}

func (s *TrdFlowSummaryRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// TrdGetAccListRequest

// 是否返回综合账户 （适用于 HK/US/SG/AU 综合账户体系）
func (s *TrdGetAccListRequest) WithNeedGeneralSecAccount(o bool) *TrdGetAccListRequest {
	s.NeedGeneralSecAccount = &o
	return s
}

func (s *TrdGetAccListRequest) SetNeedGeneralSecAccount(o bool) {
	s.NeedGeneralSecAccount = &o
}

// 交易品类，参考 TrdCategory
func (s *TrdGetAccListRequest) WithCategory(o TrdCategory) *TrdGetAccListRequest {
	s.TrdCategory = o.Enum()
	return s
}

func (s *TrdGetAccListRequest) SetCategory(o TrdCategory) {
	s.TrdCategory = o.Enum()
}

// 历史原因，目前已废弃，填0即可
func (s *TrdGetAccListRequest) WithUserID(o uint64) *TrdGetAccListRequest {
	s.UserID = &o
	return s
}

func (s *TrdGetAccListRequest) SetUserID(o uint64) {
	s.UserID = &o
}

// TrdGetFundsRequest

// 货币种类，参见Trd_Common.Currency。期货账户必填，其它账户忽略
func (s *TrdGetFundsRequest) WithCurrency(o Currency) *TrdGetFundsRequest {
	s.Currency = o.Enum()
	return s
}

func (s *TrdGetFundsRequest) SetCurrency(o Currency) {
	s.Currency = o.Enum()
}

// 交易公共参数头
func (s *TrdGetFundsRequest) WithHeader(o *TrdHeader) *TrdGetFundsRequest {
	s.Header = o
	return s
}

func (s *TrdGetFundsRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
func (s *TrdGetFundsRequest) WithRefreshCache(o bool) *TrdGetFundsRequest {
	s.RefreshCache = &o
	return s
}

func (s *TrdGetFundsRequest) SetRefreshCache(o bool) {
	s.RefreshCache = &o
}

// TrdGetHistoryOrderFillListRequest

// 过滤条件
func (s *TrdGetHistoryOrderFillListRequest) WithFilterConditions(o *TrdFilterConditions) *TrdGetHistoryOrderFillListRequest {
	s.FilterConditions = o
	return s
}

func (s *TrdGetHistoryOrderFillListRequest) SetFilterConditions(o *TrdFilterConditions) {
	s.FilterConditions = o
}

// 交易公共参数头
func (s *TrdGetHistoryOrderFillListRequest) WithHeader(o *TrdHeader) *TrdGetHistoryOrderFillListRequest {
	s.Header = o
	return s
}

func (s *TrdGetHistoryOrderFillListRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// TrdGetHistoryOrderListRequest

// 过滤条件
func (s *TrdGetHistoryOrderListRequest) WithFilterConditions(o *TrdFilterConditions) *TrdGetHistoryOrderListRequest {
	s.FilterConditions = o
	return s
}

func (s *TrdGetHistoryOrderListRequest) SetFilterConditions(o *TrdFilterConditions) {
	s.FilterConditions = o
}

// 需要过滤的订单状态列表
func (s *TrdGetHistoryOrderListRequest) WithFilterStatusList(o ...OrderStatus) *TrdGetHistoryOrderListRequest {
	s.FilterStatusList = o
	return s
}

func (s *TrdGetHistoryOrderListRequest) SetFilterStatusList(o ...OrderStatus) {
	s.FilterStatusList = o
}

// 交易公共参数头
func (s *TrdGetHistoryOrderListRequest) WithHeader(o *TrdHeader) *TrdGetHistoryOrderListRequest {
	s.Header = o
	return s
}

func (s *TrdGetHistoryOrderListRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// TrdGetMarginRatioRequest

// 交易公共参数头
func (s *TrdGetMarginRatioRequest) WithHeader(o *TrdHeader) *TrdGetMarginRatioRequest {
	s.Header = o
	return s
}

func (s *TrdGetMarginRatioRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 股票
func (s *TrdGetMarginRatioRequest) WithSecurityList(o ...*Security) *TrdGetMarginRatioRequest {
	s.SecurityList = o
	return s
}

func (s *TrdGetMarginRatioRequest) SetSecurityList(o ...*Security) {
	s.SecurityList = o
}

// TrdGetMaxTrdQtysRequest

// 是否调整价格，如果价格不合法，是否调整到合法价位，true调整，false不调整
func (s *TrdGetMaxTrdQtysRequest) WithAdjustPrice(o bool) *TrdGetMaxTrdQtysRequest {
	s.AdjustPrice = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetAdjustPrice(o bool) {
	s.AdjustPrice = &o
}

// 调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
func (s *TrdGetMaxTrdQtysRequest) WithAdjustSideAndLimit(o float64) *TrdGetMaxTrdQtysRequest {
	s.AdjustSideAndLimit = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetAdjustSideAndLimit(o float64) {
	s.AdjustSideAndLimit = &o
}

// 代码，港股必须是5位数字，A股必须是6位数字，美股没限制
func (s *TrdGetMaxTrdQtysRequest) WithCode(o string) *TrdGetMaxTrdQtysRequest {
	s.Code = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetCode(o string) {
	s.Code = &o
}

// 交易公共参数头
func (s *TrdGetMaxTrdQtysRequest) WithHeader(o *TrdHeader) *TrdGetMaxTrdQtysRequest {
	s.Header = o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 订单号，新下订单不需要，如果是修改订单就需要把原订单号带上才行，因为改单的最大买卖数量会包含原订单数量。
func (s *TrdGetMaxTrdQtysRequest) WithOrderID(o uint64) *TrdGetMaxTrdQtysRequest {
	s.OrderID = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetOrderID(o uint64) {
	s.OrderID = &o
}

// 表示服务器订单id，可以用来代替orderID，和orderID二选一
func (s *TrdGetMaxTrdQtysRequest) WithOrderIDEx(o string) *TrdGetMaxTrdQtysRequest {
	s.OrderIDEx = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetOrderIDEx(o string) {
	s.OrderIDEx = &o
}

// 订单类型, 参见Trd_Common.OrderType的枚举定义
func (s *TrdGetMaxTrdQtysRequest) WithOrderType(o OrderType) *TrdGetMaxTrdQtysRequest {
	s.OrderType = o.Enum()
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetOrderType(o OrderType) {
	s.OrderType = o.Enum()
}

// 价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）。如果是竞价、市价单，请也填入一个当前价格，服务器才好计算
func (s *TrdGetMaxTrdQtysRequest) WithPrice(o float64) *TrdGetMaxTrdQtysRequest {
	s.Price = &o
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetPrice(o float64) {
	s.Price = &o
}

// 证券所属市场，参见TrdSecMarket的枚举定义
func (s *TrdGetMaxTrdQtysRequest) WithSecMarket(o TrdSecMarket) *TrdGetMaxTrdQtysRequest {
	s.SecMarket = o.Enum()
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetSecMarket(o TrdSecMarket) {
	s.SecMarket = o.Enum()
}

// 美股订单时段, 参见Common.Session的枚举定义
func (s *TrdGetMaxTrdQtysRequest) WithSession(o Session) *TrdGetMaxTrdQtysRequest {
	s.Session = o.Enum()
	return s
}

func (s *TrdGetMaxTrdQtysRequest) SetSession(o Session) {
	s.Session = o.Enum()
}

// TrdGetOrderFeeRequest

// 交易公共参数头
func (s *TrdGetOrderFeeRequest) WithHeader(o *TrdHeader) *TrdGetOrderFeeRequest {
	s.Header = o
	return s
}

func (s *TrdGetOrderFeeRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 服务器订单ID
func (s *TrdGetOrderFeeRequest) WithOrderIdExList(o ...string) *TrdGetOrderFeeRequest {
	s.OrderIdExList = o
	return s
}

func (s *TrdGetOrderFeeRequest) SetOrderIdExList(o ...string) {
	s.OrderIdExList = o
}

// TrdGetOrderFillListRequest

// 过滤条件
func (s *TrdGetOrderFillListRequest) WithFilterConditions(o *TrdFilterConditions) *TrdGetOrderFillListRequest {
	s.FilterConditions = o
	return s
}

func (s *TrdGetOrderFillListRequest) SetFilterConditions(o *TrdFilterConditions) {
	s.FilterConditions = o
}

// 交易公共参数头
func (s *TrdGetOrderFillListRequest) WithHeader(o *TrdHeader) *TrdGetOrderFillListRequest {
	s.Header = o
	return s
}

func (s *TrdGetOrderFillListRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
func (s *TrdGetOrderFillListRequest) WithRefreshCache(o bool) *TrdGetOrderFillListRequest {
	s.RefreshCache = &o
	return s
}

func (s *TrdGetOrderFillListRequest) SetRefreshCache(o bool) {
	s.RefreshCache = &o
}

// TrdGetOrderListRequest

// 过滤条件
func (s *TrdGetOrderListRequest) WithFilterConditions(o *TrdFilterConditions) *TrdGetOrderListRequest {
	s.FilterConditions = o
	return s
}

func (s *TrdGetOrderListRequest) SetFilterConditions(o *TrdFilterConditions) {
	s.FilterConditions = o
}

// 需要过滤的订单状态列表
func (s *TrdGetOrderListRequest) WithFilterStatusList(o ...OrderStatus) *TrdGetOrderListRequest {
	s.FilterStatusList = o
	return s
}

func (s *TrdGetOrderListRequest) SetFilterStatusList(o ...OrderStatus) {
	s.FilterStatusList = o
}

// 交易公共参数头
func (s *TrdGetOrderListRequest) WithHeader(o *TrdHeader) *TrdGetOrderListRequest {
	s.Header = o
	return s
}

func (s *TrdGetOrderListRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
func (s *TrdGetOrderListRequest) WithRefreshCache(o bool) *TrdGetOrderListRequest {
	s.RefreshCache = &o
	return s
}

func (s *TrdGetOrderListRequest) SetRefreshCache(o bool) {
	s.RefreshCache = &o
}

// TrdGetPositionListRequest

// 过滤条件
func (s *TrdGetPositionListRequest) WithFilterConditions(o *TrdFilterConditions) *TrdGetPositionListRequest {
	s.FilterConditions = o
	return s
}

func (s *TrdGetPositionListRequest) SetFilterConditions(o *TrdFilterConditions) {
	s.FilterConditions = o
}

// 过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
func (s *TrdGetPositionListRequest) WithFilterPLRatioMax(o float64) *TrdGetPositionListRequest {
	s.FilterPLRatioMax = &o
	return s
}

func (s *TrdGetPositionListRequest) SetFilterPLRatioMax(o float64) {
	s.FilterPLRatioMax = &o
}

// 过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
func (s *TrdGetPositionListRequest) WithFilterPLRatioMin(o float64) *TrdGetPositionListRequest {
	s.FilterPLRatioMin = &o
	return s
}

func (s *TrdGetPositionListRequest) SetFilterPLRatioMin(o float64) {
	s.FilterPLRatioMin = &o
}

// 交易公共参数头
func (s *TrdGetPositionListRequest) WithHeader(o *TrdHeader) *TrdGetPositionListRequest {
	s.Header = o
	return s
}

func (s *TrdGetPositionListRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
func (s *TrdGetPositionListRequest) WithRefreshCache(o bool) *TrdGetPositionListRequest {
	s.RefreshCache = &o
	return s
}

func (s *TrdGetPositionListRequest) SetRefreshCache(o bool) {
	s.RefreshCache = &o
}

// TrdHeader
//交易协议公共参数头

// 业务账号, 业务账号与交易环境、市场权限需要匹配，否则会返回错误
func (s *TrdHeader) WithAccID(o uint64) *TrdHeader {
	s.AccID = &o
	return s
}

func (s *TrdHeader) SetAccID(o uint64) {
	s.AccID = &o
}

// 交易环境, 参见TrdEnv的枚举定义
func (s *TrdHeader) WithEnv(o TrdEnv) *TrdHeader {
	s.TrdEnv = o.Enum()
	return s
}

func (s *TrdHeader) SetEnv(o TrdEnv) {
	s.TrdEnv = o.Enum()
}

// 交易市场, 参见TrdMarket的枚举定义
func (s *TrdHeader) WithMarket(o TrdMarket) *TrdHeader {
	s.TrdMarket = o.Enum()
	return s
}

func (s *TrdHeader) SetMarket(o TrdMarket) {
	s.TrdMarket = o.Enum()
}

// TrdModifyOrderRequest

// 是否调整价格，如果价格不合法，是否调整到合法价位，true调整，false不调整
func (s *TrdModifyOrderRequest) WithAdjustPrice(o bool) *TrdModifyOrderRequest {
	s.AdjustPrice = &o
	return s
}

func (s *TrdModifyOrderRequest) SetAdjustPrice(o bool) {
	s.AdjustPrice = &o
}

// 调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
func (s *TrdModifyOrderRequest) WithAdjustSideAndLimit(o float64) *TrdModifyOrderRequest {
	s.AdjustSideAndLimit = &o
	return s
}

func (s *TrdModifyOrderRequest) SetAdjustSideAndLimit(o float64) {
	s.AdjustSideAndLimit = &o
}

// 触发价格
func (s *TrdModifyOrderRequest) WithAuxPrice(o float64) *TrdModifyOrderRequest {
	s.AuxPrice = &o
	return s
}

func (s *TrdModifyOrderRequest) SetAuxPrice(o float64) {
	s.AuxPrice = &o
}

// 是否对此业务账户的全部订单操作，true是，false否(对单个订单)，无此字段代表false，仅对单个订单
func (s *TrdModifyOrderRequest) WithForAll(o bool) *TrdModifyOrderRequest {
	s.ForAll = &o
	return s
}

func (s *TrdModifyOrderRequest) SetForAll(o bool) {
	s.ForAll = &o
}

// 交易公共参数头
func (s *TrdModifyOrderRequest) WithHeader(o *TrdHeader) *TrdModifyOrderRequest {
	s.Header = o
	return s
}

func (s *TrdModifyOrderRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 修改操作类型，参见Trd_Common.ModifyOrderOp的枚举定义
func (s *TrdModifyOrderRequest) WithModifyOrderOp(o ModifyOrderOp) *TrdModifyOrderRequest {
	s.ModifyOrderOp = o.Enum()
	return s
}

func (s *TrdModifyOrderRequest) SetModifyOrderOp(o ModifyOrderOp) {
	s.ModifyOrderOp = o.Enum()
}

// 订单号，forAll为true时，传0
func (s *TrdModifyOrderRequest) WithOrderID(o uint64) *TrdModifyOrderRequest {
	s.OrderID = &o
	return s
}

func (s *TrdModifyOrderRequest) SetOrderID(o uint64) {
	s.OrderID = &o
}

// 表示服务器订单id，可以用来代替orderID，和orderID二选一
func (s *TrdModifyOrderRequest) WithOrderIDEx(o string) *TrdModifyOrderRequest {
	s.OrderIDEx = &o
	return s
}

func (s *TrdModifyOrderRequest) SetOrderIDEx(o string) {
	s.OrderIDEx = &o
}

// 交易写操作防重放攻击
func (s *TrdModifyOrderRequest) WithPacketID(o *PacketID) *TrdModifyOrderRequest {
	s.PacketID = o
	return s
}

func (s *TrdModifyOrderRequest) SetPacketID(o *PacketID) {
	s.PacketID = o
}

// 价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）
func (s *TrdModifyOrderRequest) WithPrice(o float64) *TrdModifyOrderRequest {
	s.Price = &o
	return s
}

func (s *TrdModifyOrderRequest) SetPrice(o float64) {
	s.Price = &o
}

// 数量，期权单位是"张"（精确到小数点后 0 位，超出部分会被舍弃）
func (s *TrdModifyOrderRequest) WithQty(o float64) *TrdModifyOrderRequest {
	s.Qty = &o
	return s
}

func (s *TrdModifyOrderRequest) SetQty(o float64) {
	s.Qty = &o
}

// 指定价差
func (s *TrdModifyOrderRequest) WithTrailSpread(o float64) *TrdModifyOrderRequest {
	s.TrailSpread = &o
	return s
}

func (s *TrdModifyOrderRequest) SetTrailSpread(o float64) {
	s.TrailSpread = &o
}

// 跟踪类型, 参见Trd_Common.TrailType的枚举定义
func (s *TrdModifyOrderRequest) WithTrailType(o TrailType) *TrdModifyOrderRequest {
	s.TrailType = o.Enum()
	return s
}

func (s *TrdModifyOrderRequest) SetTrailType(o TrailType) {
	s.TrailType = o.Enum()
}

// 跟踪金额/百分比
func (s *TrdModifyOrderRequest) WithTrailValue(o float64) *TrdModifyOrderRequest {
	s.TrailValue = &o
	return s
}

func (s *TrdModifyOrderRequest) SetTrailValue(o float64) {
	s.TrailValue = &o
}

// 指定市场，全部撤单时才需要
func (s *TrdModifyOrderRequest) WithMarket(o TrdMarket) *TrdModifyOrderRequest {
	s.TrdMarket = o.Enum()
	return s
}

func (s *TrdModifyOrderRequest) SetMarket(o TrdMarket) {
	s.TrdMarket = o.Enum()
}

// TrdPlaceOrderRequest

// 是否调整价格，如果价格不合法，是否调整到合法价位，true调整，false不调整
func (s *TrdPlaceOrderRequest) WithAdjustPrice(o bool) *TrdPlaceOrderRequest {
	s.AdjustPrice = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetAdjustPrice(o bool) {
	s.AdjustPrice = &o
}

// 调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
func (s *TrdPlaceOrderRequest) WithAdjustSideAndLimit(o float64) *TrdPlaceOrderRequest {
	s.AdjustSideAndLimit = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetAdjustSideAndLimit(o float64) {
	s.AdjustSideAndLimit = &o
}

// 触发价格
func (s *TrdPlaceOrderRequest) WithAuxPrice(o float64) *TrdPlaceOrderRequest {
	s.AuxPrice = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetAuxPrice(o float64) {
	s.AuxPrice = &o
}

// 代码，港股必须是5位数字，A股必须是6位数字，美股没限制
func (s *TrdPlaceOrderRequest) WithCode(o string) *TrdPlaceOrderRequest {
	s.Code = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetCode(o string) {
	s.Code = &o
}

// 是否允许盘前盘后成交。仅适用于美股限价单。默认false
func (s *TrdPlaceOrderRequest) WithFillOutsideRTH(o bool) *TrdPlaceOrderRequest {
	s.FillOutsideRTH = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetFillOutsideRTH(o bool) {
	s.FillOutsideRTH = &o
}

// 交易公共参数头
func (s *TrdPlaceOrderRequest) WithHeader(o *TrdHeader) *TrdPlaceOrderRequest {
	s.Header = o
	return s
}

func (s *TrdPlaceOrderRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 订单类型, 参见Trd_Common.OrderType的枚举定义
func (s *TrdPlaceOrderRequest) WithOrderType(o OrderType) *TrdPlaceOrderRequest {
	s.OrderType = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetOrderType(o OrderType) {
	s.OrderType = o.Enum()
}

// 交易写操作防重放攻击
func (s *TrdPlaceOrderRequest) WithPacketID(o *PacketID) *TrdPlaceOrderRequest {
	s.PacketID = o
	return s
}

func (s *TrdPlaceOrderRequest) SetPacketID(o *PacketID) {
	s.PacketID = o
}

// 价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）
func (s *TrdPlaceOrderRequest) WithPrice(o float64) *TrdPlaceOrderRequest {
	s.Price = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetPrice(o float64) {
	s.Price = &o
}

// 数量，期权单位是"张"（精确到小数点后 0 位，超出部分会被舍弃。期权期货单位是"张"）
func (s *TrdPlaceOrderRequest) WithQty(o float64) *TrdPlaceOrderRequest {
	s.Qty = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetQty(o float64) {
	s.Qty = &o
}

// 用户备注字符串，最多只能传64字节。可用于标识订单唯一信息等，下单填上，订单结构就会带上。
func (s *TrdPlaceOrderRequest) WithRemark(o string) *TrdPlaceOrderRequest {
	s.Remark = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetRemark(o string) {
	s.Remark = &o
}

// 证券所属市场，参见TrdSecMarket的枚举定义
func (s *TrdPlaceOrderRequest) WithSecMarket(o TrdSecMarket) *TrdPlaceOrderRequest {
	s.SecMarket = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetSecMarket(o TrdSecMarket) {
	s.SecMarket = o.Enum()
}

// 美股订单时段, 参见Common.Session的枚举定义
func (s *TrdPlaceOrderRequest) WithSession(o Session) *TrdPlaceOrderRequest {
	s.Session = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetSession(o Session) {
	s.Session = o.Enum()
}

// 订单有效期限，参见TrdCommon_TimeInForce的枚举定义
func (s *TrdPlaceOrderRequest) WithTimeInForce(o TimeInForce) *TrdPlaceOrderRequest {
	s.TimeInForce = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetTimeInForce(o TimeInForce) {
	s.TimeInForce = o.Enum()
}

// 指定价差
func (s *TrdPlaceOrderRequest) WithTrailSpread(o float64) *TrdPlaceOrderRequest {
	s.TrailSpread = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetTrailSpread(o float64) {
	s.TrailSpread = &o
}

// 跟踪类型, 参见Trd_Common.TrailType的枚举定义
func (s *TrdPlaceOrderRequest) WithTrailType(o TrailType) *TrdPlaceOrderRequest {
	s.TrailType = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetTrailType(o TrailType) {
	s.TrailType = o.Enum()
}

// 跟踪金额/百分比
func (s *TrdPlaceOrderRequest) WithTrailValue(o float64) *TrdPlaceOrderRequest {
	s.TrailValue = &o
	return s
}

func (s *TrdPlaceOrderRequest) SetTrailValue(o float64) {
	s.TrailValue = &o
}

// 交易方向, 参见Trd_Common.TrdSide的枚举定义
func (s *TrdPlaceOrderRequest) WithSide(o TrdSide) *TrdPlaceOrderRequest {
	s.TrdSide = o.Enum()
	return s
}

func (s *TrdPlaceOrderRequest) SetSide(o TrdSide) {
	s.TrdSide = o.Enum()
}

// TrdReconfirmOrderRequest

// 交易公共参数头
func (s *TrdReconfirmOrderRequest) WithHeader(o *TrdHeader) *TrdReconfirmOrderRequest {
	s.Header = o
	return s
}

func (s *TrdReconfirmOrderRequest) SetHeader(o *TrdHeader) {
	s.Header = o
}

// 订单号
func (s *TrdReconfirmOrderRequest) WithOrderID(o uint64) *TrdReconfirmOrderRequest {
	s.OrderID = &o
	return s
}

func (s *TrdReconfirmOrderRequest) SetOrderID(o uint64) {
	s.OrderID = &o
}

// 交易写操作防重放攻击
func (s *TrdReconfirmOrderRequest) WithPacketID(o *PacketID) *TrdReconfirmOrderRequest {
	s.PacketID = o
	return s
}

func (s *TrdReconfirmOrderRequest) SetPacketID(o *PacketID) {
	s.PacketID = o
}

// 需要再次确认订单的原因，参见Trd_Common.ReconfirmOrderReason的枚举定义
func (s *TrdReconfirmOrderRequest) WithReconfirmReason(o int32) *TrdReconfirmOrderRequest {
	s.ReconfirmReason = &o
	return s
}

func (s *TrdReconfirmOrderRequest) SetReconfirmReason(o int32) {
	s.ReconfirmReason = &o
}

// TrdSubAccPushRequest

// 要接收推送数据的业务账号列表，全量非增量，即使用者请每次传需要接收推送数据的所有业务账号
func (s *TrdSubAccPushRequest) WithAccIDList(o ...uint64) *TrdSubAccPushRequest {
	s.AccIDList = o
	return s
}

func (s *TrdSubAccPushRequest) SetAccIDList(o ...uint64) {
	s.AccIDList = o
}

// TrdUnlockTradeRequest

// 交易密码的MD5转16进制(全小写)，解锁交易必须要填密码，锁定交易不需要验证密码，可不填
func (s *TrdUnlockTradeRequest) WithPwdMD5(o string) *TrdUnlockTradeRequest {
	s.PwdMD5 = &o
	return s
}

func (s *TrdUnlockTradeRequest) SetPwdMD5(o string) {
	s.PwdMD5 = &o
}

// 券商标识，取值见Trd_Common.SecurityFirm
func (s *TrdUnlockTradeRequest) WithSecurityFirm(o SecurityFirm) *TrdUnlockTradeRequest {
	s.SecurityFirm = o.Enum()
	return s
}

func (s *TrdUnlockTradeRequest) SetSecurityFirm(o SecurityFirm) {
	s.SecurityFirm = o.Enum()
}

// true解锁交易，false锁定交易
func (s *TrdUnlockTradeRequest) WithUnlock(o bool) *TrdUnlockTradeRequest {
	s.Unlock = &o
	return s
}

func (s *TrdUnlockTradeRequest) SetUnlock(o bool) {
	s.Unlock = &o
}

// UsedQuotaRequest
// VerificationRequest
//图形验证码下载之后会将其存至固定路径，请到该路径下查看验证码
//Windows平台：%appdata%/com.futunn.FutuOpenD/F3CNN/PicVerifyCode.png
//非Windows平台：~/.com.futunn.FutuOpenD/F3CNN/PicVerifyCode.png
//注意：只有最后一次请求验证码会生效，重复请求只有最后一次的验证码有效

// 验证码，请求验证码时忽略该字段，输入时必填
func (s *VerificationRequest) WithCode(o string) *VerificationRequest {
	s.Code = &o
	return s
}

func (s *VerificationRequest) SetCode(o string) {
	s.Code = &o
}

// 操作, VerificationOp
func (s *VerificationRequest) WithOp(o VerificationOp) *VerificationRequest {
	s.Op = o.Enum()
	return s
}

func (s *VerificationRequest) SetOp(o VerificationOp) {
	s.Op = o.Enum()
}

// 验证码类型, VerificationType
func (s *VerificationRequest) WithType(o VerificationType) *VerificationRequest {
	s.Type = o.Enum()
	return s
}

func (s *VerificationRequest) SetType(o VerificationType) {
	s.Type = o.Enum()
}
