// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: GetUserInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_UpdateType_None   UpdateType = 0 //无需升级
	UpdateType_UpdateType_Advice UpdateType = 1 //建议升级
	UpdateType_UpdateType_Force  UpdateType = 2 //强制升级
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UpdateType_None",
		1: "UpdateType_Advice",
		2: "UpdateType_Force",
	}
	UpdateType_value = map[string]int32{
		"UpdateType_None":   0,
		"UpdateType_Advice": 1,
		"UpdateType_Force":  2,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_GetUserInfo_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_GetUserInfo_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UpdateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UpdateType(num)
	return nil
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{0}
}

type UserInfoField int32

const (
	UserInfoField_UserInfoField_Basic      UserInfoField = 1  //昵称，用户头像，牛牛号
	UserInfoField_UserInfoField_API        UserInfoField = 2  //API权限信息
	UserInfoField_UserInfoField_QotRight   UserInfoField = 4  //市场的行情权限
	UserInfoField_UserInfoField_Disclaimer UserInfoField = 8  //免责
	UserInfoField_UserInfoField_Update     UserInfoField = 16 //升级类型
	UserInfoField_UserInfoField_WebKey     UserInfoField = 2048
)

// Enum value maps for UserInfoField.
var (
	UserInfoField_name = map[int32]string{
		1:    "UserInfoField_Basic",
		2:    "UserInfoField_API",
		4:    "UserInfoField_QotRight",
		8:    "UserInfoField_Disclaimer",
		16:   "UserInfoField_Update",
		2048: "UserInfoField_WebKey",
	}
	UserInfoField_value = map[string]int32{
		"UserInfoField_Basic":      1,
		"UserInfoField_API":        2,
		"UserInfoField_QotRight":   4,
		"UserInfoField_Disclaimer": 8,
		"UserInfoField_Update":     16,
		"UserInfoField_WebKey":     2048,
	}
)

func (x UserInfoField) Enum() *UserInfoField {
	p := new(UserInfoField)
	*p = x
	return p
}

func (x UserInfoField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserInfoField) Descriptor() protoreflect.EnumDescriptor {
	return file_GetUserInfo_proto_enumTypes[1].Descriptor()
}

func (UserInfoField) Type() protoreflect.EnumType {
	return &file_GetUserInfo_proto_enumTypes[1]
}

func (x UserInfoField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserInfoField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserInfoField(num)
	return nil
}

// Deprecated: Use UserInfoField.Descriptor instead.
func (UserInfoField) EnumDescriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{1}
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          *int32                 `protobuf:"varint,2,opt,name=flag" json:"flag,omitempty"` //UserInfoField集合，不设置默认返回全部信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_GetUserInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetFlag() int32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

type GetUserInfoResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NickName              *string                `protobuf:"bytes,1,opt,name=nickName" json:"nickName,omitempty"`                             //用户昵称
	AvatarUrl             *string                `protobuf:"bytes,2,opt,name=avatarUrl" json:"avatarUrl,omitempty"`                           //用户头像url
	ApiLevel              *string                `protobuf:"bytes,3,opt,name=apiLevel" json:"apiLevel,omitempty"`                             //api用户等级描述, 已在2.10版本之后废弃
	HkQotRight            *QotRight              `protobuf:"varint,4,opt,name=hkQotRight,enum=futupb.QotRight" json:"hkQotRight,omitempty"`   //港股行情权限, QotRight
	UsQotRight            *QotRight              `protobuf:"varint,5,opt,name=usQotRight,enum=futupb.QotRight" json:"usQotRight,omitempty"`   //美股行情权限, QotRight
	CnQotRight            *int32                 `protobuf:"varint,6,opt,name=cnQotRight" json:"cnQotRight,omitempty"`                        //A股行情权限, QotRight // 废弃，使用shQotRight和szQotRight
	IsNeedAgreeDisclaimer *bool                  `protobuf:"varint,7,opt,name=isNeedAgreeDisclaimer" json:"isNeedAgreeDisclaimer,omitempty"`  //已开户用户需要同意免责声明，未开户或已同意的用户返回false
	UserID                *int64                 `protobuf:"varint,8,opt,name=userID" json:"userID,omitempty"`                                //用户牛牛号
	UpdateType            *UpdateType            `protobuf:"varint,9,opt,name=updateType,enum=futupb.UpdateType" json:"updateType,omitempty"` //升级类型，UpdateType
	WebKey                *string                `protobuf:"bytes,10,opt,name=webKey" json:"webKey,omitempty"`
	WebJumpUrlHead        *string                `protobuf:"bytes,18,opt,name=webJumpUrlHead" json:"webJumpUrlHead,omitempty"`
	HkOptionQotRight      *QotRight              `protobuf:"varint,11,opt,name=hkOptionQotRight,enum=futupb.QotRight" json:"hkOptionQotRight,omitempty"`           //港股期权行情权限, QotRight
	HasUSOptionQotRight   *bool                  `protobuf:"varint,12,opt,name=hasUSOptionQotRight" json:"hasUSOptionQotRight,omitempty"`                          //是否有美股期权行情权限
	HkFutureQotRight      *QotRight              `protobuf:"varint,13,opt,name=hkFutureQotRight,enum=futupb.QotRight" json:"hkFutureQotRight,omitempty"`           //港股期货行情权限, QotRight
	SubQuota              *int32                 `protobuf:"varint,14,opt,name=subQuota" json:"subQuota,omitempty"`                                                //订阅额度
	HistoryKLQuota        *int32                 `protobuf:"varint,15,opt,name=historyKLQuota" json:"historyKLQuota,omitempty"`                                    //历史K线额度
	UsFutureQotRight      *int32                 `protobuf:"varint,16,opt,name=usFutureQotRight" json:"usFutureQotRight,omitempty"`                                //美股期货行情权限, QotRight(已废弃)
	UsOptionQotRight      *QotRight              `protobuf:"varint,17,opt,name=usOptionQotRight,enum=futupb.QotRight" json:"usOptionQotRight,omitempty"`           //美股期货行情权限, QotRight
	UserAttribution       *UserAttribution       `protobuf:"varint,19,opt,name=userAttribution,enum=futupb.UserAttribution" json:"userAttribution,omitempty"`      //用户注册归属地, UserAttribution
	UpdateWhatsNew        *string                `protobuf:"bytes,20,opt,name=updateWhatsNew" json:"updateWhatsNew,omitempty"`                                     //升级提示
	UsIndexQotRight       *QotRight              `protobuf:"varint,21,opt,name=usIndexQotRight,enum=futupb.QotRight" json:"usIndexQotRight,omitempty"`             //美股指数行情权限, QotRight
	UsOtcQotRight         *QotRight              `protobuf:"varint,22,opt,name=usOtcQotRight,enum=futupb.QotRight" json:"usOtcQotRight,omitempty"`                 //美股OTC市场行情权限, QotRight
	UsCMEFutureQotRight   *QotRight              `protobuf:"varint,23,opt,name=usCMEFutureQotRight,enum=futupb.QotRight" json:"usCMEFutureQotRight,omitempty"`     //美股CME期货行情权限, QotRight
	UsCBOTFutureQotRight  *int32                 `protobuf:"varint,24,opt,name=usCBOTFutureQotRight" json:"usCBOTFutureQotRight,omitempty"`                        //美股CBOT期货行情权限, QotRight
	UsNYMEXFutureQotRight *QotRight              `protobuf:"varint,25,opt,name=usNYMEXFutureQotRight,enum=futupb.QotRight" json:"usNYMEXFutureQotRight,omitempty"` //美股NYMEX期货行情权限, QotRight
	UsCOMEXFutureQotRight *QotRight              `protobuf:"varint,26,opt,name=usCOMEXFutureQotRight,enum=futupb.QotRight" json:"usCOMEXFutureQotRight,omitempty"` //美股COMEX期货行情权限, QotRight
	UsCBOEFutureQotRight  *QotRight              `protobuf:"varint,27,opt,name=usCBOEFutureQotRight,enum=futupb.QotRight" json:"usCBOEFutureQotRight,omitempty"`   //美股CBOE期货行情权限, QotRight
	SgFutureQotRight      *QotRight              `protobuf:"varint,28,opt,name=sgFutureQotRight,enum=futupb.QotRight" json:"sgFutureQotRight,omitempty"`           //新加坡市场期货行情权限, QotRight
	JpFutureQotRight      *QotRight              `protobuf:"varint,29,opt,name=jpFutureQotRight,enum=futupb.QotRight" json:"jpFutureQotRight,omitempty"`           //日本市场期货行情权限, QotRight
	IsAppNNOrMM           *bool                  `protobuf:"varint,30,opt,name=isAppNNOrMM" json:"isAppNNOrMM,omitempty"`                                          //true:NN false:MM
	ShQotRight            *QotRight              `protobuf:"varint,31,opt,name=shQotRight,enum=futupb.QotRight" json:"shQotRight,omitempty"`                       //上海市场行情权限, QotRight
	SzQotRight            *QotRight              `protobuf:"varint,32,opt,name=szQotRight,enum=futupb.QotRight" json:"szQotRight,omitempty"`                       //深圳市场行情权限, QotRight
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_GetUserInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetNickName() string {
	if x != nil && x.NickName != nil {
		return *x.NickName
	}
	return ""
}

func (x *GetUserInfoResponse) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *GetUserInfoResponse) GetApiLevel() string {
	if x != nil && x.ApiLevel != nil {
		return *x.ApiLevel
	}
	return ""
}

func (x *GetUserInfoResponse) GetHkQotRight() QotRight {
	if x != nil && x.HkQotRight != nil {
		return *x.HkQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsQotRight() QotRight {
	if x != nil && x.UsQotRight != nil {
		return *x.UsQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetCnQotRight() int32 {
	if x != nil && x.CnQotRight != nil {
		return *x.CnQotRight
	}
	return 0
}

func (x *GetUserInfoResponse) GetIsNeedAgreeDisclaimer() bool {
	if x != nil && x.IsNeedAgreeDisclaimer != nil {
		return *x.IsNeedAgreeDisclaimer
	}
	return false
}

func (x *GetUserInfoResponse) GetUserID() int64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *GetUserInfoResponse) GetUpdateType() UpdateType {
	if x != nil && x.UpdateType != nil {
		return *x.UpdateType
	}
	return UpdateType_UpdateType_None
}

func (x *GetUserInfoResponse) GetWebKey() string {
	if x != nil && x.WebKey != nil {
		return *x.WebKey
	}
	return ""
}

func (x *GetUserInfoResponse) GetWebJumpUrlHead() string {
	if x != nil && x.WebJumpUrlHead != nil {
		return *x.WebJumpUrlHead
	}
	return ""
}

func (x *GetUserInfoResponse) GetHkOptionQotRight() QotRight {
	if x != nil && x.HkOptionQotRight != nil {
		return *x.HkOptionQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetHasUSOptionQotRight() bool {
	if x != nil && x.HasUSOptionQotRight != nil {
		return *x.HasUSOptionQotRight
	}
	return false
}

func (x *GetUserInfoResponse) GetHkFutureQotRight() QotRight {
	if x != nil && x.HkFutureQotRight != nil {
		return *x.HkFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetSubQuota() int32 {
	if x != nil && x.SubQuota != nil {
		return *x.SubQuota
	}
	return 0
}

func (x *GetUserInfoResponse) GetHistoryKLQuota() int32 {
	if x != nil && x.HistoryKLQuota != nil {
		return *x.HistoryKLQuota
	}
	return 0
}

func (x *GetUserInfoResponse) GetUsFutureQotRight() int32 {
	if x != nil && x.UsFutureQotRight != nil {
		return *x.UsFutureQotRight
	}
	return 0
}

func (x *GetUserInfoResponse) GetUsOptionQotRight() QotRight {
	if x != nil && x.UsOptionQotRight != nil {
		return *x.UsOptionQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUserAttribution() UserAttribution {
	if x != nil && x.UserAttribution != nil {
		return *x.UserAttribution
	}
	return UserAttribution_UserAttribution_Unknown
}

func (x *GetUserInfoResponse) GetUpdateWhatsNew() string {
	if x != nil && x.UpdateWhatsNew != nil {
		return *x.UpdateWhatsNew
	}
	return ""
}

func (x *GetUserInfoResponse) GetUsIndexQotRight() QotRight {
	if x != nil && x.UsIndexQotRight != nil {
		return *x.UsIndexQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsOtcQotRight() QotRight {
	if x != nil && x.UsOtcQotRight != nil {
		return *x.UsOtcQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsCMEFutureQotRight() QotRight {
	if x != nil && x.UsCMEFutureQotRight != nil {
		return *x.UsCMEFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsCBOTFutureQotRight() int32 {
	if x != nil && x.UsCBOTFutureQotRight != nil {
		return *x.UsCBOTFutureQotRight
	}
	return 0
}

func (x *GetUserInfoResponse) GetUsNYMEXFutureQotRight() QotRight {
	if x != nil && x.UsNYMEXFutureQotRight != nil {
		return *x.UsNYMEXFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsCOMEXFutureQotRight() QotRight {
	if x != nil && x.UsCOMEXFutureQotRight != nil {
		return *x.UsCOMEXFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetUsCBOEFutureQotRight() QotRight {
	if x != nil && x.UsCBOEFutureQotRight != nil {
		return *x.UsCBOEFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetSgFutureQotRight() QotRight {
	if x != nil && x.SgFutureQotRight != nil {
		return *x.SgFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetJpFutureQotRight() QotRight {
	if x != nil && x.JpFutureQotRight != nil {
		return *x.JpFutureQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetIsAppNNOrMM() bool {
	if x != nil && x.IsAppNNOrMM != nil {
		return *x.IsAppNNOrMM
	}
	return false
}

func (x *GetUserInfoResponse) GetShQotRight() QotRight {
	if x != nil && x.ShQotRight != nil {
		return *x.ShQotRight
	}
	return QotRight_QotRight_Unknown
}

func (x *GetUserInfoResponse) GetSzQotRight() QotRight {
	if x != nil && x.SzQotRight != nil {
		return *x.SzQotRight
	}
	return QotRight_QotRight_Unknown
}

type GetUserInfoRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *GetUserInfoRequest    `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest_Internal) Reset() {
	*x = GetUserInfoRequest_Internal{}
	mi := &file_GetUserInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest_Internal) ProtoMessage() {}

func (x *GetUserInfoRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest_Internal.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest_Internal) Descriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoRequest_Internal) GetPayload() *GetUserInfoRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetUserInfoResponse_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *RetType               `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //返回结果，参见Common.RetType的枚举定义
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`                                 //返回结果描述
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`                              //错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
	Payload       *GetUserInfoResponse   `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for GetUserInfoResponse_Internal fields.
const (
	Default_GetUserInfoResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *GetUserInfoResponse_Internal) Reset() {
	*x = GetUserInfoResponse_Internal{}
	mi := &file_GetUserInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse_Internal) ProtoMessage() {}

func (x *GetUserInfoResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse_Internal.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse_Internal) Descriptor() ([]byte, []int) {
	return file_GetUserInfo_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_GetUserInfoResponse_Internal_RetType
}

func (x *GetUserInfoResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *GetUserInfoResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *GetUserInfoResponse_Internal) GetPayload() *GetUserInfoResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_GetUserInfo_proto protoreflect.FileDescriptor

const file_GetUserInfo_proto_rawDesc = "" +
	"\n" +
	"\x11GetUserInfo.proto\x12\x06futupb\x1a\x10Qot_Common.proto\x1a\fCommon.proto\"(\n" +
	"\x12GetUserInfoRequest\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\x05R\x04flag\"\xbc\f\n" +
	"\x13GetUserInfoResponse\x12\x1a\n" +
	"\bnickName\x18\x01 \x01(\tR\bnickName\x12\x1c\n" +
	"\tavatarUrl\x18\x02 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bapiLevel\x18\x03 \x01(\tR\bapiLevel\x120\n" +
	"\n" +
	"hkQotRight\x18\x04 \x01(\x0e2\x10.futupb.QotRightR\n" +
	"hkQotRight\x120\n" +
	"\n" +
	"usQotRight\x18\x05 \x01(\x0e2\x10.futupb.QotRightR\n" +
	"usQotRight\x12\x1e\n" +
	"\n" +
	"cnQotRight\x18\x06 \x01(\x05R\n" +
	"cnQotRight\x124\n" +
	"\x15isNeedAgreeDisclaimer\x18\a \x01(\bR\x15isNeedAgreeDisclaimer\x12\x16\n" +
	"\x06userID\x18\b \x01(\x03R\x06userID\x122\n" +
	"\n" +
	"updateType\x18\t \x01(\x0e2\x12.futupb.UpdateTypeR\n" +
	"updateType\x12\x16\n" +
	"\x06webKey\x18\n" +
	" \x01(\tR\x06webKey\x12&\n" +
	"\x0ewebJumpUrlHead\x18\x12 \x01(\tR\x0ewebJumpUrlHead\x12<\n" +
	"\x10hkOptionQotRight\x18\v \x01(\x0e2\x10.futupb.QotRightR\x10hkOptionQotRight\x120\n" +
	"\x13hasUSOptionQotRight\x18\f \x01(\bR\x13hasUSOptionQotRight\x12<\n" +
	"\x10hkFutureQotRight\x18\r \x01(\x0e2\x10.futupb.QotRightR\x10hkFutureQotRight\x12\x1a\n" +
	"\bsubQuota\x18\x0e \x01(\x05R\bsubQuota\x12&\n" +
	"\x0ehistoryKLQuota\x18\x0f \x01(\x05R\x0ehistoryKLQuota\x12*\n" +
	"\x10usFutureQotRight\x18\x10 \x01(\x05R\x10usFutureQotRight\x12<\n" +
	"\x10usOptionQotRight\x18\x11 \x01(\x0e2\x10.futupb.QotRightR\x10usOptionQotRight\x12A\n" +
	"\x0fuserAttribution\x18\x13 \x01(\x0e2\x17.futupb.UserAttributionR\x0fuserAttribution\x12&\n" +
	"\x0eupdateWhatsNew\x18\x14 \x01(\tR\x0eupdateWhatsNew\x12:\n" +
	"\x0fusIndexQotRight\x18\x15 \x01(\x0e2\x10.futupb.QotRightR\x0fusIndexQotRight\x126\n" +
	"\rusOtcQotRight\x18\x16 \x01(\x0e2\x10.futupb.QotRightR\rusOtcQotRight\x12B\n" +
	"\x13usCMEFutureQotRight\x18\x17 \x01(\x0e2\x10.futupb.QotRightR\x13usCMEFutureQotRight\x122\n" +
	"\x14usCBOTFutureQotRight\x18\x18 \x01(\x05R\x14usCBOTFutureQotRight\x12F\n" +
	"\x15usNYMEXFutureQotRight\x18\x19 \x01(\x0e2\x10.futupb.QotRightR\x15usNYMEXFutureQotRight\x12F\n" +
	"\x15usCOMEXFutureQotRight\x18\x1a \x01(\x0e2\x10.futupb.QotRightR\x15usCOMEXFutureQotRight\x12D\n" +
	"\x14usCBOEFutureQotRight\x18\x1b \x01(\x0e2\x10.futupb.QotRightR\x14usCBOEFutureQotRight\x12<\n" +
	"\x10sgFutureQotRight\x18\x1c \x01(\x0e2\x10.futupb.QotRightR\x10sgFutureQotRight\x12<\n" +
	"\x10jpFutureQotRight\x18\x1d \x01(\x0e2\x10.futupb.QotRightR\x10jpFutureQotRight\x12 \n" +
	"\visAppNNOrMM\x18\x1e \x01(\bR\visAppNNOrMM\x120\n" +
	"\n" +
	"shQotRight\x18\x1f \x01(\x0e2\x10.futupb.QotRightR\n" +
	"shQotRight\x120\n" +
	"\n" +
	"szQotRight\x18  \x01(\x0e2\x10.futupb.QotRightR\n" +
	"szQotRight\"S\n" +
	"\x1bGetUserInfoRequest_Internal\x124\n" +
	"\apayload\x18\x01 \x02(\v2\x1a.futupb.GetUserInfoRequestR\apayload\"\xc3\x01\n" +
	"\x1cGetUserInfoResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x125\n" +
	"\apayload\x18\x04 \x01(\v2\x1b.futupb.GetUserInfoResponseR\apayload*N\n" +
	"\n" +
	"UpdateType\x12\x13\n" +
	"\x0fUpdateType_None\x10\x00\x12\x15\n" +
	"\x11UpdateType_Advice\x10\x01\x12\x14\n" +
	"\x10UpdateType_Force\x10\x02*\xae\x01\n" +
	"\rUserInfoField\x12\x17\n" +
	"\x13UserInfoField_Basic\x10\x01\x12\x15\n" +
	"\x11UserInfoField_API\x10\x02\x12\x1a\n" +
	"\x16UserInfoField_QotRight\x10\x04\x12\x1c\n" +
	"\x18UserInfoField_Disclaimer\x10\b\x12\x18\n" +
	"\x14UserInfoField_Update\x10\x10\x12\x19\n" +
	"\x14UserInfoField_WebKey\x10\x80\x10B4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_GetUserInfo_proto_rawDescOnce sync.Once
	file_GetUserInfo_proto_rawDescData []byte
)

func file_GetUserInfo_proto_rawDescGZIP() []byte {
	file_GetUserInfo_proto_rawDescOnce.Do(func() {
		file_GetUserInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetUserInfo_proto_rawDesc), len(file_GetUserInfo_proto_rawDesc)))
	})
	return file_GetUserInfo_proto_rawDescData
}

var file_GetUserInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_GetUserInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetUserInfo_proto_goTypes = []any{
	(UpdateType)(0),                      // 0: futupb.UpdateType
	(UserInfoField)(0),                   // 1: futupb.UserInfoField
	(*GetUserInfoRequest)(nil),           // 2: futupb.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),          // 3: futupb.GetUserInfoResponse
	(*GetUserInfoRequest_Internal)(nil),  // 4: futupb.GetUserInfoRequest_Internal
	(*GetUserInfoResponse_Internal)(nil), // 5: futupb.GetUserInfoResponse_Internal
	(QotRight)(0),                        // 6: futupb.QotRight
	(UserAttribution)(0),                 // 7: futupb.UserAttribution
	(RetType)(0),                         // 8: futupb.RetType
}
var file_GetUserInfo_proto_depIdxs = []int32{
	6,  // 0: futupb.GetUserInfoResponse.hkQotRight:type_name -> futupb.QotRight
	6,  // 1: futupb.GetUserInfoResponse.usQotRight:type_name -> futupb.QotRight
	0,  // 2: futupb.GetUserInfoResponse.updateType:type_name -> futupb.UpdateType
	6,  // 3: futupb.GetUserInfoResponse.hkOptionQotRight:type_name -> futupb.QotRight
	6,  // 4: futupb.GetUserInfoResponse.hkFutureQotRight:type_name -> futupb.QotRight
	6,  // 5: futupb.GetUserInfoResponse.usOptionQotRight:type_name -> futupb.QotRight
	7,  // 6: futupb.GetUserInfoResponse.userAttribution:type_name -> futupb.UserAttribution
	6,  // 7: futupb.GetUserInfoResponse.usIndexQotRight:type_name -> futupb.QotRight
	6,  // 8: futupb.GetUserInfoResponse.usOtcQotRight:type_name -> futupb.QotRight
	6,  // 9: futupb.GetUserInfoResponse.usCMEFutureQotRight:type_name -> futupb.QotRight
	6,  // 10: futupb.GetUserInfoResponse.usNYMEXFutureQotRight:type_name -> futupb.QotRight
	6,  // 11: futupb.GetUserInfoResponse.usCOMEXFutureQotRight:type_name -> futupb.QotRight
	6,  // 12: futupb.GetUserInfoResponse.usCBOEFutureQotRight:type_name -> futupb.QotRight
	6,  // 13: futupb.GetUserInfoResponse.sgFutureQotRight:type_name -> futupb.QotRight
	6,  // 14: futupb.GetUserInfoResponse.jpFutureQotRight:type_name -> futupb.QotRight
	6,  // 15: futupb.GetUserInfoResponse.shQotRight:type_name -> futupb.QotRight
	6,  // 16: futupb.GetUserInfoResponse.szQotRight:type_name -> futupb.QotRight
	2,  // 17: futupb.GetUserInfoRequest_Internal.payload:type_name -> futupb.GetUserInfoRequest
	8,  // 18: futupb.GetUserInfoResponse_Internal.retType:type_name -> futupb.RetType
	3,  // 19: futupb.GetUserInfoResponse_Internal.payload:type_name -> futupb.GetUserInfoResponse
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_GetUserInfo_proto_init() }
func file_GetUserInfo_proto_init() {
	if File_GetUserInfo_proto != nil {
		return
	}
	file_Qot_Common_proto_init()
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetUserInfo_proto_rawDesc), len(file_GetUserInfo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetUserInfo_proto_goTypes,
		DependencyIndexes: file_GetUserInfo_proto_depIdxs,
		EnumInfos:         file_GetUserInfo_proto_enumTypes,
		MessageInfos:      file_GetUserInfo_proto_msgTypes,
	}.Build()
	File_GetUserInfo_proto = out.File
	file_GetUserInfo_proto_goTypes = nil
	file_GetUserInfo_proto_depIdxs = nil
}
