// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: InitConnect.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitConnectRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ClientVer  *int32                 `protobuf:"varint,1,req,name=clientVer" json:"clientVer,omitempty"`   //客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
	ClientID   *string                `protobuf:"bytes,2,req,name=clientID" json:"clientID,omitempty"`      //客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
	RecvNotify *bool                  `protobuf:"varint,3,opt,name=recvNotify" json:"recvNotify,omitempty"` //此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
	// 如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
	// 如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
	PacketEncAlgo       *PacketEncAlgo `protobuf:"varint,4,opt,name=packetEncAlgo,enum=futupb.PacketEncAlgo" json:"packetEncAlgo,omitempty"` //指定包加密算法，参见Common.PacketEncAlgo的枚举定义
	PushProtoFmt        *ProtoFmt      `protobuf:"varint,5,opt,name=pushProtoFmt,enum=futupb.ProtoFmt" json:"pushProtoFmt,omitempty"`        //指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
	ProgrammingLanguage *string        `protobuf:"bytes,6,opt,name=programmingLanguage" json:"programmingLanguage,omitempty"`                //接口编程语言，用于统计语言偏好
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InitConnectRequest) Reset() {
	*x = InitConnectRequest{}
	mi := &file_InitConnect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectRequest) ProtoMessage() {}

func (x *InitConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InitConnect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectRequest.ProtoReflect.Descriptor instead.
func (*InitConnectRequest) Descriptor() ([]byte, []int) {
	return file_InitConnect_proto_rawDescGZIP(), []int{0}
}

func (x *InitConnectRequest) GetClientVer() int32 {
	if x != nil && x.ClientVer != nil {
		return *x.ClientVer
	}
	return 0
}

func (x *InitConnectRequest) GetClientID() string {
	if x != nil && x.ClientID != nil {
		return *x.ClientID
	}
	return ""
}

func (x *InitConnectRequest) GetRecvNotify() bool {
	if x != nil && x.RecvNotify != nil {
		return *x.RecvNotify
	}
	return false
}

func (x *InitConnectRequest) GetPacketEncAlgo() PacketEncAlgo {
	if x != nil && x.PacketEncAlgo != nil {
		return *x.PacketEncAlgo
	}
	return PacketEncAlgo_PacketEncAlgo_FTAES_ECB
}

func (x *InitConnectRequest) GetPushProtoFmt() ProtoFmt {
	if x != nil && x.PushProtoFmt != nil {
		return *x.PushProtoFmt
	}
	return ProtoFmt_ProtoFmt_Protobuf
}

func (x *InitConnectRequest) GetProgrammingLanguage() string {
	if x != nil && x.ProgrammingLanguage != nil {
		return *x.ProgrammingLanguage
	}
	return ""
}

type InitConnectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerVer         *int32                 `protobuf:"varint,1,req,name=serverVer" json:"serverVer,omitempty"`                                         //FutuOpenD的版本号
	LoginUserID       *uint64                `protobuf:"varint,2,req,name=loginUserID" json:"loginUserID,omitempty"`                                     //FutuOpenD登陆的牛牛用户ID
	ConnID            *uint64                `protobuf:"varint,3,req,name=connID" json:"connID,omitempty"`                                               //此连接的连接ID，连接的唯一标识
	ConnAESKey        *string                `protobuf:"bytes,4,req,name=connAESKey" json:"connAESKey,omitempty"`                                        //此连接后续AES加密通信的Key，固定为16字节长字符串
	KeepAliveInterval *int32                 `protobuf:"varint,5,req,name=keepAliveInterval" json:"keepAliveInterval,omitempty"`                         //心跳保活间隔
	AesCBCiv          *string                `protobuf:"bytes,6,opt,name=aesCBCiv" json:"aesCBCiv,omitempty"`                                            //AES加密通信CBC加密模式的iv，固定为16字节长字符串
	UserAttribution   *UserAttribution       `protobuf:"varint,7,opt,name=userAttribution,enum=futupb.UserAttribution" json:"userAttribution,omitempty"` //用户类型，牛牛用户或MooMoo用户
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitConnectResponse) Reset() {
	*x = InitConnectResponse{}
	mi := &file_InitConnect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectResponse) ProtoMessage() {}

func (x *InitConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InitConnect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectResponse.ProtoReflect.Descriptor instead.
func (*InitConnectResponse) Descriptor() ([]byte, []int) {
	return file_InitConnect_proto_rawDescGZIP(), []int{1}
}

func (x *InitConnectResponse) GetServerVer() int32 {
	if x != nil && x.ServerVer != nil {
		return *x.ServerVer
	}
	return 0
}

func (x *InitConnectResponse) GetLoginUserID() uint64 {
	if x != nil && x.LoginUserID != nil {
		return *x.LoginUserID
	}
	return 0
}

func (x *InitConnectResponse) GetConnID() uint64 {
	if x != nil && x.ConnID != nil {
		return *x.ConnID
	}
	return 0
}

func (x *InitConnectResponse) GetConnAESKey() string {
	if x != nil && x.ConnAESKey != nil {
		return *x.ConnAESKey
	}
	return ""
}

func (x *InitConnectResponse) GetKeepAliveInterval() int32 {
	if x != nil && x.KeepAliveInterval != nil {
		return *x.KeepAliveInterval
	}
	return 0
}

func (x *InitConnectResponse) GetAesCBCiv() string {
	if x != nil && x.AesCBCiv != nil {
		return *x.AesCBCiv
	}
	return ""
}

func (x *InitConnectResponse) GetUserAttribution() UserAttribution {
	if x != nil && x.UserAttribution != nil {
		return *x.UserAttribution
	}
	return UserAttribution_UserAttribution_Unknown
}

type InitConnectRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *InitConnectRequest    `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitConnectRequest_Internal) Reset() {
	*x = InitConnectRequest_Internal{}
	mi := &file_InitConnect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitConnectRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectRequest_Internal) ProtoMessage() {}

func (x *InitConnectRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_InitConnect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectRequest_Internal.ProtoReflect.Descriptor instead.
func (*InitConnectRequest_Internal) Descriptor() ([]byte, []int) {
	return file_InitConnect_proto_rawDescGZIP(), []int{2}
}

func (x *InitConnectRequest_Internal) GetPayload() *InitConnectRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InitConnectResponse_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *RetType               `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //返回结果，参见Common.RetType的枚举定义
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`                                 //返回结果描述
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`                              //错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
	Payload       *InitConnectResponse   `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for InitConnectResponse_Internal fields.
const (
	Default_InitConnectResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *InitConnectResponse_Internal) Reset() {
	*x = InitConnectResponse_Internal{}
	mi := &file_InitConnect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitConnectResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectResponse_Internal) ProtoMessage() {}

func (x *InitConnectResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_InitConnect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectResponse_Internal.ProtoReflect.Descriptor instead.
func (*InitConnectResponse_Internal) Descriptor() ([]byte, []int) {
	return file_InitConnect_proto_rawDescGZIP(), []int{3}
}

func (x *InitConnectResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_InitConnectResponse_Internal_RetType
}

func (x *InitConnectResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *InitConnectResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *InitConnectResponse_Internal) GetPayload() *InitConnectResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_InitConnect_proto protoreflect.FileDescriptor

const file_InitConnect_proto_rawDesc = "" +
	"\n" +
	"\x11InitConnect.proto\x12\x06futupb\x1a\fCommon.proto\"\x93\x02\n" +
	"\x12InitConnectRequest\x12\x1c\n" +
	"\tclientVer\x18\x01 \x02(\x05R\tclientVer\x12\x1a\n" +
	"\bclientID\x18\x02 \x02(\tR\bclientID\x12\x1e\n" +
	"\n" +
	"recvNotify\x18\x03 \x01(\bR\n" +
	"recvNotify\x12;\n" +
	"\rpacketEncAlgo\x18\x04 \x01(\x0e2\x15.futupb.PacketEncAlgoR\rpacketEncAlgo\x124\n" +
	"\fpushProtoFmt\x18\x05 \x01(\x0e2\x10.futupb.ProtoFmtR\fpushProtoFmt\x120\n" +
	"\x13programmingLanguage\x18\x06 \x01(\tR\x13programmingLanguage\"\x9a\x02\n" +
	"\x13InitConnectResponse\x12\x1c\n" +
	"\tserverVer\x18\x01 \x02(\x05R\tserverVer\x12 \n" +
	"\vloginUserID\x18\x02 \x02(\x04R\vloginUserID\x12\x16\n" +
	"\x06connID\x18\x03 \x02(\x04R\x06connID\x12\x1e\n" +
	"\n" +
	"connAESKey\x18\x04 \x02(\tR\n" +
	"connAESKey\x12,\n" +
	"\x11keepAliveInterval\x18\x05 \x02(\x05R\x11keepAliveInterval\x12\x1a\n" +
	"\baesCBCiv\x18\x06 \x01(\tR\baesCBCiv\x12A\n" +
	"\x0fuserAttribution\x18\a \x01(\x0e2\x17.futupb.UserAttributionR\x0fuserAttribution\"S\n" +
	"\x1bInitConnectRequest_Internal\x124\n" +
	"\apayload\x18\x01 \x02(\v2\x1a.futupb.InitConnectRequestR\apayload\"\xc3\x01\n" +
	"\x1cInitConnectResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x125\n" +
	"\apayload\x18\x04 \x01(\v2\x1b.futupb.InitConnectResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_InitConnect_proto_rawDescOnce sync.Once
	file_InitConnect_proto_rawDescData []byte
)

func file_InitConnect_proto_rawDescGZIP() []byte {
	file_InitConnect_proto_rawDescOnce.Do(func() {
		file_InitConnect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_InitConnect_proto_rawDesc), len(file_InitConnect_proto_rawDesc)))
	})
	return file_InitConnect_proto_rawDescData
}

var file_InitConnect_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_InitConnect_proto_goTypes = []any{
	(*InitConnectRequest)(nil),           // 0: futupb.InitConnectRequest
	(*InitConnectResponse)(nil),          // 1: futupb.InitConnectResponse
	(*InitConnectRequest_Internal)(nil),  // 2: futupb.InitConnectRequest_Internal
	(*InitConnectResponse_Internal)(nil), // 3: futupb.InitConnectResponse_Internal
	(PacketEncAlgo)(0),                   // 4: futupb.PacketEncAlgo
	(ProtoFmt)(0),                        // 5: futupb.ProtoFmt
	(UserAttribution)(0),                 // 6: futupb.UserAttribution
	(RetType)(0),                         // 7: futupb.RetType
}
var file_InitConnect_proto_depIdxs = []int32{
	4, // 0: futupb.InitConnectRequest.packetEncAlgo:type_name -> futupb.PacketEncAlgo
	5, // 1: futupb.InitConnectRequest.pushProtoFmt:type_name -> futupb.ProtoFmt
	6, // 2: futupb.InitConnectResponse.userAttribution:type_name -> futupb.UserAttribution
	0, // 3: futupb.InitConnectRequest_Internal.payload:type_name -> futupb.InitConnectRequest
	7, // 4: futupb.InitConnectResponse_Internal.retType:type_name -> futupb.RetType
	1, // 5: futupb.InitConnectResponse_Internal.payload:type_name -> futupb.InitConnectResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_InitConnect_proto_init() }
func file_InitConnect_proto_init() {
	if File_InitConnect_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_InitConnect_proto_rawDesc), len(file_InitConnect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InitConnect_proto_goTypes,
		DependencyIndexes: file_InitConnect_proto_depIdxs,
		MessageInfos:      file_InitConnect_proto_msgTypes,
	}.Build()
	File_InitConnect_proto = out.File
	file_InitConnect_proto_goTypes = nil
	file_InitConnect_proto_depIdxs = nil
}
