// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: KeepAlive.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeepAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *int64                 `protobuf:"varint,1,req,name=time" json:"time,omitempty"` //客户端发包时的格林威治时间戳，单位秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	mi := &file_KeepAlive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KeepAlive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_KeepAlive_proto_rawDescGZIP(), []int{0}
}

func (x *KeepAliveRequest) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type KeepAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *int64                 `protobuf:"varint,1,req,name=time" json:"time,omitempty"` //服务器回包时的格林威治时间戳，单位秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveResponse) Reset() {
	*x = KeepAliveResponse{}
	mi := &file_KeepAlive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse) ProtoMessage() {}

func (x *KeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_KeepAlive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_KeepAlive_proto_rawDescGZIP(), []int{1}
}

func (x *KeepAliveResponse) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type KeepAliveRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *KeepAliveRequest      `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest_Internal) Reset() {
	*x = KeepAliveRequest_Internal{}
	mi := &file_KeepAlive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest_Internal) ProtoMessage() {}

func (x *KeepAliveRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_KeepAlive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest_Internal.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest_Internal) Descriptor() ([]byte, []int) {
	return file_KeepAlive_proto_rawDescGZIP(), []int{2}
}

func (x *KeepAliveRequest_Internal) GetPayload() *KeepAliveRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type KeepAliveResponse_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *RetType               `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *KeepAliveResponse     `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for KeepAliveResponse_Internal fields.
const (
	Default_KeepAliveResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *KeepAliveResponse_Internal) Reset() {
	*x = KeepAliveResponse_Internal{}
	mi := &file_KeepAlive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse_Internal) ProtoMessage() {}

func (x *KeepAliveResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_KeepAlive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse_Internal.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse_Internal) Descriptor() ([]byte, []int) {
	return file_KeepAlive_proto_rawDescGZIP(), []int{3}
}

func (x *KeepAliveResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_KeepAliveResponse_Internal_RetType
}

func (x *KeepAliveResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *KeepAliveResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *KeepAliveResponse_Internal) GetPayload() *KeepAliveResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_KeepAlive_proto protoreflect.FileDescriptor

const file_KeepAlive_proto_rawDesc = "" +
	"\n" +
	"\x0fKeepAlive.proto\x12\x06futupb\x1a\fCommon.proto\"&\n" +
	"\x10KeepAliveRequest\x12\x12\n" +
	"\x04time\x18\x01 \x02(\x03R\x04time\"'\n" +
	"\x11KeepAliveResponse\x12\x12\n" +
	"\x04time\x18\x01 \x02(\x03R\x04time\"O\n" +
	"\x19KeepAliveRequest_Internal\x122\n" +
	"\apayload\x18\x01 \x02(\v2\x18.futupb.KeepAliveRequestR\apayload\"\xbf\x01\n" +
	"\x1aKeepAliveResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x123\n" +
	"\apayload\x18\x04 \x01(\v2\x19.futupb.KeepAliveResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_KeepAlive_proto_rawDescOnce sync.Once
	file_KeepAlive_proto_rawDescData []byte
)

func file_KeepAlive_proto_rawDescGZIP() []byte {
	file_KeepAlive_proto_rawDescOnce.Do(func() {
		file_KeepAlive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_KeepAlive_proto_rawDesc), len(file_KeepAlive_proto_rawDesc)))
	})
	return file_KeepAlive_proto_rawDescData
}

var file_KeepAlive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_KeepAlive_proto_goTypes = []any{
	(*KeepAliveRequest)(nil),           // 0: futupb.KeepAliveRequest
	(*KeepAliveResponse)(nil),          // 1: futupb.KeepAliveResponse
	(*KeepAliveRequest_Internal)(nil),  // 2: futupb.KeepAliveRequest_Internal
	(*KeepAliveResponse_Internal)(nil), // 3: futupb.KeepAliveResponse_Internal
	(RetType)(0),                       // 4: futupb.RetType
}
var file_KeepAlive_proto_depIdxs = []int32{
	0, // 0: futupb.KeepAliveRequest_Internal.payload:type_name -> futupb.KeepAliveRequest
	4, // 1: futupb.KeepAliveResponse_Internal.retType:type_name -> futupb.RetType
	1, // 2: futupb.KeepAliveResponse_Internal.payload:type_name -> futupb.KeepAliveResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_KeepAlive_proto_init() }
func file_KeepAlive_proto_init() {
	if File_KeepAlive_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_KeepAlive_proto_rawDesc), len(file_KeepAlive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KeepAlive_proto_goTypes,
		DependencyIndexes: file_KeepAlive_proto_depIdxs,
		MessageInfos:      file_KeepAlive_proto_msgTypes,
	}.Build()
	File_KeepAlive_proto = out.File
	file_KeepAlive_proto_goTypes = nil
	file_KeepAlive_proto_depIdxs = nil
}
