// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Qot_GetPlateSet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotGetPlateSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *int32                 `protobuf:"varint,1,req,name=market" json:"market,omitempty"`             //Qot_Common.QotMarket,股票市场
	PlateSetType  *int32                 `protobuf:"varint,2,req,name=plateSetType" json:"plateSetType,omitempty"` //Qot_Common.PlateSetType,板块集合的类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetPlateSetRequest) Reset() {
	*x = QotGetPlateSetRequest{}
	mi := &file_Qot_GetPlateSet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetPlateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetPlateSetRequest) ProtoMessage() {}

func (x *QotGetPlateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetPlateSet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetPlateSetRequest.ProtoReflect.Descriptor instead.
func (*QotGetPlateSetRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetPlateSet_proto_rawDescGZIP(), []int{0}
}

func (x *QotGetPlateSetRequest) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *QotGetPlateSetRequest) GetPlateSetType() int32 {
	if x != nil && x.PlateSetType != nil {
		return *x.PlateSetType
	}
	return 0
}

type QotGetPlateSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateInfoList []*PlateInfo           `protobuf:"bytes,1,rep,name=plateInfoList" json:"plateInfoList,omitempty"` //板块集合下的板块信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetPlateSetResponse) Reset() {
	*x = QotGetPlateSetResponse{}
	mi := &file_Qot_GetPlateSet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetPlateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetPlateSetResponse) ProtoMessage() {}

func (x *QotGetPlateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetPlateSet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetPlateSetResponse.ProtoReflect.Descriptor instead.
func (*QotGetPlateSetResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetPlateSet_proto_rawDescGZIP(), []int{1}
}

func (x *QotGetPlateSetResponse) GetPlateInfoList() []*PlateInfo {
	if x != nil {
		return x.PlateInfoList
	}
	return nil
}

type QotGetPlateSetRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *QotGetPlateSetRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetPlateSetRequest_Internal) Reset() {
	*x = QotGetPlateSetRequest_Internal{}
	mi := &file_Qot_GetPlateSet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetPlateSetRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetPlateSetRequest_Internal) ProtoMessage() {}

func (x *QotGetPlateSetRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetPlateSet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetPlateSetRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetPlateSetRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetPlateSet_proto_rawDescGZIP(), []int{2}
}

func (x *QotGetPlateSetRequest_Internal) GetPayload() *QotGetPlateSetRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetPlateSetResponse_Internal struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RetType       *int32                  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                 `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetPlateSetResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetPlateSetResponse_Internal fields.
const (
	Default_QotGetPlateSetResponse_Internal_RetType = int32(-400)
)

func (x *QotGetPlateSetResponse_Internal) Reset() {
	*x = QotGetPlateSetResponse_Internal{}
	mi := &file_Qot_GetPlateSet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetPlateSetResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetPlateSetResponse_Internal) ProtoMessage() {}

func (x *QotGetPlateSetResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetPlateSet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetPlateSetResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetPlateSetResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetPlateSet_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetPlateSetResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetPlateSetResponse_Internal_RetType
}

func (x *QotGetPlateSetResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetPlateSetResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetPlateSetResponse_Internal) GetPayload() *QotGetPlateSetResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetPlateSet_proto protoreflect.FileDescriptor

const file_Qot_GetPlateSet_proto_rawDesc = "" +
	"\n" +
	"\x15Qot_GetPlateSet.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"S\n" +
	"\x15QotGetPlateSetRequest\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12\"\n" +
	"\fplateSetType\x18\x02 \x02(\x05R\fplateSetType\"Q\n" +
	"\x16QotGetPlateSetResponse\x127\n" +
	"\rplateInfoList\x18\x01 \x03(\v2\x11.futupb.PlateInfoR\rplateInfoList\"Y\n" +
	"\x1eQotGetPlateSetRequest_Internal\x127\n" +
	"\apayload\x18\x01 \x02(\v2\x1d.futupb.QotGetPlateSetRequestR\apayload\"\xad\x01\n" +
	"\x1fQotGetPlateSetResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x128\n" +
	"\apayload\x18\x04 \x01(\v2\x1e.futupb.QotGetPlateSetResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetPlateSet_proto_rawDescOnce sync.Once
	file_Qot_GetPlateSet_proto_rawDescData []byte
)

func file_Qot_GetPlateSet_proto_rawDescGZIP() []byte {
	file_Qot_GetPlateSet_proto_rawDescOnce.Do(func() {
		file_Qot_GetPlateSet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetPlateSet_proto_rawDesc), len(file_Qot_GetPlateSet_proto_rawDesc)))
	})
	return file_Qot_GetPlateSet_proto_rawDescData
}

var file_Qot_GetPlateSet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_GetPlateSet_proto_goTypes = []any{
	(*QotGetPlateSetRequest)(nil),           // 0: futupb.QotGetPlateSetRequest
	(*QotGetPlateSetResponse)(nil),          // 1: futupb.QotGetPlateSetResponse
	(*QotGetPlateSetRequest_Internal)(nil),  // 2: futupb.QotGetPlateSetRequest_Internal
	(*QotGetPlateSetResponse_Internal)(nil), // 3: futupb.QotGetPlateSetResponse_Internal
	(*PlateInfo)(nil),                       // 4: futupb.PlateInfo
}
var file_Qot_GetPlateSet_proto_depIdxs = []int32{
	4, // 0: futupb.QotGetPlateSetResponse.plateInfoList:type_name -> futupb.PlateInfo
	0, // 1: futupb.QotGetPlateSetRequest_Internal.payload:type_name -> futupb.QotGetPlateSetRequest
	1, // 2: futupb.QotGetPlateSetResponse_Internal.payload:type_name -> futupb.QotGetPlateSetResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_GetPlateSet_proto_init() }
func file_Qot_GetPlateSet_proto_init() {
	if File_Qot_GetPlateSet_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetPlateSet_proto_rawDesc), len(file_Qot_GetPlateSet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetPlateSet_proto_goTypes,
		DependencyIndexes: file_Qot_GetPlateSet_proto_depIdxs,
		MessageInfos:      file_Qot_GetPlateSet_proto_msgTypes,
	}.Build()
	File_Qot_GetPlateSet_proto = out.File
	file_Qot_GetPlateSet_proto_goTypes = nil
	file_Qot_GetPlateSet_proto_depIdxs = nil
}
