// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Qot_UpdateTicker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotUpdateTickerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`     //股票
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`             //股票名称
	TickerList    []*Ticker              `protobuf:"bytes,2,rep,name=tickerList" json:"tickerList,omitempty"` //逐笔
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotUpdateTickerResponse) Reset() {
	*x = QotUpdateTickerResponse{}
	mi := &file_Qot_UpdateTicker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotUpdateTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotUpdateTickerResponse) ProtoMessage() {}

func (x *QotUpdateTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateTicker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotUpdateTickerResponse.ProtoReflect.Descriptor instead.
func (*QotUpdateTickerResponse) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateTicker_proto_rawDescGZIP(), []int{0}
}

func (x *QotUpdateTickerResponse) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotUpdateTickerResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QotUpdateTickerResponse) GetTickerList() []*Ticker {
	if x != nil {
		return x.TickerList
	}
	return nil
}

type QotUpdateTickerResponse_Internal struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RetType       *int32                   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotUpdateTickerResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotUpdateTickerResponse_Internal fields.
const (
	Default_QotUpdateTickerResponse_Internal_RetType = int32(-400)
)

func (x *QotUpdateTickerResponse_Internal) Reset() {
	*x = QotUpdateTickerResponse_Internal{}
	mi := &file_Qot_UpdateTicker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotUpdateTickerResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotUpdateTickerResponse_Internal) ProtoMessage() {}

func (x *QotUpdateTickerResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateTicker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotUpdateTickerResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotUpdateTickerResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateTicker_proto_rawDescGZIP(), []int{1}
}

func (x *QotUpdateTickerResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotUpdateTickerResponse_Internal_RetType
}

func (x *QotUpdateTickerResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotUpdateTickerResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotUpdateTickerResponse_Internal) GetPayload() *QotUpdateTickerResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_UpdateTicker_proto protoreflect.FileDescriptor

const file_Qot_UpdateTicker_proto_rawDesc = "" +
	"\n" +
	"\x16Qot_UpdateTicker.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\x8b\x01\n" +
	"\x17QotUpdateTickerResponse\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\n" +
	"tickerList\x18\x02 \x03(\v2\x0e.futupb.TickerR\n" +
	"tickerList\"\xaf\x01\n" +
	" QotUpdateTickerResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1f.futupb.QotUpdateTickerResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_UpdateTicker_proto_rawDescOnce sync.Once
	file_Qot_UpdateTicker_proto_rawDescData []byte
)

func file_Qot_UpdateTicker_proto_rawDescGZIP() []byte {
	file_Qot_UpdateTicker_proto_rawDescOnce.Do(func() {
		file_Qot_UpdateTicker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_UpdateTicker_proto_rawDesc), len(file_Qot_UpdateTicker_proto_rawDesc)))
	})
	return file_Qot_UpdateTicker_proto_rawDescData
}

var file_Qot_UpdateTicker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Qot_UpdateTicker_proto_goTypes = []any{
	(*QotUpdateTickerResponse)(nil),          // 0: futupb.QotUpdateTickerResponse
	(*QotUpdateTickerResponse_Internal)(nil), // 1: futupb.QotUpdateTickerResponse_Internal
	(*Security)(nil),                         // 2: futupb.Security
	(*Ticker)(nil),                           // 3: futupb.Ticker
}
var file_Qot_UpdateTicker_proto_depIdxs = []int32{
	2, // 0: futupb.QotUpdateTickerResponse.security:type_name -> futupb.Security
	3, // 1: futupb.QotUpdateTickerResponse.tickerList:type_name -> futupb.Ticker
	0, // 2: futupb.QotUpdateTickerResponse_Internal.payload:type_name -> futupb.QotUpdateTickerResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_UpdateTicker_proto_init() }
func file_Qot_UpdateTicker_proto_init() {
	if File_Qot_UpdateTicker_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_UpdateTicker_proto_rawDesc), len(file_Qot_UpdateTicker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_UpdateTicker_proto_goTypes,
		DependencyIndexes: file_Qot_UpdateTicker_proto_depIdxs,
		MessageInfos:      file_Qot_UpdateTicker_proto_msgTypes,
	}.Build()
	File_Qot_UpdateTicker_proto = out.File
	file_Qot_UpdateTicker_proto_goTypes = nil
	file_Qot_UpdateTicker_proto_depIdxs = nil
}
