// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Qot_UpdateOrderBook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotUpdateOrderBookResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Security                *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                                 //股票
	Name                    *string                `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`                                         //股票名称
	OrderBookAskList        []*OrderBook           `protobuf:"bytes,2,rep,name=orderBookAskList" json:"orderBookAskList,omitempty"`                 //卖盘
	OrderBookBidList        []*OrderBook           `protobuf:"bytes,3,rep,name=orderBookBidList" json:"orderBookBidList,omitempty"`                 //买盘
	SvrRecvTimeBid          *string                `protobuf:"bytes,4,opt,name=svrRecvTimeBid" json:"svrRecvTimeBid,omitempty"`                     // 富途服务器从交易所收到数据的时间(for bid)部分数据的接收时间为零，例如服务器重启或第一次推送的缓存数据。该字段暂时只支持港股。
	SvrRecvTimeBidTimestamp *float64               `protobuf:"fixed64,5,opt,name=svrRecvTimeBidTimestamp" json:"svrRecvTimeBidTimestamp,omitempty"` // 富途服务器从交易所收到数据的时间戳(for bid)
	SvrRecvTimeAsk          *string                `protobuf:"bytes,6,opt,name=svrRecvTimeAsk" json:"svrRecvTimeAsk,omitempty"`                     // 富途服务器从交易所收到数据的时间(for ask)
	SvrRecvTimeAskTimestamp *float64               `protobuf:"fixed64,7,opt,name=svrRecvTimeAskTimestamp" json:"svrRecvTimeAskTimestamp,omitempty"` // 富途服务器从交易所收到数据的时间戳(for ask)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *QotUpdateOrderBookResponse) Reset() {
	*x = QotUpdateOrderBookResponse{}
	mi := &file_Qot_UpdateOrderBook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotUpdateOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotUpdateOrderBookResponse) ProtoMessage() {}

func (x *QotUpdateOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateOrderBook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotUpdateOrderBookResponse.ProtoReflect.Descriptor instead.
func (*QotUpdateOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateOrderBook_proto_rawDescGZIP(), []int{0}
}

func (x *QotUpdateOrderBookResponse) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotUpdateOrderBookResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QotUpdateOrderBookResponse) GetOrderBookAskList() []*OrderBook {
	if x != nil {
		return x.OrderBookAskList
	}
	return nil
}

func (x *QotUpdateOrderBookResponse) GetOrderBookBidList() []*OrderBook {
	if x != nil {
		return x.OrderBookBidList
	}
	return nil
}

func (x *QotUpdateOrderBookResponse) GetSvrRecvTimeBid() string {
	if x != nil && x.SvrRecvTimeBid != nil {
		return *x.SvrRecvTimeBid
	}
	return ""
}

func (x *QotUpdateOrderBookResponse) GetSvrRecvTimeBidTimestamp() float64 {
	if x != nil && x.SvrRecvTimeBidTimestamp != nil {
		return *x.SvrRecvTimeBidTimestamp
	}
	return 0
}

func (x *QotUpdateOrderBookResponse) GetSvrRecvTimeAsk() string {
	if x != nil && x.SvrRecvTimeAsk != nil {
		return *x.SvrRecvTimeAsk
	}
	return ""
}

func (x *QotUpdateOrderBookResponse) GetSvrRecvTimeAskTimestamp() float64 {
	if x != nil && x.SvrRecvTimeAskTimestamp != nil {
		return *x.SvrRecvTimeAskTimestamp
	}
	return 0
}

type QotUpdateOrderBookResponse_Internal struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	RetType       *RetType                    `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                     `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                      `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotUpdateOrderBookResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotUpdateOrderBookResponse_Internal fields.
const (
	Default_QotUpdateOrderBookResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotUpdateOrderBookResponse_Internal) Reset() {
	*x = QotUpdateOrderBookResponse_Internal{}
	mi := &file_Qot_UpdateOrderBook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotUpdateOrderBookResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotUpdateOrderBookResponse_Internal) ProtoMessage() {}

func (x *QotUpdateOrderBookResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateOrderBook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotUpdateOrderBookResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotUpdateOrderBookResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateOrderBook_proto_rawDescGZIP(), []int{1}
}

func (x *QotUpdateOrderBookResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotUpdateOrderBookResponse_Internal_RetType
}

func (x *QotUpdateOrderBookResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotUpdateOrderBookResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotUpdateOrderBookResponse_Internal) GetPayload() *QotUpdateOrderBookResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_UpdateOrderBook_proto protoreflect.FileDescriptor

const file_Qot_UpdateOrderBook_proto_rawDesc = "" +
	"\n" +
	"\x19Qot_UpdateOrderBook.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xa0\x03\n" +
	"\x1aQotUpdateOrderBookResponse\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12=\n" +
	"\x10orderBookAskList\x18\x02 \x03(\v2\x11.futupb.OrderBookR\x10orderBookAskList\x12=\n" +
	"\x10orderBookBidList\x18\x03 \x03(\v2\x11.futupb.OrderBookR\x10orderBookBidList\x12&\n" +
	"\x0esvrRecvTimeBid\x18\x04 \x01(\tR\x0esvrRecvTimeBid\x128\n" +
	"\x17svrRecvTimeBidTimestamp\x18\x05 \x01(\x01R\x17svrRecvTimeBidTimestamp\x12&\n" +
	"\x0esvrRecvTimeAsk\x18\x06 \x01(\tR\x0esvrRecvTimeAsk\x128\n" +
	"\x17svrRecvTimeAskTimestamp\x18\a \x01(\x01R\x17svrRecvTimeAskTimestamp\"\xd1\x01\n" +
	"#QotUpdateOrderBookResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12<\n" +
	"\apayload\x18\x04 \x01(\v2\".futupb.QotUpdateOrderBookResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_UpdateOrderBook_proto_rawDescOnce sync.Once
	file_Qot_UpdateOrderBook_proto_rawDescData []byte
)

func file_Qot_UpdateOrderBook_proto_rawDescGZIP() []byte {
	file_Qot_UpdateOrderBook_proto_rawDescOnce.Do(func() {
		file_Qot_UpdateOrderBook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_UpdateOrderBook_proto_rawDesc), len(file_Qot_UpdateOrderBook_proto_rawDesc)))
	})
	return file_Qot_UpdateOrderBook_proto_rawDescData
}

var file_Qot_UpdateOrderBook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Qot_UpdateOrderBook_proto_goTypes = []any{
	(*QotUpdateOrderBookResponse)(nil),          // 0: futupb.QotUpdateOrderBookResponse
	(*QotUpdateOrderBookResponse_Internal)(nil), // 1: futupb.QotUpdateOrderBookResponse_Internal
	(*Security)(nil),                            // 2: futupb.Security
	(*OrderBook)(nil),                           // 3: futupb.OrderBook
	(RetType)(0),                                // 4: futupb.RetType
}
var file_Qot_UpdateOrderBook_proto_depIdxs = []int32{
	2, // 0: futupb.QotUpdateOrderBookResponse.security:type_name -> futupb.Security
	3, // 1: futupb.QotUpdateOrderBookResponse.orderBookAskList:type_name -> futupb.OrderBook
	3, // 2: futupb.QotUpdateOrderBookResponse.orderBookBidList:type_name -> futupb.OrderBook
	4, // 3: futupb.QotUpdateOrderBookResponse_Internal.retType:type_name -> futupb.RetType
	0, // 4: futupb.QotUpdateOrderBookResponse_Internal.payload:type_name -> futupb.QotUpdateOrderBookResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Qot_UpdateOrderBook_proto_init() }
func file_Qot_UpdateOrderBook_proto_init() {
	if File_Qot_UpdateOrderBook_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_UpdateOrderBook_proto_rawDesc), len(file_Qot_UpdateOrderBook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_UpdateOrderBook_proto_goTypes,
		DependencyIndexes: file_Qot_UpdateOrderBook_proto_depIdxs,
		MessageInfos:      file_Qot_UpdateOrderBook_proto_msgTypes,
	}.Build()
	File_Qot_UpdateOrderBook_proto = out.File
	file_Qot_UpdateOrderBook_proto_goTypes = nil
	file_Qot_UpdateOrderBook_proto_depIdxs = nil
}
