// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Qot_GetCorporateActionsDividends.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分红派息单条记录
type DividendItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PubDate             *string                `protobuf:"bytes,1,opt,name=pubDate" json:"pubDate,omitempty"`                         // 公告日，格式 YYYY/MM/DD，对应市场时区
	Statement           *string                `protobuf:"bytes,2,opt,name=statement" json:"statement,omitempty"`                     // 分配方案描述，如"末期息5.3港元"
	Process             *string                `protobuf:"bytes,3,opt,name=process" json:"process,omitempty"`                         // 事件进展，如"方案实施"/"预案"；仅港股和A股的正股与信托有值
	RecordDate          *string                `protobuf:"bytes,4,opt,name=recordDate" json:"recordDate,omitempty"`                   // 股权登记日，格式 YYYY/MM/DD，对应市场时区。ETF无此数据
	ExDate              *string                `protobuf:"bytes,5,opt,name=exDate" json:"exDate,omitempty"`                           // 除权除息日，格式 YYYY/MM/DD，对应市场时区
	DividendPayableDate *string                `protobuf:"bytes,6,opt,name=dividendPayableDate" json:"dividendPayableDate,omitempty"` // 派息日，格式 YYYY/MM/DD，对应市场时区
	FiscalYear          *string                `protobuf:"bytes,7,opt,name=fiscalYear" json:"fiscalYear,omitempty"`                   // 财政年度,如“2026”。仅ETF有值。
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DividendItem) Reset() {
	*x = DividendItem{}
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DividendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DividendItem) ProtoMessage() {}

func (x *DividendItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DividendItem.ProtoReflect.Descriptor instead.
func (*DividendItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP(), []int{0}
}

func (x *DividendItem) GetPubDate() string {
	if x != nil && x.PubDate != nil {
		return *x.PubDate
	}
	return ""
}

func (x *DividendItem) GetStatement() string {
	if x != nil && x.Statement != nil {
		return *x.Statement
	}
	return ""
}

func (x *DividendItem) GetProcess() string {
	if x != nil && x.Process != nil {
		return *x.Process
	}
	return ""
}

func (x *DividendItem) GetRecordDate() string {
	if x != nil && x.RecordDate != nil {
		return *x.RecordDate
	}
	return ""
}

func (x *DividendItem) GetExDate() string {
	if x != nil && x.ExDate != nil {
		return *x.ExDate
	}
	return ""
}

func (x *DividendItem) GetDividendPayableDate() string {
	if x != nil && x.DividendPayableDate != nil {
		return *x.DividendPayableDate
	}
	return ""
}

func (x *DividendItem) GetFiscalYear() string {
	if x != nil && x.FiscalYear != nil {
		return *x.FiscalYear
	}
	return ""
}

type QotGetCorporateActionsDividendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"` // 股票
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetCorporateActionsDividendsRequest) Reset() {
	*x = QotGetCorporateActionsDividendsRequest{}
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCorporateActionsDividendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCorporateActionsDividendsRequest) ProtoMessage() {}

func (x *QotGetCorporateActionsDividendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCorporateActionsDividendsRequest.ProtoReflect.Descriptor instead.
func (*QotGetCorporateActionsDividendsRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP(), []int{1}
}

func (x *QotGetCorporateActionsDividendsRequest) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

type QotGetCorporateActionsDividendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DividendList  []*DividendItem        `protobuf:"bytes,1,rep,name=dividendList" json:"dividendList,omitempty"` // 分红派息列表，按公告日倒序排列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetCorporateActionsDividendsResponse) Reset() {
	*x = QotGetCorporateActionsDividendsResponse{}
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCorporateActionsDividendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCorporateActionsDividendsResponse) ProtoMessage() {}

func (x *QotGetCorporateActionsDividendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCorporateActionsDividendsResponse.ProtoReflect.Descriptor instead.
func (*QotGetCorporateActionsDividendsResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP(), []int{2}
}

func (x *QotGetCorporateActionsDividendsResponse) GetDividendList() []*DividendItem {
	if x != nil {
		return x.DividendList
	}
	return nil
}

type QotGetCorporateActionsDividendsRequest_Internal struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Payload       *QotGetCorporateActionsDividendsRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetCorporateActionsDividendsRequest_Internal) Reset() {
	*x = QotGetCorporateActionsDividendsRequest_Internal{}
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCorporateActionsDividendsRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCorporateActionsDividendsRequest_Internal) ProtoMessage() {}

func (x *QotGetCorporateActionsDividendsRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCorporateActionsDividendsRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetCorporateActionsDividendsRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetCorporateActionsDividendsRequest_Internal) GetPayload() *QotGetCorporateActionsDividendsRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetCorporateActionsDividendsResponse_Internal struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	RetType       *RetType                                 `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                                  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                                   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetCorporateActionsDividendsResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetCorporateActionsDividendsResponse_Internal fields.
const (
	Default_QotGetCorporateActionsDividendsResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetCorporateActionsDividendsResponse_Internal) Reset() {
	*x = QotGetCorporateActionsDividendsResponse_Internal{}
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCorporateActionsDividendsResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCorporateActionsDividendsResponse_Internal) ProtoMessage() {}

func (x *QotGetCorporateActionsDividendsResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCorporateActionsDividends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCorporateActionsDividendsResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetCorporateActionsDividendsResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetCorporateActionsDividendsResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetCorporateActionsDividendsResponse_Internal_RetType
}

func (x *QotGetCorporateActionsDividendsResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetCorporateActionsDividendsResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetCorporateActionsDividendsResponse_Internal) GetPayload() *QotGetCorporateActionsDividendsResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetCorporateActionsDividends_proto protoreflect.FileDescriptor

const file_Qot_GetCorporateActionsDividends_proto_rawDesc = "" +
	"\n" +
	"&Qot_GetCorporateActionsDividends.proto\x12\x06futupb\x1a\vTypes.proto\"\xea\x01\n" +
	"\fDividendItem\x12\x18\n" +
	"\apubDate\x18\x01 \x01(\tR\apubDate\x12\x1c\n" +
	"\tstatement\x18\x02 \x01(\tR\tstatement\x12\x18\n" +
	"\aprocess\x18\x03 \x01(\tR\aprocess\x12\x1e\n" +
	"\n" +
	"recordDate\x18\x04 \x01(\tR\n" +
	"recordDate\x12\x16\n" +
	"\x06exDate\x18\x05 \x01(\tR\x06exDate\x120\n" +
	"\x13dividendPayableDate\x18\x06 \x01(\tR\x13dividendPayableDate\x12\x1e\n" +
	"\n" +
	"fiscalYear\x18\a \x01(\tR\n" +
	"fiscalYear\"V\n" +
	"&QotGetCorporateActionsDividendsRequest\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\"c\n" +
	"'QotGetCorporateActionsDividendsResponse\x128\n" +
	"\fdividendList\x18\x01 \x03(\v2\x14.futupb.DividendItemR\fdividendList\"{\n" +
	"/QotGetCorporateActionsDividendsRequest_Internal\x12H\n" +
	"\apayload\x18\x01 \x02(\v2..futupb.QotGetCorporateActionsDividendsRequestR\apayload\"\xeb\x01\n" +
	"0QotGetCorporateActionsDividendsResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12I\n" +
	"\apayload\x18\x04 \x01(\v2/.futupb.QotGetCorporateActionsDividendsResponseR\apayloadB\x1fZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetCorporateActionsDividends_proto_rawDescOnce sync.Once
	file_Qot_GetCorporateActionsDividends_proto_rawDescData []byte
)

func file_Qot_GetCorporateActionsDividends_proto_rawDescGZIP() []byte {
	file_Qot_GetCorporateActionsDividends_proto_rawDescOnce.Do(func() {
		file_Qot_GetCorporateActionsDividends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetCorporateActionsDividends_proto_rawDesc), len(file_Qot_GetCorporateActionsDividends_proto_rawDesc)))
	})
	return file_Qot_GetCorporateActionsDividends_proto_rawDescData
}

var file_Qot_GetCorporateActionsDividends_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetCorporateActionsDividends_proto_goTypes = []any{
	(*DividendItem)(nil),                                     // 0: futupb.DividendItem
	(*QotGetCorporateActionsDividendsRequest)(nil),           // 1: futupb.QotGetCorporateActionsDividendsRequest
	(*QotGetCorporateActionsDividendsResponse)(nil),          // 2: futupb.QotGetCorporateActionsDividendsResponse
	(*QotGetCorporateActionsDividendsRequest_Internal)(nil),  // 3: futupb.QotGetCorporateActionsDividendsRequest_Internal
	(*QotGetCorporateActionsDividendsResponse_Internal)(nil), // 4: futupb.QotGetCorporateActionsDividendsResponse_Internal
	(*Security)(nil), // 5: futupb.Security
	(RetType)(0),     // 6: futupb.RetType
}
var file_Qot_GetCorporateActionsDividends_proto_depIdxs = []int32{
	5, // 0: futupb.QotGetCorporateActionsDividendsRequest.security:type_name -> futupb.Security
	0, // 1: futupb.QotGetCorporateActionsDividendsResponse.dividendList:type_name -> futupb.DividendItem
	1, // 2: futupb.QotGetCorporateActionsDividendsRequest_Internal.payload:type_name -> futupb.QotGetCorporateActionsDividendsRequest
	6, // 3: futupb.QotGetCorporateActionsDividendsResponse_Internal.retType:type_name -> futupb.RetType
	2, // 4: futupb.QotGetCorporateActionsDividendsResponse_Internal.payload:type_name -> futupb.QotGetCorporateActionsDividendsResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Qot_GetCorporateActionsDividends_proto_init() }
func file_Qot_GetCorporateActionsDividends_proto_init() {
	if File_Qot_GetCorporateActionsDividends_proto != nil {
		return
	}
	file_Types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetCorporateActionsDividends_proto_rawDesc), len(file_Qot_GetCorporateActionsDividends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetCorporateActionsDividends_proto_goTypes,
		DependencyIndexes: file_Qot_GetCorporateActionsDividends_proto_depIdxs,
		MessageInfos:      file_Qot_GetCorporateActionsDividends_proto_msgTypes,
	}.Build()
	File_Qot_GetCorporateActionsDividends_proto = out.File
	file_Qot_GetCorporateActionsDividends_proto_goTypes = nil
	file_Qot_GetCorporateActionsDividends_proto_depIdxs = nil
}
