// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Qot_GetCompanyExecutiveBackground.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotGetCompanyExecutiveBackgroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`     // 股票
	LeaderName    *string                `protobuf:"bytes,2,opt,name=leaderName" json:"leaderName,omitempty"` // 高管姓名（使用GetCompanyExecutives返回的leaderName字段）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetCompanyExecutiveBackgroundRequest) Reset() {
	*x = QotGetCompanyExecutiveBackgroundRequest{}
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCompanyExecutiveBackgroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCompanyExecutiveBackgroundRequest) ProtoMessage() {}

func (x *QotGetCompanyExecutiveBackgroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCompanyExecutiveBackgroundRequest.ProtoReflect.Descriptor instead.
func (*QotGetCompanyExecutiveBackgroundRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetCompanyExecutiveBackground_proto_rawDescGZIP(), []int{0}
}

func (x *QotGetCompanyExecutiveBackgroundRequest) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotGetCompanyExecutiveBackgroundRequest) GetLeaderName() string {
	if x != nil && x.LeaderName != nil {
		return *x.LeaderName
	}
	return ""
}

type QotGetCompanyExecutiveBackgroundResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BriefBackground *string                `protobuf:"bytes,1,opt,name=briefBackground" json:"briefBackground,omitempty"` // 高管背景简介
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QotGetCompanyExecutiveBackgroundResponse) Reset() {
	*x = QotGetCompanyExecutiveBackgroundResponse{}
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCompanyExecutiveBackgroundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCompanyExecutiveBackgroundResponse) ProtoMessage() {}

func (x *QotGetCompanyExecutiveBackgroundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCompanyExecutiveBackgroundResponse.ProtoReflect.Descriptor instead.
func (*QotGetCompanyExecutiveBackgroundResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetCompanyExecutiveBackground_proto_rawDescGZIP(), []int{1}
}

func (x *QotGetCompanyExecutiveBackgroundResponse) GetBriefBackground() string {
	if x != nil && x.BriefBackground != nil {
		return *x.BriefBackground
	}
	return ""
}

type QotGetCompanyExecutiveBackgroundRequest_Internal struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Payload       *QotGetCompanyExecutiveBackgroundRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetCompanyExecutiveBackgroundRequest_Internal) Reset() {
	*x = QotGetCompanyExecutiveBackgroundRequest_Internal{}
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCompanyExecutiveBackgroundRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCompanyExecutiveBackgroundRequest_Internal) ProtoMessage() {}

func (x *QotGetCompanyExecutiveBackgroundRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCompanyExecutiveBackgroundRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetCompanyExecutiveBackgroundRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetCompanyExecutiveBackground_proto_rawDescGZIP(), []int{2}
}

func (x *QotGetCompanyExecutiveBackgroundRequest_Internal) GetPayload() *QotGetCompanyExecutiveBackgroundRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetCompanyExecutiveBackgroundResponse_Internal struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	RetType       *RetType                                  `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                                   `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                                    `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetCompanyExecutiveBackgroundResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetCompanyExecutiveBackgroundResponse_Internal fields.
const (
	Default_QotGetCompanyExecutiveBackgroundResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) Reset() {
	*x = QotGetCompanyExecutiveBackgroundResponse_Internal{}
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetCompanyExecutiveBackgroundResponse_Internal) ProtoMessage() {}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCompanyExecutiveBackground_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetCompanyExecutiveBackgroundResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetCompanyExecutiveBackgroundResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetCompanyExecutiveBackground_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetCompanyExecutiveBackgroundResponse_Internal_RetType
}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetCompanyExecutiveBackgroundResponse_Internal) GetPayload() *QotGetCompanyExecutiveBackgroundResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetCompanyExecutiveBackground_proto protoreflect.FileDescriptor

const file_Qot_GetCompanyExecutiveBackground_proto_rawDesc = "" +
	"\n" +
	"'Qot_GetCompanyExecutiveBackground.proto\x12\x06futupb\x1a\vTypes.proto\"w\n" +
	"'QotGetCompanyExecutiveBackgroundRequest\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x1e\n" +
	"\n" +
	"leaderName\x18\x02 \x01(\tR\n" +
	"leaderName\"T\n" +
	"(QotGetCompanyExecutiveBackgroundResponse\x12(\n" +
	"\x0fbriefBackground\x18\x01 \x01(\tR\x0fbriefBackground\"}\n" +
	"0QotGetCompanyExecutiveBackgroundRequest_Internal\x12I\n" +
	"\apayload\x18\x01 \x02(\v2/.futupb.QotGetCompanyExecutiveBackgroundRequestR\apayload\"\xed\x01\n" +
	"1QotGetCompanyExecutiveBackgroundResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12J\n" +
	"\apayload\x18\x04 \x01(\v20.futupb.QotGetCompanyExecutiveBackgroundResponseR\apayloadB\x1fZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetCompanyExecutiveBackground_proto_rawDescOnce sync.Once
	file_Qot_GetCompanyExecutiveBackground_proto_rawDescData []byte
)

func file_Qot_GetCompanyExecutiveBackground_proto_rawDescGZIP() []byte {
	file_Qot_GetCompanyExecutiveBackground_proto_rawDescOnce.Do(func() {
		file_Qot_GetCompanyExecutiveBackground_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetCompanyExecutiveBackground_proto_rawDesc), len(file_Qot_GetCompanyExecutiveBackground_proto_rawDesc)))
	})
	return file_Qot_GetCompanyExecutiveBackground_proto_rawDescData
}

var file_Qot_GetCompanyExecutiveBackground_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_GetCompanyExecutiveBackground_proto_goTypes = []any{
	(*QotGetCompanyExecutiveBackgroundRequest)(nil),           // 0: futupb.QotGetCompanyExecutiveBackgroundRequest
	(*QotGetCompanyExecutiveBackgroundResponse)(nil),          // 1: futupb.QotGetCompanyExecutiveBackgroundResponse
	(*QotGetCompanyExecutiveBackgroundRequest_Internal)(nil),  // 2: futupb.QotGetCompanyExecutiveBackgroundRequest_Internal
	(*QotGetCompanyExecutiveBackgroundResponse_Internal)(nil), // 3: futupb.QotGetCompanyExecutiveBackgroundResponse_Internal
	(*Security)(nil), // 4: futupb.Security
	(RetType)(0),     // 5: futupb.RetType
}
var file_Qot_GetCompanyExecutiveBackground_proto_depIdxs = []int32{
	4, // 0: futupb.QotGetCompanyExecutiveBackgroundRequest.security:type_name -> futupb.Security
	0, // 1: futupb.QotGetCompanyExecutiveBackgroundRequest_Internal.payload:type_name -> futupb.QotGetCompanyExecutiveBackgroundRequest
	5, // 2: futupb.QotGetCompanyExecutiveBackgroundResponse_Internal.retType:type_name -> futupb.RetType
	1, // 3: futupb.QotGetCompanyExecutiveBackgroundResponse_Internal.payload:type_name -> futupb.QotGetCompanyExecutiveBackgroundResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Qot_GetCompanyExecutiveBackground_proto_init() }
func file_Qot_GetCompanyExecutiveBackground_proto_init() {
	if File_Qot_GetCompanyExecutiveBackground_proto != nil {
		return
	}
	file_Types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetCompanyExecutiveBackground_proto_rawDesc), len(file_Qot_GetCompanyExecutiveBackground_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetCompanyExecutiveBackground_proto_goTypes,
		DependencyIndexes: file_Qot_GetCompanyExecutiveBackground_proto_depIdxs,
		MessageInfos:      file_Qot_GetCompanyExecutiveBackground_proto_msgTypes,
	}.Build()
	File_Qot_GetCompanyExecutiveBackground_proto = out.File
	file_Qot_GetCompanyExecutiveBackground_proto_goTypes = nil
	file_Qot_GetCompanyExecutiveBackground_proto_depIdxs = nil
}
