// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Qot_RequestHistoryKL.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotRequestHistoryKLRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RehabType        *int32                 `protobuf:"varint,1,req,name=rehabType" json:"rehabType,omitempty"`               //Qot_Common.RehabType,复权类型
	KlType           *int32                 `protobuf:"varint,2,req,name=klType" json:"klType,omitempty"`                     //Qot_Common.KLType,K线类型
	Security         *Security              `protobuf:"bytes,3,req,name=security" json:"security,omitempty"`                  //股票市场以及股票代码
	BeginTime        *string                `protobuf:"bytes,4,req,name=beginTime" json:"beginTime,omitempty"`                //开始时间字符串
	EndTime          *string                `protobuf:"bytes,5,req,name=endTime" json:"endTime,omitempty"`                    //结束时间字符串
	MaxAckKLNum      *int32                 `protobuf:"varint,6,opt,name=maxAckKLNum" json:"maxAckKLNum,omitempty"`           //最多返回多少根K线，如果未指定表示不限制
	NeedKLFieldsFlag *int64                 `protobuf:"varint,7,opt,name=needKLFieldsFlag" json:"needKLFieldsFlag,omitempty"` //指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
	NextReqKey       []byte                 `protobuf:"bytes,8,opt,name=nextReqKey" json:"nextReqKey,omitempty"`              //分页请求key
	ExtendedTime     *bool                  `protobuf:"varint,9,opt,name=extendedTime" json:"extendedTime,omitempty"`         //是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
	Session          *int32                 `protobuf:"varint,10,opt,name=session" json:"session,omitempty"`                  //Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QotRequestHistoryKLRequest) Reset() {
	*x = QotRequestHistoryKLRequest{}
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotRequestHistoryKLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotRequestHistoryKLRequest) ProtoMessage() {}

func (x *QotRequestHistoryKLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotRequestHistoryKLRequest.ProtoReflect.Descriptor instead.
func (*QotRequestHistoryKLRequest) Descriptor() ([]byte, []int) {
	return file_Qot_RequestHistoryKL_proto_rawDescGZIP(), []int{0}
}

func (x *QotRequestHistoryKLRequest) GetRehabType() int32 {
	if x != nil && x.RehabType != nil {
		return *x.RehabType
	}
	return 0
}

func (x *QotRequestHistoryKLRequest) GetKlType() int32 {
	if x != nil && x.KlType != nil {
		return *x.KlType
	}
	return 0
}

func (x *QotRequestHistoryKLRequest) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotRequestHistoryKLRequest) GetBeginTime() string {
	if x != nil && x.BeginTime != nil {
		return *x.BeginTime
	}
	return ""
}

func (x *QotRequestHistoryKLRequest) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

func (x *QotRequestHistoryKLRequest) GetMaxAckKLNum() int32 {
	if x != nil && x.MaxAckKLNum != nil {
		return *x.MaxAckKLNum
	}
	return 0
}

func (x *QotRequestHistoryKLRequest) GetNeedKLFieldsFlag() int64 {
	if x != nil && x.NeedKLFieldsFlag != nil {
		return *x.NeedKLFieldsFlag
	}
	return 0
}

func (x *QotRequestHistoryKLRequest) GetNextReqKey() []byte {
	if x != nil {
		return x.NextReqKey
	}
	return nil
}

func (x *QotRequestHistoryKLRequest) GetExtendedTime() bool {
	if x != nil && x.ExtendedTime != nil {
		return *x.ExtendedTime
	}
	return false
}

func (x *QotRequestHistoryKLRequest) GetSession() int32 {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return 0
}

type QotRequestHistoryKLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`             // 股票名称
	KlList        []*KLine               `protobuf:"bytes,2,rep,name=klList" json:"klList,omitempty"`         //K线数据
	NextReqKey    []byte                 `protobuf:"bytes,3,opt,name=nextReqKey" json:"nextReqKey,omitempty"` //分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotRequestHistoryKLResponse) Reset() {
	*x = QotRequestHistoryKLResponse{}
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotRequestHistoryKLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotRequestHistoryKLResponse) ProtoMessage() {}

func (x *QotRequestHistoryKLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotRequestHistoryKLResponse.ProtoReflect.Descriptor instead.
func (*QotRequestHistoryKLResponse) Descriptor() ([]byte, []int) {
	return file_Qot_RequestHistoryKL_proto_rawDescGZIP(), []int{1}
}

func (x *QotRequestHistoryKLResponse) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotRequestHistoryKLResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QotRequestHistoryKLResponse) GetKlList() []*KLine {
	if x != nil {
		return x.KlList
	}
	return nil
}

func (x *QotRequestHistoryKLResponse) GetNextReqKey() []byte {
	if x != nil {
		return x.NextReqKey
	}
	return nil
}

type QotRequestHistoryKLRequest_Internal struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Payload       *QotRequestHistoryKLRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotRequestHistoryKLRequest_Internal) Reset() {
	*x = QotRequestHistoryKLRequest_Internal{}
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotRequestHistoryKLRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotRequestHistoryKLRequest_Internal) ProtoMessage() {}

func (x *QotRequestHistoryKLRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotRequestHistoryKLRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotRequestHistoryKLRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_RequestHistoryKL_proto_rawDescGZIP(), []int{2}
}

func (x *QotRequestHistoryKLRequest_Internal) GetPayload() *QotRequestHistoryKLRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotRequestHistoryKLResponse_Internal struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	RetType       *int32                       `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                      `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                       `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotRequestHistoryKLResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotRequestHistoryKLResponse_Internal fields.
const (
	Default_QotRequestHistoryKLResponse_Internal_RetType = int32(-400)
)

func (x *QotRequestHistoryKLResponse_Internal) Reset() {
	*x = QotRequestHistoryKLResponse_Internal{}
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotRequestHistoryKLResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotRequestHistoryKLResponse_Internal) ProtoMessage() {}

func (x *QotRequestHistoryKLResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RequestHistoryKL_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotRequestHistoryKLResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotRequestHistoryKLResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_RequestHistoryKL_proto_rawDescGZIP(), []int{3}
}

func (x *QotRequestHistoryKLResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotRequestHistoryKLResponse_Internal_RetType
}

func (x *QotRequestHistoryKLResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotRequestHistoryKLResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotRequestHistoryKLResponse_Internal) GetPayload() *QotRequestHistoryKLResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_RequestHistoryKL_proto protoreflect.FileDescriptor

const file_Qot_RequestHistoryKL_proto_rawDesc = "" +
	"\n" +
	"\x1aQot_RequestHistoryKL.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xe4\x02\n" +
	"\x1aQotRequestHistoryKLRequest\x12\x1c\n" +
	"\trehabType\x18\x01 \x02(\x05R\trehabType\x12\x16\n" +
	"\x06klType\x18\x02 \x02(\x05R\x06klType\x12,\n" +
	"\bsecurity\x18\x03 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x1c\n" +
	"\tbeginTime\x18\x04 \x02(\tR\tbeginTime\x12\x18\n" +
	"\aendTime\x18\x05 \x02(\tR\aendTime\x12 \n" +
	"\vmaxAckKLNum\x18\x06 \x01(\x05R\vmaxAckKLNum\x12*\n" +
	"\x10needKLFieldsFlag\x18\a \x01(\x03R\x10needKLFieldsFlag\x12\x1e\n" +
	"\n" +
	"nextReqKey\x18\b \x01(\fR\n" +
	"nextReqKey\x12\"\n" +
	"\fextendedTime\x18\t \x01(\bR\fextendedTime\x12\x18\n" +
	"\asession\x18\n" +
	" \x01(\x05R\asession\"\xa6\x01\n" +
	"\x1bQotRequestHistoryKLResponse\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x06klList\x18\x02 \x03(\v2\r.futupb.KLineR\x06klList\x12\x1e\n" +
	"\n" +
	"nextReqKey\x18\x03 \x01(\fR\n" +
	"nextReqKey\"c\n" +
	"#QotRequestHistoryKLRequest_Internal\x12<\n" +
	"\apayload\x18\x01 \x02(\v2\".futupb.QotRequestHistoryKLRequestR\apayload\"\xb7\x01\n" +
	"$QotRequestHistoryKLResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12=\n" +
	"\apayload\x18\x04 \x01(\v2#.futupb.QotRequestHistoryKLResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_RequestHistoryKL_proto_rawDescOnce sync.Once
	file_Qot_RequestHistoryKL_proto_rawDescData []byte
)

func file_Qot_RequestHistoryKL_proto_rawDescGZIP() []byte {
	file_Qot_RequestHistoryKL_proto_rawDescOnce.Do(func() {
		file_Qot_RequestHistoryKL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_RequestHistoryKL_proto_rawDesc), len(file_Qot_RequestHistoryKL_proto_rawDesc)))
	})
	return file_Qot_RequestHistoryKL_proto_rawDescData
}

var file_Qot_RequestHistoryKL_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_RequestHistoryKL_proto_goTypes = []any{
	(*QotRequestHistoryKLRequest)(nil),           // 0: futupb.QotRequestHistoryKLRequest
	(*QotRequestHistoryKLResponse)(nil),          // 1: futupb.QotRequestHistoryKLResponse
	(*QotRequestHistoryKLRequest_Internal)(nil),  // 2: futupb.QotRequestHistoryKLRequest_Internal
	(*QotRequestHistoryKLResponse_Internal)(nil), // 3: futupb.QotRequestHistoryKLResponse_Internal
	(*Security)(nil),                             // 4: futupb.Security
	(*KLine)(nil),                                // 5: futupb.KLine
}
var file_Qot_RequestHistoryKL_proto_depIdxs = []int32{
	4, // 0: futupb.QotRequestHistoryKLRequest.security:type_name -> futupb.Security
	4, // 1: futupb.QotRequestHistoryKLResponse.security:type_name -> futupb.Security
	5, // 2: futupb.QotRequestHistoryKLResponse.klList:type_name -> futupb.KLine
	0, // 3: futupb.QotRequestHistoryKLRequest_Internal.payload:type_name -> futupb.QotRequestHistoryKLRequest
	1, // 4: futupb.QotRequestHistoryKLResponse_Internal.payload:type_name -> futupb.QotRequestHistoryKLResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Qot_RequestHistoryKL_proto_init() }
func file_Qot_RequestHistoryKL_proto_init() {
	if File_Qot_RequestHistoryKL_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_RequestHistoryKL_proto_rawDesc), len(file_Qot_RequestHistoryKL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_RequestHistoryKL_proto_goTypes,
		DependencyIndexes: file_Qot_RequestHistoryKL_proto_depIdxs,
		MessageInfos:      file_Qot_RequestHistoryKL_proto_msgTypes,
	}.Build()
	File_Qot_RequestHistoryKL_proto = out.File
	file_Qot_RequestHistoryKL_proto_goTypes = nil
	file_Qot_RequestHistoryKL_proto_depIdxs = nil
}
