// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Qot_GetHistoryKLPoints.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 当请求时间点数据为空时，如何返回数据
type NoDataMode int32

const (
	NoDataMode_NoDataMode_Null     NoDataMode = 0 //直接返回空数据
	NoDataMode_NoDataMode_Forward  NoDataMode = 1 //往前取值，返回前一个时间点数据
	NoDataMode_NoDataMode_Backward NoDataMode = 2 //向后取值，返回后一个时间点数据
)

// Enum value maps for NoDataMode.
var (
	NoDataMode_name = map[int32]string{
		0: "NoDataMode_Null",
		1: "NoDataMode_Forward",
		2: "NoDataMode_Backward",
	}
	NoDataMode_value = map[string]int32{
		"NoDataMode_Null":     0,
		"NoDataMode_Forward":  1,
		"NoDataMode_Backward": 2,
	}
)

func (x NoDataMode) Enum() *NoDataMode {
	p := new(NoDataMode)
	*p = x
	return p
}

func (x NoDataMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoDataMode) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetHistoryKLPoints_proto_enumTypes[0].Descriptor()
}

func (NoDataMode) Type() protoreflect.EnumType {
	return &file_Qot_GetHistoryKLPoints_proto_enumTypes[0]
}

func (x NoDataMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NoDataMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NoDataMode(num)
	return nil
}

// Deprecated: Use NoDataMode.Descriptor instead.
func (NoDataMode) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{0}
}

// 这个时间点返回数据的状态以及来源
type DataStatus int32

const (
	DataStatus_DataStatus_Null     DataStatus = 0 //空数据
	DataStatus_DataStatus_Current  DataStatus = 1 //当前时间点数据
	DataStatus_DataStatus_Previous DataStatus = 2 //前一个时间点数据
	DataStatus_DataStatus_Back     DataStatus = 3 //后一个时间点数据
)

// Enum value maps for DataStatus.
var (
	DataStatus_name = map[int32]string{
		0: "DataStatus_Null",
		1: "DataStatus_Current",
		2: "DataStatus_Previous",
		3: "DataStatus_Back",
	}
	DataStatus_value = map[string]int32{
		"DataStatus_Null":     0,
		"DataStatus_Current":  1,
		"DataStatus_Previous": 2,
		"DataStatus_Back":     3,
	}
)

func (x DataStatus) Enum() *DataStatus {
	p := new(DataStatus)
	*p = x
	return p
}

func (x DataStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetHistoryKLPoints_proto_enumTypes[1].Descriptor()
}

func (DataStatus) Type() protoreflect.EnumType {
	return &file_Qot_GetHistoryKLPoints_proto_enumTypes[1]
}

func (x DataStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DataStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DataStatus(num)
	return nil
}

// Deprecated: Use DataStatus.Descriptor instead.
func (DataStatus) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{1}
}

type QotGetHistoryKLPointsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RehabType         *RehabType             `protobuf:"varint,1,req,name=rehabType,enum=futupb.RehabType" json:"rehabType,omitempty"`    //Qot_Common.RehabType,复权类型
	KlType            *KLType                `protobuf:"varint,2,req,name=klType,enum=futupb.KLType" json:"klType,omitempty"`             //Qot_Common.KLType,K线类型
	NoDataMode        *NoDataMode            `protobuf:"varint,3,req,name=noDataMode,enum=futupb.NoDataMode" json:"noDataMode,omitempty"` //NoDataMode,当请求时间点数据为空时，如何返回数据
	SecurityList      []*Security            `protobuf:"bytes,4,rep,name=securityList" json:"securityList,omitempty"`                     //股票市场以及股票代码
	TimeList          []string               `protobuf:"bytes,5,rep,name=timeList" json:"timeList,omitempty"`                             //时间字符串
	MaxReqSecurityNum *int32                 `protobuf:"varint,6,opt,name=maxReqSecurityNum" json:"maxReqSecurityNum,omitempty"`          //最多返回多少只股票的数据，如果未指定表示不限制
	NeedKLFieldsFlag  *int64                 `protobuf:"varint,7,opt,name=needKLFieldsFlag" json:"needKLFieldsFlag,omitempty"`            //指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QotGetHistoryKLPointsRequest) Reset() {
	*x = QotGetHistoryKLPointsRequest{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetHistoryKLPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetHistoryKLPointsRequest) ProtoMessage() {}

func (x *QotGetHistoryKLPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetHistoryKLPointsRequest.ProtoReflect.Descriptor instead.
func (*QotGetHistoryKLPointsRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{0}
}

func (x *QotGetHistoryKLPointsRequest) GetRehabType() RehabType {
	if x != nil && x.RehabType != nil {
		return *x.RehabType
	}
	return RehabType_RehabType_None
}

func (x *QotGetHistoryKLPointsRequest) GetKlType() KLType {
	if x != nil && x.KlType != nil {
		return *x.KlType
	}
	return KLType_KLType_Unknown
}

func (x *QotGetHistoryKLPointsRequest) GetNoDataMode() NoDataMode {
	if x != nil && x.NoDataMode != nil {
		return *x.NoDataMode
	}
	return NoDataMode_NoDataMode_Null
}

func (x *QotGetHistoryKLPointsRequest) GetSecurityList() []*Security {
	if x != nil {
		return x.SecurityList
	}
	return nil
}

func (x *QotGetHistoryKLPointsRequest) GetTimeList() []string {
	if x != nil {
		return x.TimeList
	}
	return nil
}

func (x *QotGetHistoryKLPointsRequest) GetMaxReqSecurityNum() int32 {
	if x != nil && x.MaxReqSecurityNum != nil {
		return *x.MaxReqSecurityNum
	}
	return 0
}

func (x *QotGetHistoryKLPointsRequest) GetNeedKLFieldsFlag() int64 {
	if x != nil && x.NeedKLFieldsFlag != nil {
		return *x.NeedKLFieldsFlag
	}
	return 0
}

type HistoryPointsKL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *DataStatus            `protobuf:"varint,1,req,name=status,enum=futupb.DataStatus" json:"status,omitempty"` //DataStatus,数据状态
	ReqTime       *string                `protobuf:"bytes,2,req,name=reqTime" json:"reqTime,omitempty"`                       //请求的时间
	Kl            *KLine                 `protobuf:"bytes,3,req,name=kl" json:"kl,omitempty"`                                 //K线数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryPointsKL) Reset() {
	*x = HistoryPointsKL{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryPointsKL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPointsKL) ProtoMessage() {}

func (x *HistoryPointsKL) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPointsKL.ProtoReflect.Descriptor instead.
func (*HistoryPointsKL) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryPointsKL) GetStatus() DataStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DataStatus_DataStatus_Null
}

func (x *HistoryPointsKL) GetReqTime() string {
	if x != nil && x.ReqTime != nil {
		return *x.ReqTime
	}
	return ""
}

func (x *HistoryPointsKL) GetKl() *KLine {
	if x != nil {
		return x.Kl
	}
	return nil
}

type SecurityHistoryKLPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"` //股票
	KlList        []*HistoryPointsKL     `protobuf:"bytes,2,rep,name=klList" json:"klList,omitempty"`     //K线数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityHistoryKLPoints) Reset() {
	*x = SecurityHistoryKLPoints{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityHistoryKLPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityHistoryKLPoints) ProtoMessage() {}

func (x *SecurityHistoryKLPoints) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityHistoryKLPoints.ProtoReflect.Descriptor instead.
func (*SecurityHistoryKLPoints) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityHistoryKLPoints) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *SecurityHistoryKLPoints) GetKlList() []*HistoryPointsKL {
	if x != nil {
		return x.KlList
	}
	return nil
}

type QotGetHistoryKLPointsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	KlPointList   []*SecurityHistoryKLPoints `protobuf:"bytes,1,rep,name=klPointList" json:"klPointList,omitempty"` //多只股票的多点历史K线点
	HasNext       *bool                      `protobuf:"varint,2,opt,name=hasNext" json:"hasNext,omitempty"`        //如请求不指定maxReqSecurityNum值，则不会返回该字段，该字段表示请求是否还有超过指定限制的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetHistoryKLPointsResponse) Reset() {
	*x = QotGetHistoryKLPointsResponse{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetHistoryKLPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetHistoryKLPointsResponse) ProtoMessage() {}

func (x *QotGetHistoryKLPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetHistoryKLPointsResponse.ProtoReflect.Descriptor instead.
func (*QotGetHistoryKLPointsResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetHistoryKLPointsResponse) GetKlPointList() []*SecurityHistoryKLPoints {
	if x != nil {
		return x.KlPointList
	}
	return nil
}

func (x *QotGetHistoryKLPointsResponse) GetHasNext() bool {
	if x != nil && x.HasNext != nil {
		return *x.HasNext
	}
	return false
}

type QotGetHistoryKLPointsRequest_Internal struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Payload       *QotGetHistoryKLPointsRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetHistoryKLPointsRequest_Internal) Reset() {
	*x = QotGetHistoryKLPointsRequest_Internal{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetHistoryKLPointsRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetHistoryKLPointsRequest_Internal) ProtoMessage() {}

func (x *QotGetHistoryKLPointsRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetHistoryKLPointsRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetHistoryKLPointsRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetHistoryKLPointsRequest_Internal) GetPayload() *QotGetHistoryKLPointsRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetHistoryKLPointsResponse_Internal struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RetType       *RetType                       `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                        `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                         `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetHistoryKLPointsResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetHistoryKLPointsResponse_Internal fields.
const (
	Default_QotGetHistoryKLPointsResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetHistoryKLPointsResponse_Internal) Reset() {
	*x = QotGetHistoryKLPointsResponse_Internal{}
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetHistoryKLPointsResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetHistoryKLPointsResponse_Internal) ProtoMessage() {}

func (x *QotGetHistoryKLPointsResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetHistoryKLPoints_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetHistoryKLPointsResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetHistoryKLPointsResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetHistoryKLPoints_proto_rawDescGZIP(), []int{5}
}

func (x *QotGetHistoryKLPointsResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetHistoryKLPointsResponse_Internal_RetType
}

func (x *QotGetHistoryKLPointsResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetHistoryKLPointsResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetHistoryKLPointsResponse_Internal) GetPayload() *QotGetHistoryKLPointsResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetHistoryKLPoints_proto protoreflect.FileDescriptor

const file_Qot_GetHistoryKLPoints_proto_rawDesc = "" +
	"\n" +
	"\x1cQot_GetHistoryKLPoints.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xd7\x02\n" +
	"\x1cQotGetHistoryKLPointsRequest\x12/\n" +
	"\trehabType\x18\x01 \x02(\x0e2\x11.futupb.RehabTypeR\trehabType\x12&\n" +
	"\x06klType\x18\x02 \x02(\x0e2\x0e.futupb.KLTypeR\x06klType\x122\n" +
	"\n" +
	"noDataMode\x18\x03 \x02(\x0e2\x12.futupb.NoDataModeR\n" +
	"noDataMode\x124\n" +
	"\fsecurityList\x18\x04 \x03(\v2\x10.futupb.SecurityR\fsecurityList\x12\x1a\n" +
	"\btimeList\x18\x05 \x03(\tR\btimeList\x12,\n" +
	"\x11maxReqSecurityNum\x18\x06 \x01(\x05R\x11maxReqSecurityNum\x12*\n" +
	"\x10needKLFieldsFlag\x18\a \x01(\x03R\x10needKLFieldsFlag\"v\n" +
	"\x0fHistoryPointsKL\x12*\n" +
	"\x06status\x18\x01 \x02(\x0e2\x12.futupb.DataStatusR\x06status\x12\x18\n" +
	"\areqTime\x18\x02 \x02(\tR\areqTime\x12\x1d\n" +
	"\x02kl\x18\x03 \x02(\v2\r.futupb.KLineR\x02kl\"x\n" +
	"\x17SecurityHistoryKLPoints\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12/\n" +
	"\x06klList\x18\x02 \x03(\v2\x17.futupb.HistoryPointsKLR\x06klList\"|\n" +
	"\x1dQotGetHistoryKLPointsResponse\x12A\n" +
	"\vklPointList\x18\x01 \x03(\v2\x1f.futupb.SecurityHistoryKLPointsR\vklPointList\x12\x18\n" +
	"\ahasNext\x18\x02 \x01(\bR\ahasNext\"g\n" +
	"%QotGetHistoryKLPointsRequest_Internal\x12>\n" +
	"\apayload\x18\x01 \x02(\v2$.futupb.QotGetHistoryKLPointsRequestR\apayload\"\xd7\x01\n" +
	"&QotGetHistoryKLPointsResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12?\n" +
	"\apayload\x18\x04 \x01(\v2%.futupb.QotGetHistoryKLPointsResponseR\apayload*R\n" +
	"\n" +
	"NoDataMode\x12\x13\n" +
	"\x0fNoDataMode_Null\x10\x00\x12\x16\n" +
	"\x12NoDataMode_Forward\x10\x01\x12\x17\n" +
	"\x13NoDataMode_Backward\x10\x02*g\n" +
	"\n" +
	"DataStatus\x12\x13\n" +
	"\x0fDataStatus_Null\x10\x00\x12\x16\n" +
	"\x12DataStatus_Current\x10\x01\x12\x17\n" +
	"\x13DataStatus_Previous\x10\x02\x12\x13\n" +
	"\x0fDataStatus_Back\x10\x03B4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetHistoryKLPoints_proto_rawDescOnce sync.Once
	file_Qot_GetHistoryKLPoints_proto_rawDescData []byte
)

func file_Qot_GetHistoryKLPoints_proto_rawDescGZIP() []byte {
	file_Qot_GetHistoryKLPoints_proto_rawDescOnce.Do(func() {
		file_Qot_GetHistoryKLPoints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetHistoryKLPoints_proto_rawDesc), len(file_Qot_GetHistoryKLPoints_proto_rawDesc)))
	})
	return file_Qot_GetHistoryKLPoints_proto_rawDescData
}

var file_Qot_GetHistoryKLPoints_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Qot_GetHistoryKLPoints_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Qot_GetHistoryKLPoints_proto_goTypes = []any{
	(NoDataMode)(0),                                // 0: futupb.NoDataMode
	(DataStatus)(0),                                // 1: futupb.DataStatus
	(*QotGetHistoryKLPointsRequest)(nil),           // 2: futupb.QotGetHistoryKLPointsRequest
	(*HistoryPointsKL)(nil),                        // 3: futupb.HistoryPointsKL
	(*SecurityHistoryKLPoints)(nil),                // 4: futupb.SecurityHistoryKLPoints
	(*QotGetHistoryKLPointsResponse)(nil),          // 5: futupb.QotGetHistoryKLPointsResponse
	(*QotGetHistoryKLPointsRequest_Internal)(nil),  // 6: futupb.QotGetHistoryKLPointsRequest_Internal
	(*QotGetHistoryKLPointsResponse_Internal)(nil), // 7: futupb.QotGetHistoryKLPointsResponse_Internal
	(RehabType)(0),                                 // 8: futupb.RehabType
	(KLType)(0),                                    // 9: futupb.KLType
	(*Security)(nil),                               // 10: futupb.Security
	(*KLine)(nil),                                  // 11: futupb.KLine
	(RetType)(0),                                   // 12: futupb.RetType
}
var file_Qot_GetHistoryKLPoints_proto_depIdxs = []int32{
	8,  // 0: futupb.QotGetHistoryKLPointsRequest.rehabType:type_name -> futupb.RehabType
	9,  // 1: futupb.QotGetHistoryKLPointsRequest.klType:type_name -> futupb.KLType
	0,  // 2: futupb.QotGetHistoryKLPointsRequest.noDataMode:type_name -> futupb.NoDataMode
	10, // 3: futupb.QotGetHistoryKLPointsRequest.securityList:type_name -> futupb.Security
	1,  // 4: futupb.HistoryPointsKL.status:type_name -> futupb.DataStatus
	11, // 5: futupb.HistoryPointsKL.kl:type_name -> futupb.KLine
	10, // 6: futupb.SecurityHistoryKLPoints.security:type_name -> futupb.Security
	3,  // 7: futupb.SecurityHistoryKLPoints.klList:type_name -> futupb.HistoryPointsKL
	4,  // 8: futupb.QotGetHistoryKLPointsResponse.klPointList:type_name -> futupb.SecurityHistoryKLPoints
	2,  // 9: futupb.QotGetHistoryKLPointsRequest_Internal.payload:type_name -> futupb.QotGetHistoryKLPointsRequest
	12, // 10: futupb.QotGetHistoryKLPointsResponse_Internal.retType:type_name -> futupb.RetType
	5,  // 11: futupb.QotGetHistoryKLPointsResponse_Internal.payload:type_name -> futupb.QotGetHistoryKLPointsResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_Qot_GetHistoryKLPoints_proto_init() }
func file_Qot_GetHistoryKLPoints_proto_init() {
	if File_Qot_GetHistoryKLPoints_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetHistoryKLPoints_proto_rawDesc), len(file_Qot_GetHistoryKLPoints_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetHistoryKLPoints_proto_goTypes,
		DependencyIndexes: file_Qot_GetHistoryKLPoints_proto_depIdxs,
		EnumInfos:         file_Qot_GetHistoryKLPoints_proto_enumTypes,
		MessageInfos:      file_Qot_GetHistoryKLPoints_proto_msgTypes,
	}.Build()
	File_Qot_GetHistoryKLPoints_proto = out.File
	file_Qot_GetHistoryKLPoints_proto_goTypes = nil
	file_Qot_GetHistoryKLPoints_proto_depIdxs = nil
}
