// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Qot_GetValuationDetail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 走势
type ValuationTrend struct {
	state               protoimpl.MessageState                    `protogen:"open.v1"`
	CurrentValue        *float64                                  `protobuf:"fixed64,1,opt,name=currentValue" json:"currentValue,omitempty"`               // 当前估值
	AverageValue        *float64                                  `protobuf:"fixed64,2,opt,name=averageValue" json:"averageValue,omitempty"`               // 历史平均估值
	AvgMinus1Stddev     *float64                                  `protobuf:"fixed64,3,opt,name=avgMinus1Stddev" json:"avgMinus1Stddev,omitempty"`         // 历史平均 - 1σ
	AvgPlus1Stddev      *float64                                  `protobuf:"fixed64,4,opt,name=avgPlus1Stddev" json:"avgPlus1Stddev,omitempty"`           // 历史平均 + 1σ
	ValuationPercentile *float64                                  `protobuf:"fixed64,5,opt,name=valuationPercentile" json:"valuationPercentile,omitempty"` // 估值历史分位，百分号前的值，如 12.34 表示 12.34%
	ForwardValue        *float64                                  `protobuf:"fixed64,6,opt,name=forwardValue" json:"forwardValue,omitempty"`               // 预测估值，仅 PE / PS 有
	HistoricalItems     []*ValuationTrend_ValuationHistoricalItem `protobuf:"bytes,7,rep,name=historicalItems" json:"historicalItems,omitempty"`           // 历史数据
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValuationTrend) Reset() {
	*x = ValuationTrend{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuationTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuationTrend) ProtoMessage() {}

func (x *ValuationTrend) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuationTrend.ProtoReflect.Descriptor instead.
func (*ValuationTrend) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{0}
}

func (x *ValuationTrend) GetCurrentValue() float64 {
	if x != nil && x.CurrentValue != nil {
		return *x.CurrentValue
	}
	return 0
}

func (x *ValuationTrend) GetAverageValue() float64 {
	if x != nil && x.AverageValue != nil {
		return *x.AverageValue
	}
	return 0
}

func (x *ValuationTrend) GetAvgMinus1Stddev() float64 {
	if x != nil && x.AvgMinus1Stddev != nil {
		return *x.AvgMinus1Stddev
	}
	return 0
}

func (x *ValuationTrend) GetAvgPlus1Stddev() float64 {
	if x != nil && x.AvgPlus1Stddev != nil {
		return *x.AvgPlus1Stddev
	}
	return 0
}

func (x *ValuationTrend) GetValuationPercentile() float64 {
	if x != nil && x.ValuationPercentile != nil {
		return *x.ValuationPercentile
	}
	return 0
}

func (x *ValuationTrend) GetForwardValue() float64 {
	if x != nil && x.ForwardValue != nil {
		return *x.ForwardValue
	}
	return 0
}

func (x *ValuationTrend) GetHistoricalItems() []*ValuationTrend_ValuationHistoricalItem {
	if x != nil {
		return x.HistoricalItems
	}
	return nil
}

// 市场分布
type MarketDistribution struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Sections      []*MarketDistribution_DistributionSection `protobuf:"bytes,1,rep,name=sections" json:"sections,omitempty"`           // 区间分布（降序）
	Total         *int32                                    `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`                // 市场总数 / 成分股总数
	Ranking       *int32                                    `protobuf:"varint,3,opt,name=ranking" json:"ranking,omitempty"`            // 该股票估值在市场中的排名（指数无）
	AverageValue  *float64                                  `protobuf:"fixed64,4,opt,name=averageValue" json:"averageValue,omitempty"` // 市场估值均值（指数无）
	MedianValue   *float64                                  `protobuf:"fixed64,5,opt,name=medianValue" json:"medianValue,omitempty"`   // 市场估值中位数（指数无）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDistribution) Reset() {
	*x = MarketDistribution{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDistribution) ProtoMessage() {}

func (x *MarketDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDistribution.ProtoReflect.Descriptor instead.
func (*MarketDistribution) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{1}
}

func (x *MarketDistribution) GetSections() []*MarketDistribution_DistributionSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *MarketDistribution) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *MarketDistribution) GetRanking() int32 {
	if x != nil && x.Ranking != nil {
		return *x.Ranking
	}
	return 0
}

func (x *MarketDistribution) GetAverageValue() float64 {
	if x != nil && x.AverageValue != nil {
		return *x.AverageValue
	}
	return 0
}

func (x *MarketDistribution) GetMedianValue() float64 {
	if x != nil && x.MedianValue != nil {
		return *x.MedianValue
	}
	return 0
}

// 行业分布
type PlateDistribution struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	Plate               *Security                           `protobuf:"bytes,1,opt,name=plate" json:"plate,omitempty"`                              // 所属板块
	PlateName           *string                             `protobuf:"bytes,2,opt,name=plateName" json:"plateName,omitempty"`                      // 所属板块名称
	PlateAverageValue   *float64                            `protobuf:"fixed64,3,opt,name=plateAverageValue" json:"plateAverageValue,omitempty"`    // 板块估值均值
	PlateRanking        *int32                              `protobuf:"varint,4,opt,name=plateRanking" json:"plateRanking,omitempty"`               // 该股票估值在板块中的排名
	PlateStockItemCount *int32                              `protobuf:"varint,5,opt,name=plateStockItemCount" json:"plateStockItemCount,omitempty"` // 板块个股总数
	StockItems          []*PlateDistribution_PlateStockItem `protobuf:"bytes,6,rep,name=stockItems" json:"stockItems,omitempty"`                    // 板块成分股估值明细
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlateDistribution) Reset() {
	*x = PlateDistribution{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateDistribution) ProtoMessage() {}

func (x *PlateDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateDistribution.ProtoReflect.Descriptor instead.
func (*PlateDistribution) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{2}
}

func (x *PlateDistribution) GetPlate() *Security {
	if x != nil {
		return x.Plate
	}
	return nil
}

func (x *PlateDistribution) GetPlateName() string {
	if x != nil && x.PlateName != nil {
		return *x.PlateName
	}
	return ""
}

func (x *PlateDistribution) GetPlateAverageValue() float64 {
	if x != nil && x.PlateAverageValue != nil {
		return *x.PlateAverageValue
	}
	return 0
}

func (x *PlateDistribution) GetPlateRanking() int32 {
	if x != nil && x.PlateRanking != nil {
		return *x.PlateRanking
	}
	return 0
}

func (x *PlateDistribution) GetPlateStockItemCount() int32 {
	if x != nil && x.PlateStockItemCount != nil {
		return *x.PlateStockItemCount
	}
	return 0
}

func (x *PlateDistribution) GetStockItems() []*PlateDistribution_PlateStockItem {
	if x != nil {
		return x.StockItems
	}
	return nil
}

// 盈利 / 营收增速聚合
type ProfitGrowthRate struct {
	state                protoimpl.MessageState               `protogen:"open.v1"`
	FinancialTtmMultiple *float64                             `protobuf:"fixed64,1,opt,name=financialTtmMultiple" json:"financialTtmMultiple,omitempty"` // TTM 增长倍数
	MarketCapMultiple    *float64                             `protobuf:"fixed64,2,opt,name=marketCapMultiple" json:"marketCapMultiple,omitempty"`       // 市值增长倍数
	YearCount            *int32                               `protobuf:"varint,3,opt,name=yearCount" json:"yearCount,omitempty"`                        // 计算增长倍数时实际用到的年份数量
	ProfitData           []*ProfitGrowthRate_ProfitGrowthItem `protobuf:"bytes,4,rep,name=profitData" json:"profitData,omitempty"`                       // 各期数据
	ConclusionDetailed   *string                              `protobuf:"bytes,5,opt,name=conclusionDetailed" json:"conclusionDetailed,omitempty"`       // 估值结论描述（已多语言翻译；仅 label 时为 label，仅 detailed 时为 detailed，两者均有时为 "label : detailed"）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProfitGrowthRate) Reset() {
	*x = ProfitGrowthRate{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitGrowthRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitGrowthRate) ProtoMessage() {}

func (x *ProfitGrowthRate) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitGrowthRate.ProtoReflect.Descriptor instead.
func (*ProfitGrowthRate) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{3}
}

func (x *ProfitGrowthRate) GetFinancialTtmMultiple() float64 {
	if x != nil && x.FinancialTtmMultiple != nil {
		return *x.FinancialTtmMultiple
	}
	return 0
}

func (x *ProfitGrowthRate) GetMarketCapMultiple() float64 {
	if x != nil && x.MarketCapMultiple != nil {
		return *x.MarketCapMultiple
	}
	return 0
}

func (x *ProfitGrowthRate) GetYearCount() int32 {
	if x != nil && x.YearCount != nil {
		return *x.YearCount
	}
	return 0
}

func (x *ProfitGrowthRate) GetProfitData() []*ProfitGrowthRate_ProfitGrowthItem {
	if x != nil {
		return x.ProfitData
	}
	return nil
}

func (x *ProfitGrowthRate) GetConclusionDetailed() string {
	if x != nil && x.ConclusionDetailed != nil {
		return *x.ConclusionDetailed
	}
	return ""
}

// ===== 请求 / 响应 =====
type QotGetValuationDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                                            // 股票
	ValuationType *ValuationType         `protobuf:"varint,2,opt,name=valuationType,enum=futupb.ValuationType" json:"valuationType,omitempty"`       // 估值类型，详见 Qot_Common.ValuationType 定义，默认 0(Unknown，使用推荐类型)
	IntervalType  *ValuationIntervalType `protobuf:"varint,3,opt,name=intervalType,enum=futupb.ValuationIntervalType" json:"intervalType,omitempty"` // 历史数据时间周期，详见 Qot_Common.ValuationIntervalType 定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetValuationDetailRequest) Reset() {
	*x = QotGetValuationDetailRequest{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetValuationDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetValuationDetailRequest) ProtoMessage() {}

func (x *QotGetValuationDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetValuationDetailRequest.ProtoReflect.Descriptor instead.
func (*QotGetValuationDetailRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetValuationDetailRequest) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotGetValuationDetailRequest) GetValuationType() ValuationType {
	if x != nil && x.ValuationType != nil {
		return *x.ValuationType
	}
	return ValuationType_ValuationType_Unknown
}

func (x *QotGetValuationDetailRequest) GetIntervalType() ValuationIntervalType {
	if x != nil && x.IntervalType != nil {
		return *x.IntervalType
	}
	return ValuationIntervalType_ValuationIntervalType_Unknown
}

type QotGetValuationDetailResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ValuationType     *ValuationType         `protobuf:"varint,1,opt,name=valuationType,enum=futupb.ValuationType" json:"valuationType,omitempty"` // 实际返回的估值类型，详见 Qot_Common.ValuationType 定义
	LastUpdateTime    *uint64                `protobuf:"varint,2,opt,name=lastUpdateTime" json:"lastUpdateTime,omitempty"`                         // 最后更新时间戳（秒）
	LastUpdateTimeStr *string                `protobuf:"bytes,3,opt,name=lastUpdateTimeStr" json:"lastUpdateTimeStr,omitempty"`                    // 最后更新时间字符串，格式 YYYY-MM-DD HH:MM:SS，对应市场时区
	// 4 个聚合字段
	Trend              *ValuationTrend     `protobuf:"bytes,4,opt,name=trend" json:"trend,omitempty"`                           // 走势（个股 + 指数）
	MarketDistribution *MarketDistribution `protobuf:"bytes,5,opt,name=marketDistribution" json:"marketDistribution,omitempty"` // 市场分布 / 成分股分布（个股 + 指数）
	PlateDistribution  *PlateDistribution  `protobuf:"bytes,6,opt,name=plateDistribution" json:"plateDistribution,omitempty"`   // 行业分布（仅个股）
	ProfitGrowthRate   *ProfitGrowthRate   `protobuf:"bytes,7,opt,name=profitGrowthRate" json:"profitGrowthRate,omitempty"`     // 盈利 / 营收增速（仅个股，PB 无）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QotGetValuationDetailResponse) Reset() {
	*x = QotGetValuationDetailResponse{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetValuationDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetValuationDetailResponse) ProtoMessage() {}

func (x *QotGetValuationDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetValuationDetailResponse.ProtoReflect.Descriptor instead.
func (*QotGetValuationDetailResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{5}
}

func (x *QotGetValuationDetailResponse) GetValuationType() ValuationType {
	if x != nil && x.ValuationType != nil {
		return *x.ValuationType
	}
	return ValuationType_ValuationType_Unknown
}

func (x *QotGetValuationDetailResponse) GetLastUpdateTime() uint64 {
	if x != nil && x.LastUpdateTime != nil {
		return *x.LastUpdateTime
	}
	return 0
}

func (x *QotGetValuationDetailResponse) GetLastUpdateTimeStr() string {
	if x != nil && x.LastUpdateTimeStr != nil {
		return *x.LastUpdateTimeStr
	}
	return ""
}

func (x *QotGetValuationDetailResponse) GetTrend() *ValuationTrend {
	if x != nil {
		return x.Trend
	}
	return nil
}

func (x *QotGetValuationDetailResponse) GetMarketDistribution() *MarketDistribution {
	if x != nil {
		return x.MarketDistribution
	}
	return nil
}

func (x *QotGetValuationDetailResponse) GetPlateDistribution() *PlateDistribution {
	if x != nil {
		return x.PlateDistribution
	}
	return nil
}

func (x *QotGetValuationDetailResponse) GetProfitGrowthRate() *ProfitGrowthRate {
	if x != nil {
		return x.ProfitGrowthRate
	}
	return nil
}

type QotGetValuationDetailRequest_Internal struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Payload       *QotGetValuationDetailRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetValuationDetailRequest_Internal) Reset() {
	*x = QotGetValuationDetailRequest_Internal{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetValuationDetailRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetValuationDetailRequest_Internal) ProtoMessage() {}

func (x *QotGetValuationDetailRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetValuationDetailRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetValuationDetailRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{6}
}

func (x *QotGetValuationDetailRequest_Internal) GetPayload() *QotGetValuationDetailRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetValuationDetailResponse_Internal struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RetType       *RetType                       `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` // RetType，返回结果
	RetMsg        *string                        `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                         `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetValuationDetailResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetValuationDetailResponse_Internal fields.
const (
	Default_QotGetValuationDetailResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetValuationDetailResponse_Internal) Reset() {
	*x = QotGetValuationDetailResponse_Internal{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetValuationDetailResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetValuationDetailResponse_Internal) ProtoMessage() {}

func (x *QotGetValuationDetailResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetValuationDetailResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetValuationDetailResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{7}
}

func (x *QotGetValuationDetailResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetValuationDetailResponse_Internal_RetType
}

func (x *QotGetValuationDetailResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetValuationDetailResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetValuationDetailResponse_Internal) GetPayload() *QotGetValuationDetailResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ValuationTrend_ValuationHistoricalItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float64               `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`           // 估值
	Time          *uint64                `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`              // 时间戳（秒）
	TimeStr       *string                `protobuf:"bytes,3,opt,name=timeStr" json:"timeStr,omitempty"`         // 时间字符串，格式 YYYY-MM-DD，对应市场时区
	PlateValue    *float64               `protobuf:"fixed64,4,opt,name=plateValue" json:"plateValue,omitempty"` // 行业均值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuationTrend_ValuationHistoricalItem) Reset() {
	*x = ValuationTrend_ValuationHistoricalItem{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuationTrend_ValuationHistoricalItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuationTrend_ValuationHistoricalItem) ProtoMessage() {}

func (x *ValuationTrend_ValuationHistoricalItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuationTrend_ValuationHistoricalItem.ProtoReflect.Descriptor instead.
func (*ValuationTrend_ValuationHistoricalItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ValuationTrend_ValuationHistoricalItem) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ValuationTrend_ValuationHistoricalItem) GetTime() uint64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *ValuationTrend_ValuationHistoricalItem) GetTimeStr() string {
	if x != nil && x.TimeStr != nil {
		return *x.TimeStr
	}
	return ""
}

func (x *ValuationTrend_ValuationHistoricalItem) GetPlateValue() float64 {
	if x != nil && x.PlateValue != nil {
		return *x.PlateValue
	}
	return 0
}

// 区间分布
type MarketDistribution_DistributionSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *float64               `protobuf:"fixed64,1,opt,name=start" json:"start,omitempty"`  // 区间开始值
	End           *float64               `protobuf:"fixed64,2,opt,name=end" json:"end,omitempty"`      // 区间结束值（0 表示无上限）
	Number        *int32                 `protobuf:"varint,3,opt,name=number" json:"number,omitempty"` // 该区间个股数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDistribution_DistributionSection) Reset() {
	*x = MarketDistribution_DistributionSection{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDistribution_DistributionSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDistribution_DistributionSection) ProtoMessage() {}

func (x *MarketDistribution_DistributionSection) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDistribution_DistributionSection.ProtoReflect.Descriptor instead.
func (*MarketDistribution_DistributionSection) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MarketDistribution_DistributionSection) GetStart() float64 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *MarketDistribution_DistributionSection) GetEnd() float64 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *MarketDistribution_DistributionSection) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

type PlateDistribution_PlateStockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,opt,name=security" json:"security,omitempty"`     // 股票
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`             // 个股名称
	Value         *float64               `protobuf:"fixed64,3,opt,name=value" json:"value,omitempty"`         // 估值
	MarketCap     *float64               `protobuf:"fixed64,4,opt,name=marketCap" json:"marketCap,omitempty"` // 市值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlateDistribution_PlateStockItem) Reset() {
	*x = PlateDistribution_PlateStockItem{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateDistribution_PlateStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateDistribution_PlateStockItem) ProtoMessage() {}

func (x *PlateDistribution_PlateStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateDistribution_PlateStockItem.ProtoReflect.Descriptor instead.
func (*PlateDistribution_PlateStockItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PlateDistribution_PlateStockItem) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *PlateDistribution_PlateStockItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PlateDistribution_PlateStockItem) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *PlateDistribution_PlateStockItem) GetMarketCap() float64 {
	if x != nil && x.MarketCap != nil {
		return *x.MarketCap
	}
	return 0
}

type ProfitGrowthRate_ProfitGrowthItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FinancialYear       *uint32                `protobuf:"varint,1,opt,name=financialYear" json:"financialYear,omitempty"`              // 财报年度
	FinancialQuarter    *uint32                `protobuf:"varint,2,opt,name=financialQuarter" json:"financialQuarter,omitempty"`        // 财报季度（FinancialType 1=Q1, 2=Q2, 3=Q3, 4=FY）
	PeriodStr           *string                `protobuf:"bytes,3,opt,name=periodStr" json:"periodStr,omitempty"`                       // 财报周期，如 "2024/Q3"、"2024/FY"
	ReportDate          *int64                 `protobuf:"varint,4,opt,name=reportDate" json:"reportDate,omitempty"`                    // 报告日时间戳（秒）
	ReportDateStr       *string                `protobuf:"bytes,5,opt,name=reportDateStr" json:"reportDateStr,omitempty"`               // 报告日字符串，格式 YYYY-MM-DD，对应市场时区
	MarketCapMultiple   *float64               `protobuf:"fixed64,6,opt,name=marketCapMultiple" json:"marketCapMultiple,omitempty"`     // 报告日市值倍数（基准期 = 1）
	FinanceDataMultiple *float64               `protobuf:"fixed64,7,opt,name=financeDataMultiple" json:"financeDataMultiple,omitempty"` // 盈利 / 营收倍数（基准期 = 1，依 valuationType 而定）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfitGrowthRate_ProfitGrowthItem) Reset() {
	*x = ProfitGrowthRate_ProfitGrowthItem{}
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitGrowthRate_ProfitGrowthItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitGrowthRate_ProfitGrowthItem) ProtoMessage() {}

func (x *ProfitGrowthRate_ProfitGrowthItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetValuationDetail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitGrowthRate_ProfitGrowthItem.ProtoReflect.Descriptor instead.
func (*ProfitGrowthRate_ProfitGrowthItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetValuationDetail_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetFinancialYear() uint32 {
	if x != nil && x.FinancialYear != nil {
		return *x.FinancialYear
	}
	return 0
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetFinancialQuarter() uint32 {
	if x != nil && x.FinancialQuarter != nil {
		return *x.FinancialQuarter
	}
	return 0
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetPeriodStr() string {
	if x != nil && x.PeriodStr != nil {
		return *x.PeriodStr
	}
	return ""
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetReportDate() int64 {
	if x != nil && x.ReportDate != nil {
		return *x.ReportDate
	}
	return 0
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetReportDateStr() string {
	if x != nil && x.ReportDateStr != nil {
		return *x.ReportDateStr
	}
	return ""
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetMarketCapMultiple() float64 {
	if x != nil && x.MarketCapMultiple != nil {
		return *x.MarketCapMultiple
	}
	return 0
}

func (x *ProfitGrowthRate_ProfitGrowthItem) GetFinanceDataMultiple() float64 {
	if x != nil && x.FinanceDataMultiple != nil {
		return *x.FinanceDataMultiple
	}
	return 0
}

var File_Qot_GetValuationDetail_proto protoreflect.FileDescriptor

const file_Qot_GetValuationDetail_proto_rawDesc = "" +
	"\n" +
	"\x1cQot_GetValuationDetail.proto\x12\x06futupb\x1a\vTypes.proto\"\xd9\x03\n" +
	"\x0eValuationTrend\x12\"\n" +
	"\fcurrentValue\x18\x01 \x01(\x01R\fcurrentValue\x12\"\n" +
	"\faverageValue\x18\x02 \x01(\x01R\faverageValue\x12(\n" +
	"\x0favgMinus1Stddev\x18\x03 \x01(\x01R\x0favgMinus1Stddev\x12&\n" +
	"\x0eavgPlus1Stddev\x18\x04 \x01(\x01R\x0eavgPlus1Stddev\x120\n" +
	"\x13valuationPercentile\x18\x05 \x01(\x01R\x13valuationPercentile\x12\"\n" +
	"\fforwardValue\x18\x06 \x01(\x01R\fforwardValue\x12X\n" +
	"\x0fhistoricalItems\x18\a \x03(\v2..futupb.ValuationTrend.ValuationHistoricalItemR\x0fhistoricalItems\x1a}\n" +
	"\x17ValuationHistoricalItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12\x18\n" +
	"\atimeStr\x18\x03 \x01(\tR\atimeStr\x12\x1e\n" +
	"\n" +
	"plateValue\x18\x04 \x01(\x01R\n" +
	"plateValue\"\xad\x02\n" +
	"\x12MarketDistribution\x12J\n" +
	"\bsections\x18\x01 \x03(\v2..futupb.MarketDistribution.DistributionSectionR\bsections\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\aranking\x18\x03 \x01(\x05R\aranking\x12\"\n" +
	"\faverageValue\x18\x04 \x01(\x01R\faverageValue\x12 \n" +
	"\vmedianValue\x18\x05 \x01(\x01R\vmedianValue\x1aU\n" +
	"\x13DistributionSection\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x01R\x03end\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\"\xb0\x03\n" +
	"\x11PlateDistribution\x12&\n" +
	"\x05plate\x18\x01 \x01(\v2\x10.futupb.SecurityR\x05plate\x12\x1c\n" +
	"\tplateName\x18\x02 \x01(\tR\tplateName\x12,\n" +
	"\x11plateAverageValue\x18\x03 \x01(\x01R\x11plateAverageValue\x12\"\n" +
	"\fplateRanking\x18\x04 \x01(\x05R\fplateRanking\x120\n" +
	"\x13plateStockItemCount\x18\x05 \x01(\x05R\x13plateStockItemCount\x12H\n" +
	"\n" +
	"stockItems\x18\x06 \x03(\v2(.futupb.PlateDistribution.PlateStockItemR\n" +
	"stockItems\x1a\x86\x01\n" +
	"\x0ePlateStockItem\x12,\n" +
	"\bsecurity\x18\x01 \x01(\v2\x10.futupb.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\tmarketCap\x18\x04 \x01(\x01R\tmarketCap\"\xb8\x04\n" +
	"\x10ProfitGrowthRate\x122\n" +
	"\x14financialTtmMultiple\x18\x01 \x01(\x01R\x14financialTtmMultiple\x12,\n" +
	"\x11marketCapMultiple\x18\x02 \x01(\x01R\x11marketCapMultiple\x12\x1c\n" +
	"\tyearCount\x18\x03 \x01(\x05R\tyearCount\x12I\n" +
	"\n" +
	"profitData\x18\x04 \x03(\v2).futupb.ProfitGrowthRate.ProfitGrowthItemR\n" +
	"profitData\x12.\n" +
	"\x12conclusionDetailed\x18\x05 \x01(\tR\x12conclusionDetailed\x1a\xa8\x02\n" +
	"\x10ProfitGrowthItem\x12$\n" +
	"\rfinancialYear\x18\x01 \x01(\rR\rfinancialYear\x12*\n" +
	"\x10financialQuarter\x18\x02 \x01(\rR\x10financialQuarter\x12\x1c\n" +
	"\tperiodStr\x18\x03 \x01(\tR\tperiodStr\x12\x1e\n" +
	"\n" +
	"reportDate\x18\x04 \x01(\x03R\n" +
	"reportDate\x12$\n" +
	"\rreportDateStr\x18\x05 \x01(\tR\rreportDateStr\x12,\n" +
	"\x11marketCapMultiple\x18\x06 \x01(\x01R\x11marketCapMultiple\x120\n" +
	"\x13financeDataMultiple\x18\a \x01(\x01R\x13financeDataMultiple\"\xcc\x01\n" +
	"\x1cQotGetValuationDetailRequest\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12;\n" +
	"\rvaluationType\x18\x02 \x01(\x0e2\x15.futupb.ValuationTypeR\rvaluationType\x12A\n" +
	"\fintervalType\x18\x03 \x01(\x0e2\x1d.futupb.ValuationIntervalTypeR\fintervalType\"\xbb\x03\n" +
	"\x1dQotGetValuationDetailResponse\x12;\n" +
	"\rvaluationType\x18\x01 \x01(\x0e2\x15.futupb.ValuationTypeR\rvaluationType\x12&\n" +
	"\x0elastUpdateTime\x18\x02 \x01(\x04R\x0elastUpdateTime\x12,\n" +
	"\x11lastUpdateTimeStr\x18\x03 \x01(\tR\x11lastUpdateTimeStr\x12,\n" +
	"\x05trend\x18\x04 \x01(\v2\x16.futupb.ValuationTrendR\x05trend\x12J\n" +
	"\x12marketDistribution\x18\x05 \x01(\v2\x1a.futupb.MarketDistributionR\x12marketDistribution\x12G\n" +
	"\x11plateDistribution\x18\x06 \x01(\v2\x19.futupb.PlateDistributionR\x11plateDistribution\x12D\n" +
	"\x10profitGrowthRate\x18\a \x01(\v2\x18.futupb.ProfitGrowthRateR\x10profitGrowthRate\"g\n" +
	"%QotGetValuationDetailRequest_Internal\x12>\n" +
	"\apayload\x18\x01 \x02(\v2$.futupb.QotGetValuationDetailRequestR\apayload\"\xd7\x01\n" +
	"&QotGetValuationDetailResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12?\n" +
	"\apayload\x18\x04 \x01(\v2%.futupb.QotGetValuationDetailResponseR\apayloadB\x1fZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetValuationDetail_proto_rawDescOnce sync.Once
	file_Qot_GetValuationDetail_proto_rawDescData []byte
)

func file_Qot_GetValuationDetail_proto_rawDescGZIP() []byte {
	file_Qot_GetValuationDetail_proto_rawDescOnce.Do(func() {
		file_Qot_GetValuationDetail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetValuationDetail_proto_rawDesc), len(file_Qot_GetValuationDetail_proto_rawDesc)))
	})
	return file_Qot_GetValuationDetail_proto_rawDescData
}

var file_Qot_GetValuationDetail_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_Qot_GetValuationDetail_proto_goTypes = []any{
	(*ValuationTrend)(nil),                         // 0: futupb.ValuationTrend
	(*MarketDistribution)(nil),                     // 1: futupb.MarketDistribution
	(*PlateDistribution)(nil),                      // 2: futupb.PlateDistribution
	(*ProfitGrowthRate)(nil),                       // 3: futupb.ProfitGrowthRate
	(*QotGetValuationDetailRequest)(nil),           // 4: futupb.QotGetValuationDetailRequest
	(*QotGetValuationDetailResponse)(nil),          // 5: futupb.QotGetValuationDetailResponse
	(*QotGetValuationDetailRequest_Internal)(nil),  // 6: futupb.QotGetValuationDetailRequest_Internal
	(*QotGetValuationDetailResponse_Internal)(nil), // 7: futupb.QotGetValuationDetailResponse_Internal
	(*ValuationTrend_ValuationHistoricalItem)(nil), // 8: futupb.ValuationTrend.ValuationHistoricalItem
	(*MarketDistribution_DistributionSection)(nil), // 9: futupb.MarketDistribution.DistributionSection
	(*PlateDistribution_PlateStockItem)(nil),       // 10: futupb.PlateDistribution.PlateStockItem
	(*ProfitGrowthRate_ProfitGrowthItem)(nil),      // 11: futupb.ProfitGrowthRate.ProfitGrowthItem
	(*Security)(nil),                               // 12: futupb.Security
	(ValuationType)(0),                             // 13: futupb.ValuationType
	(ValuationIntervalType)(0),                     // 14: futupb.ValuationIntervalType
	(RetType)(0),                                   // 15: futupb.RetType
}
var file_Qot_GetValuationDetail_proto_depIdxs = []int32{
	8,  // 0: futupb.ValuationTrend.historicalItems:type_name -> futupb.ValuationTrend.ValuationHistoricalItem
	9,  // 1: futupb.MarketDistribution.sections:type_name -> futupb.MarketDistribution.DistributionSection
	12, // 2: futupb.PlateDistribution.plate:type_name -> futupb.Security
	10, // 3: futupb.PlateDistribution.stockItems:type_name -> futupb.PlateDistribution.PlateStockItem
	11, // 4: futupb.ProfitGrowthRate.profitData:type_name -> futupb.ProfitGrowthRate.ProfitGrowthItem
	12, // 5: futupb.QotGetValuationDetailRequest.security:type_name -> futupb.Security
	13, // 6: futupb.QotGetValuationDetailRequest.valuationType:type_name -> futupb.ValuationType
	14, // 7: futupb.QotGetValuationDetailRequest.intervalType:type_name -> futupb.ValuationIntervalType
	13, // 8: futupb.QotGetValuationDetailResponse.valuationType:type_name -> futupb.ValuationType
	0,  // 9: futupb.QotGetValuationDetailResponse.trend:type_name -> futupb.ValuationTrend
	1,  // 10: futupb.QotGetValuationDetailResponse.marketDistribution:type_name -> futupb.MarketDistribution
	2,  // 11: futupb.QotGetValuationDetailResponse.plateDistribution:type_name -> futupb.PlateDistribution
	3,  // 12: futupb.QotGetValuationDetailResponse.profitGrowthRate:type_name -> futupb.ProfitGrowthRate
	4,  // 13: futupb.QotGetValuationDetailRequest_Internal.payload:type_name -> futupb.QotGetValuationDetailRequest
	15, // 14: futupb.QotGetValuationDetailResponse_Internal.retType:type_name -> futupb.RetType
	5,  // 15: futupb.QotGetValuationDetailResponse_Internal.payload:type_name -> futupb.QotGetValuationDetailResponse
	12, // 16: futupb.PlateDistribution.PlateStockItem.security:type_name -> futupb.Security
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_Qot_GetValuationDetail_proto_init() }
func file_Qot_GetValuationDetail_proto_init() {
	if File_Qot_GetValuationDetail_proto != nil {
		return
	}
	file_Types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetValuationDetail_proto_rawDesc), len(file_Qot_GetValuationDetail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetValuationDetail_proto_goTypes,
		DependencyIndexes: file_Qot_GetValuationDetail_proto_depIdxs,
		MessageInfos:      file_Qot_GetValuationDetail_proto_msgTypes,
	}.Build()
	File_Qot_GetValuationDetail_proto = out.File
	file_Qot_GetValuationDetail_proto_goTypes = nil
	file_Qot_GetValuationDetail_proto_depIdxs = nil
}
