// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Qot_GetMarketState.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QotGetMarketStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityList  []*Security            `protobuf:"bytes,1,rep,name=securityList" json:"securityList,omitempty"` //股票列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetMarketStateRequest) Reset() {
	*x = QotGetMarketStateRequest{}
	mi := &file_Qot_GetMarketState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetMarketStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetMarketStateRequest) ProtoMessage() {}

func (x *QotGetMarketStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetMarketState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetMarketStateRequest.ProtoReflect.Descriptor instead.
func (*QotGetMarketStateRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetMarketState_proto_rawDescGZIP(), []int{0}
}

func (x *QotGetMarketStateRequest) GetSecurityList() []*Security {
	if x != nil {
		return x.SecurityList
	}
	return nil
}

type MarketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`        //股票代码
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`                // 股票名称
	MarketState   *int32                 `protobuf:"varint,3,req,name=marketState" json:"marketState,omitempty"` //Qot_Common.QotMarketState,市场状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketInfo) Reset() {
	*x = MarketInfo{}
	mi := &file_Qot_GetMarketState_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketInfo) ProtoMessage() {}

func (x *MarketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetMarketState_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketInfo.ProtoReflect.Descriptor instead.
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return file_Qot_GetMarketState_proto_rawDescGZIP(), []int{1}
}

func (x *MarketInfo) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *MarketInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MarketInfo) GetMarketState() int32 {
	if x != nil && x.MarketState != nil {
		return *x.MarketState
	}
	return 0
}

type QotGetMarketStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketInfoList []*MarketInfo          `protobuf:"bytes,1,rep,name=marketInfoList" json:"marketInfoList,omitempty"` // 市场状态信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QotGetMarketStateResponse) Reset() {
	*x = QotGetMarketStateResponse{}
	mi := &file_Qot_GetMarketState_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetMarketStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetMarketStateResponse) ProtoMessage() {}

func (x *QotGetMarketStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetMarketState_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetMarketStateResponse.ProtoReflect.Descriptor instead.
func (*QotGetMarketStateResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetMarketState_proto_rawDescGZIP(), []int{2}
}

func (x *QotGetMarketStateResponse) GetMarketInfoList() []*MarketInfo {
	if x != nil {
		return x.MarketInfoList
	}
	return nil
}

type QotGetMarketStateRequest_Internal struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Payload       *QotGetMarketStateRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetMarketStateRequest_Internal) Reset() {
	*x = QotGetMarketStateRequest_Internal{}
	mi := &file_Qot_GetMarketState_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetMarketStateRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetMarketStateRequest_Internal) ProtoMessage() {}

func (x *QotGetMarketStateRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetMarketState_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetMarketStateRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetMarketStateRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetMarketState_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetMarketStateRequest_Internal) GetPayload() *QotGetMarketStateRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetMarketStateResponse_Internal struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RetType       *int32                     `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                    `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                     `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetMarketStateResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetMarketStateResponse_Internal fields.
const (
	Default_QotGetMarketStateResponse_Internal_RetType = int32(-400)
)

func (x *QotGetMarketStateResponse_Internal) Reset() {
	*x = QotGetMarketStateResponse_Internal{}
	mi := &file_Qot_GetMarketState_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetMarketStateResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetMarketStateResponse_Internal) ProtoMessage() {}

func (x *QotGetMarketStateResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetMarketState_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetMarketStateResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetMarketStateResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetMarketState_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetMarketStateResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetMarketStateResponse_Internal_RetType
}

func (x *QotGetMarketStateResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetMarketStateResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetMarketStateResponse_Internal) GetPayload() *QotGetMarketStateResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetMarketState_proto protoreflect.FileDescriptor

const file_Qot_GetMarketState_proto_rawDesc = "" +
	"\n" +
	"\x18Qot_GetMarketState.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"P\n" +
	"\x18QotGetMarketStateRequest\x124\n" +
	"\fsecurityList\x18\x01 \x03(\v2\x10.futupb.SecurityR\fsecurityList\"p\n" +
	"\n" +
	"MarketInfo\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12 \n" +
	"\vmarketState\x18\x03 \x02(\x05R\vmarketState\"W\n" +
	"\x19QotGetMarketStateResponse\x12:\n" +
	"\x0emarketInfoList\x18\x01 \x03(\v2\x12.futupb.MarketInfoR\x0emarketInfoList\"_\n" +
	"!QotGetMarketStateRequest_Internal\x12:\n" +
	"\apayload\x18\x01 \x02(\v2 .futupb.QotGetMarketStateRequestR\apayload\"\xb3\x01\n" +
	"\"QotGetMarketStateResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12;\n" +
	"\apayload\x18\x04 \x01(\v2!.futupb.QotGetMarketStateResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetMarketState_proto_rawDescOnce sync.Once
	file_Qot_GetMarketState_proto_rawDescData []byte
)

func file_Qot_GetMarketState_proto_rawDescGZIP() []byte {
	file_Qot_GetMarketState_proto_rawDescOnce.Do(func() {
		file_Qot_GetMarketState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetMarketState_proto_rawDesc), len(file_Qot_GetMarketState_proto_rawDesc)))
	})
	return file_Qot_GetMarketState_proto_rawDescData
}

var file_Qot_GetMarketState_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetMarketState_proto_goTypes = []any{
	(*QotGetMarketStateRequest)(nil),           // 0: futupb.QotGetMarketStateRequest
	(*MarketInfo)(nil),                         // 1: futupb.MarketInfo
	(*QotGetMarketStateResponse)(nil),          // 2: futupb.QotGetMarketStateResponse
	(*QotGetMarketStateRequest_Internal)(nil),  // 3: futupb.QotGetMarketStateRequest_Internal
	(*QotGetMarketStateResponse_Internal)(nil), // 4: futupb.QotGetMarketStateResponse_Internal
	(*Security)(nil),                           // 5: futupb.Security
}
var file_Qot_GetMarketState_proto_depIdxs = []int32{
	5, // 0: futupb.QotGetMarketStateRequest.securityList:type_name -> futupb.Security
	5, // 1: futupb.MarketInfo.security:type_name -> futupb.Security
	1, // 2: futupb.QotGetMarketStateResponse.marketInfoList:type_name -> futupb.MarketInfo
	0, // 3: futupb.QotGetMarketStateRequest_Internal.payload:type_name -> futupb.QotGetMarketStateRequest
	2, // 4: futupb.QotGetMarketStateResponse_Internal.payload:type_name -> futupb.QotGetMarketStateResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Qot_GetMarketState_proto_init() }
func file_Qot_GetMarketState_proto_init() {
	if File_Qot_GetMarketState_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Qot_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetMarketState_proto_rawDesc), len(file_Qot_GetMarketState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetMarketState_proto_goTypes,
		DependencyIndexes: file_Qot_GetMarketState_proto_depIdxs,
		MessageInfos:      file_Qot_GetMarketState_proto_msgTypes,
	}.Build()
	File_Qot_GetMarketState_proto = out.File
	file_Qot_GetMarketState_proto_goTypes = nil
	file_Qot_GetMarketState_proto_depIdxs = nil
}
