// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Qot_GetShareholdersOverview.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OwnershipStaticItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`             // 持股人/分组名称
	HolderPct     *float64               `protobuf:"fixed64,2,opt,name=holderPct" json:"holderPct,omitempty"` // 持股占比（百分比），如 23.37 表示 23.37%
	HolderId      *int32                 `protobuf:"varint,3,opt,name=holderId" json:"holderId,omitempty"`    // 股东 ID；mainHolderInfoList 中有值，其他分组为 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnershipStaticItem) Reset() {
	*x = OwnershipStaticItem{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipStaticItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipStaticItem) ProtoMessage() {}

func (x *OwnershipStaticItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipStaticItem.ProtoReflect.Descriptor instead.
func (*OwnershipStaticItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{0}
}

func (x *OwnershipStaticItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OwnershipStaticItem) GetHolderPct() float64 {
	if x != nil && x.HolderPct != nil {
		return *x.HolderPct
	}
	return 0
}

func (x *OwnershipStaticItem) GetHolderId() int32 {
	if x != nil && x.HolderId != nil {
		return *x.HolderId
	}
	return 0
}

type OwnershipStaticInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaticDate    *uint64                `protobuf:"varint,1,opt,name=staticDate" json:"staticDate,omitempty"`      // 统计日期时间戳（秒）
	StaticDateStr *string                `protobuf:"bytes,2,opt,name=staticDateStr" json:"staticDateStr,omitempty"` // 统计日期字符串，格式 YYYY-MM-DD，对应市场时区
	ItemList      []*OwnershipStaticItem `protobuf:"bytes,4,rep,name=itemList" json:"itemList,omitempty"`           // 持股统计子项列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnershipStaticInfo) Reset() {
	*x = OwnershipStaticInfo{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipStaticInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipStaticInfo) ProtoMessage() {}

func (x *OwnershipStaticInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipStaticInfo.ProtoReflect.Descriptor instead.
func (*OwnershipStaticInfo) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{1}
}

func (x *OwnershipStaticInfo) GetStaticDate() uint64 {
	if x != nil && x.StaticDate != nil {
		return *x.StaticDate
	}
	return 0
}

func (x *OwnershipStaticInfo) GetStaticDateStr() string {
	if x != nil && x.StaticDateStr != nil {
		return *x.StaticDateStr
	}
	return ""
}

func (x *OwnershipStaticInfo) GetItemList() []*OwnershipStaticItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

// 报告期条目
type HoldingPeriodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodText    *string                `protobuf:"bytes,1,opt,name=periodText" json:"periodText,omitempty"` // 报告期，如 "2025/Q3"
	PeriodId      *int32                 `protobuf:"varint,2,opt,name=periodId" json:"periodId,omitempty"`    // 报告期 ID，下次请求原样传入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingPeriodItem) Reset() {
	*x = HoldingPeriodItem{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingPeriodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingPeriodItem) ProtoMessage() {}

func (x *HoldingPeriodItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingPeriodItem.ProtoReflect.Descriptor instead.
func (*HoldingPeriodItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{2}
}

func (x *HoldingPeriodItem) GetPeriodText() string {
	if x != nil && x.PeriodText != nil {
		return *x.PeriodText
	}
	return ""
}

func (x *HoldingPeriodItem) GetPeriodId() int32 {
	if x != nil && x.PeriodId != nil {
		return *x.PeriodId
	}
	return 0
}

type QotGetShareholdersOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *Security              `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	PeriodId      *int32                 `protobuf:"varint,3,opt,name=periodId" json:"periodId,omitempty"` // 指定报告期 ID；传 0 或不传则返回最新数据，并额外返回可用报告期列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetShareholdersOverviewRequest) Reset() {
	*x = QotGetShareholdersOverviewRequest{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetShareholdersOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetShareholdersOverviewRequest) ProtoMessage() {}

func (x *QotGetShareholdersOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetShareholdersOverviewRequest.ProtoReflect.Descriptor instead.
func (*QotGetShareholdersOverviewRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetShareholdersOverviewRequest) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *QotGetShareholdersOverviewRequest) GetPeriodId() int32 {
	if x != nil && x.PeriodId != nil {
		return *x.PeriodId
	}
	return 0
}

type QotGetShareholdersOverviewResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MainHolderInfoList []*OwnershipStaticInfo `protobuf:"bytes,1,rep,name=mainHolderInfoList" json:"mainHolderInfoList,omitempty"` // 主要股东列表
	HolderTypeInfoList []*OwnershipStaticInfo `protobuf:"bytes,2,rep,name=holderTypeInfoList" json:"holderTypeInfoList,omitempty"` // 持股类型列表
	HoldingPeriodList  []*HoldingPeriodItem   `protobuf:"bytes,3,rep,name=holdingPeriodList" json:"holdingPeriodList,omitempty"`   // 可用报告期列表，仅当请求 periodId 为 0 时返回
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QotGetShareholdersOverviewResponse) Reset() {
	*x = QotGetShareholdersOverviewResponse{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetShareholdersOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetShareholdersOverviewResponse) ProtoMessage() {}

func (x *QotGetShareholdersOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetShareholdersOverviewResponse.ProtoReflect.Descriptor instead.
func (*QotGetShareholdersOverviewResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetShareholdersOverviewResponse) GetMainHolderInfoList() []*OwnershipStaticInfo {
	if x != nil {
		return x.MainHolderInfoList
	}
	return nil
}

func (x *QotGetShareholdersOverviewResponse) GetHolderTypeInfoList() []*OwnershipStaticInfo {
	if x != nil {
		return x.HolderTypeInfoList
	}
	return nil
}

func (x *QotGetShareholdersOverviewResponse) GetHoldingPeriodList() []*HoldingPeriodItem {
	if x != nil {
		return x.HoldingPeriodList
	}
	return nil
}

type QotGetShareholdersOverviewRequest_Internal struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Payload       *QotGetShareholdersOverviewRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetShareholdersOverviewRequest_Internal) Reset() {
	*x = QotGetShareholdersOverviewRequest_Internal{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetShareholdersOverviewRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetShareholdersOverviewRequest_Internal) ProtoMessage() {}

func (x *QotGetShareholdersOverviewRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetShareholdersOverviewRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetShareholdersOverviewRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{5}
}

func (x *QotGetShareholdersOverviewRequest_Internal) GetPayload() *QotGetShareholdersOverviewRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetShareholdersOverviewResponse_Internal struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	RetType       *RetType                            `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                             `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                              `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetShareholdersOverviewResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetShareholdersOverviewResponse_Internal fields.
const (
	Default_QotGetShareholdersOverviewResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetShareholdersOverviewResponse_Internal) Reset() {
	*x = QotGetShareholdersOverviewResponse_Internal{}
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetShareholdersOverviewResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetShareholdersOverviewResponse_Internal) ProtoMessage() {}

func (x *QotGetShareholdersOverviewResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetShareholdersOverview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetShareholdersOverviewResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetShareholdersOverviewResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetShareholdersOverview_proto_rawDescGZIP(), []int{6}
}

func (x *QotGetShareholdersOverviewResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetShareholdersOverviewResponse_Internal_RetType
}

func (x *QotGetShareholdersOverviewResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetShareholdersOverviewResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetShareholdersOverviewResponse_Internal) GetPayload() *QotGetShareholdersOverviewResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetShareholdersOverview_proto protoreflect.FileDescriptor

const file_Qot_GetShareholdersOverview_proto_rawDesc = "" +
	"\n" +
	"!Qot_GetShareholdersOverview.proto\x12\x06futupb\x1a\vTypes.proto\"c\n" +
	"\x13OwnershipStaticItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tholderPct\x18\x02 \x01(\x01R\tholderPct\x12\x1a\n" +
	"\bholderId\x18\x03 \x01(\x05R\bholderId\"\x94\x01\n" +
	"\x13OwnershipStaticInfo\x12\x1e\n" +
	"\n" +
	"staticDate\x18\x01 \x01(\x04R\n" +
	"staticDate\x12$\n" +
	"\rstaticDateStr\x18\x02 \x01(\tR\rstaticDateStr\x127\n" +
	"\bitemList\x18\x04 \x03(\v2\x1b.futupb.OwnershipStaticItemR\bitemList\"O\n" +
	"\x11HoldingPeriodItem\x12\x1e\n" +
	"\n" +
	"periodText\x18\x01 \x01(\tR\n" +
	"periodText\x12\x1a\n" +
	"\bperiodId\x18\x02 \x01(\x05R\bperiodId\"m\n" +
	"!QotGetShareholdersOverviewRequest\x12,\n" +
	"\bsecurity\x18\x01 \x02(\v2\x10.futupb.SecurityR\bsecurity\x12\x1a\n" +
	"\bperiodId\x18\x03 \x01(\x05R\bperiodId\"\x87\x02\n" +
	"\"QotGetShareholdersOverviewResponse\x12K\n" +
	"\x12mainHolderInfoList\x18\x01 \x03(\v2\x1b.futupb.OwnershipStaticInfoR\x12mainHolderInfoList\x12K\n" +
	"\x12holderTypeInfoList\x18\x02 \x03(\v2\x1b.futupb.OwnershipStaticInfoR\x12holderTypeInfoList\x12G\n" +
	"\x11holdingPeriodList\x18\x03 \x03(\v2\x19.futupb.HoldingPeriodItemR\x11holdingPeriodList\"q\n" +
	"*QotGetShareholdersOverviewRequest_Internal\x12C\n" +
	"\apayload\x18\x01 \x02(\v2).futupb.QotGetShareholdersOverviewRequestR\apayload\"\xe1\x01\n" +
	"+QotGetShareholdersOverviewResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12D\n" +
	"\apayload\x18\x04 \x01(\v2*.futupb.QotGetShareholdersOverviewResponseR\apayloadB\x1fZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetShareholdersOverview_proto_rawDescOnce sync.Once
	file_Qot_GetShareholdersOverview_proto_rawDescData []byte
)

func file_Qot_GetShareholdersOverview_proto_rawDescGZIP() []byte {
	file_Qot_GetShareholdersOverview_proto_rawDescOnce.Do(func() {
		file_Qot_GetShareholdersOverview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetShareholdersOverview_proto_rawDesc), len(file_Qot_GetShareholdersOverview_proto_rawDesc)))
	})
	return file_Qot_GetShareholdersOverview_proto_rawDescData
}

var file_Qot_GetShareholdersOverview_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Qot_GetShareholdersOverview_proto_goTypes = []any{
	(*OwnershipStaticItem)(nil),                         // 0: futupb.OwnershipStaticItem
	(*OwnershipStaticInfo)(nil),                         // 1: futupb.OwnershipStaticInfo
	(*HoldingPeriodItem)(nil),                           // 2: futupb.HoldingPeriodItem
	(*QotGetShareholdersOverviewRequest)(nil),           // 3: futupb.QotGetShareholdersOverviewRequest
	(*QotGetShareholdersOverviewResponse)(nil),          // 4: futupb.QotGetShareholdersOverviewResponse
	(*QotGetShareholdersOverviewRequest_Internal)(nil),  // 5: futupb.QotGetShareholdersOverviewRequest_Internal
	(*QotGetShareholdersOverviewResponse_Internal)(nil), // 6: futupb.QotGetShareholdersOverviewResponse_Internal
	(*Security)(nil),                                    // 7: futupb.Security
	(RetType)(0),                                        // 8: futupb.RetType
}
var file_Qot_GetShareholdersOverview_proto_depIdxs = []int32{
	0, // 0: futupb.OwnershipStaticInfo.itemList:type_name -> futupb.OwnershipStaticItem
	7, // 1: futupb.QotGetShareholdersOverviewRequest.security:type_name -> futupb.Security
	1, // 2: futupb.QotGetShareholdersOverviewResponse.mainHolderInfoList:type_name -> futupb.OwnershipStaticInfo
	1, // 3: futupb.QotGetShareholdersOverviewResponse.holderTypeInfoList:type_name -> futupb.OwnershipStaticInfo
	2, // 4: futupb.QotGetShareholdersOverviewResponse.holdingPeriodList:type_name -> futupb.HoldingPeriodItem
	3, // 5: futupb.QotGetShareholdersOverviewRequest_Internal.payload:type_name -> futupb.QotGetShareholdersOverviewRequest
	8, // 6: futupb.QotGetShareholdersOverviewResponse_Internal.retType:type_name -> futupb.RetType
	4, // 7: futupb.QotGetShareholdersOverviewResponse_Internal.payload:type_name -> futupb.QotGetShareholdersOverviewResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Qot_GetShareholdersOverview_proto_init() }
func file_Qot_GetShareholdersOverview_proto_init() {
	if File_Qot_GetShareholdersOverview_proto != nil {
		return
	}
	file_Types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetShareholdersOverview_proto_rawDesc), len(file_Qot_GetShareholdersOverview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetShareholdersOverview_proto_goTypes,
		DependencyIndexes: file_Qot_GetShareholdersOverview_proto_depIdxs,
		MessageInfos:      file_Qot_GetShareholdersOverview_proto_msgTypes,
	}.Build()
	File_Qot_GetShareholdersOverview_proto = out.File
	file_Qot_GetShareholdersOverview_proto_goTypes = nil
	file_Qot_GetShareholdersOverview_proto_depIdxs = nil
}
