// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Qot_GetOptionStrategy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个期权策略组合
type OptionStrategyItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           *string                `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`                                                                           //组合策略代码
	Name           *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`                                                                           //组合策略名称
	OptionStrategy *OptionStrategyType    `protobuf:"varint,3,req,name=option_strategy,json=optionStrategy,enum=futupb.OptionStrategyType" json:"option_strategy,omitempty"` //OptionStrategyType，组合策略类型
	StockOwner     *Security              `protobuf:"bytes,4,req,name=stock_owner,json=stockOwner" json:"stock_owner,omitempty"`                                             //标的股
	MultiLegs      []*ComboLeg            `protobuf:"bytes,5,rep,name=multi_legs,json=multiLegs" json:"multi_legs,omitempty"`                                                //组合子订单列表（multi_legs）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptionStrategyItem) Reset() {
	*x = OptionStrategyItem{}
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionStrategyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionStrategyItem) ProtoMessage() {}

func (x *OptionStrategyItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionStrategyItem.ProtoReflect.Descriptor instead.
func (*OptionStrategyItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionStrategy_proto_rawDescGZIP(), []int{0}
}

func (x *OptionStrategyItem) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *OptionStrategyItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OptionStrategyItem) GetOptionStrategy() OptionStrategyType {
	if x != nil && x.OptionStrategy != nil {
		return *x.OptionStrategy
	}
	return OptionStrategyType_OptionStrategyType_Unknown
}

func (x *OptionStrategyItem) GetStockOwner() *Security {
	if x != nil {
		return x.StockOwner
	}
	return nil
}

func (x *OptionStrategyItem) GetMultiLegs() []*ComboLeg {
	if x != nil {
		return x.MultiLegs
	}
	return nil
}

type QotGetOptionStrategyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           *Security              `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`                                                                           //期权标的股，目前仅支持港美正股以及恒指国指
	OptionStrategy  *OptionStrategyType    `protobuf:"varint,2,req,name=option_strategy,json=optionStrategy,enum=futupb.OptionStrategyType" json:"option_strategy,omitempty"`   //OptionStrategyType，期权策略类型
	ExpireTime      *string                `protobuf:"bytes,3,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`                                               //到期日（近端到期日）
	FarExpireTime   *string                `protobuf:"bytes,4,opt,name=far_expire_time,json=farExpireTime" json:"far_expire_time,omitempty"`                                    //远端到期日，对角策略（DiagonalSpread）时使用
	Spread          *float64               `protobuf:"fixed64,5,opt,name=spread" json:"spread,omitempty"`                                                                       //价差筛选值，仅对价差类策略有效，不填表示返回所有
	OptionType      *OptionType            `protobuf:"varint,6,opt,name=option_type,json=optionType,enum=futupb.OptionType" json:"option_type,omitempty"`                       //Qot_Common.OptionType，期权类型，不填表示都返回
	StrikePrice     *float64               `protobuf:"fixed64,7,opt,name=strike_price,json=strikePrice" json:"strike_price,omitempty"`                                          //行权价筛选，不填表示返回所有行权价
	IndexOptionType *IndexOptionType       `protobuf:"varint,8,opt,name=index_option_type,json=indexOptionType,enum=futupb.IndexOptionType" json:"index_option_type,omitempty"` //Qot_Common.IndexOptionType，指数期权类型，仅用于恒指国指
	Header          *QotHeader             `protobuf:"bytes,100,opt,name=header" json:"header,omitempty"`                                                                       //行情公共参数头
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QotGetOptionStrategyRequest) Reset() {
	*x = QotGetOptionStrategyRequest{}
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetOptionStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetOptionStrategyRequest) ProtoMessage() {}

func (x *QotGetOptionStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetOptionStrategyRequest.ProtoReflect.Descriptor instead.
func (*QotGetOptionStrategyRequest) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionStrategy_proto_rawDescGZIP(), []int{1}
}

func (x *QotGetOptionStrategyRequest) GetOwner() *Security {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *QotGetOptionStrategyRequest) GetOptionStrategy() OptionStrategyType {
	if x != nil && x.OptionStrategy != nil {
		return *x.OptionStrategy
	}
	return OptionStrategyType_OptionStrategyType_Unknown
}

func (x *QotGetOptionStrategyRequest) GetExpireTime() string {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return ""
}

func (x *QotGetOptionStrategyRequest) GetFarExpireTime() string {
	if x != nil && x.FarExpireTime != nil {
		return *x.FarExpireTime
	}
	return ""
}

func (x *QotGetOptionStrategyRequest) GetSpread() float64 {
	if x != nil && x.Spread != nil {
		return *x.Spread
	}
	return 0
}

func (x *QotGetOptionStrategyRequest) GetOptionType() OptionType {
	if x != nil && x.OptionType != nil {
		return *x.OptionType
	}
	return OptionType_OptionType_Unknown
}

func (x *QotGetOptionStrategyRequest) GetStrikePrice() float64 {
	if x != nil && x.StrikePrice != nil {
		return *x.StrikePrice
	}
	return 0
}

func (x *QotGetOptionStrategyRequest) GetIndexOptionType() IndexOptionType {
	if x != nil && x.IndexOptionType != nil {
		return *x.IndexOptionType
	}
	return IndexOptionType_IndexOptionType_Unknown
}

func (x *QotGetOptionStrategyRequest) GetHeader() *QotHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type QotGetOptionStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyList  []*OptionStrategyItem  `protobuf:"bytes,1,rep,name=strategyList" json:"strategyList,omitempty"` //期权策略组合列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetOptionStrategyResponse) Reset() {
	*x = QotGetOptionStrategyResponse{}
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetOptionStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetOptionStrategyResponse) ProtoMessage() {}

func (x *QotGetOptionStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetOptionStrategyResponse.ProtoReflect.Descriptor instead.
func (*QotGetOptionStrategyResponse) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionStrategy_proto_rawDescGZIP(), []int{2}
}

func (x *QotGetOptionStrategyResponse) GetStrategyList() []*OptionStrategyItem {
	if x != nil {
		return x.StrategyList
	}
	return nil
}

type QotGetOptionStrategyRequest_Internal struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Payload       *QotGetOptionStrategyRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QotGetOptionStrategyRequest_Internal) Reset() {
	*x = QotGetOptionStrategyRequest_Internal{}
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetOptionStrategyRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetOptionStrategyRequest_Internal) ProtoMessage() {}

func (x *QotGetOptionStrategyRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetOptionStrategyRequest_Internal.ProtoReflect.Descriptor instead.
func (*QotGetOptionStrategyRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionStrategy_proto_rawDescGZIP(), []int{3}
}

func (x *QotGetOptionStrategyRequest_Internal) GetPayload() *QotGetOptionStrategyRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QotGetOptionStrategyResponse_Internal struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	RetType       *RetType                      `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                       `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                        `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *QotGetOptionStrategyResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for QotGetOptionStrategyResponse_Internal fields.
const (
	Default_QotGetOptionStrategyResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *QotGetOptionStrategyResponse_Internal) Reset() {
	*x = QotGetOptionStrategyResponse_Internal{}
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotGetOptionStrategyResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotGetOptionStrategyResponse_Internal) ProtoMessage() {}

func (x *QotGetOptionStrategyResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionStrategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotGetOptionStrategyResponse_Internal.ProtoReflect.Descriptor instead.
func (*QotGetOptionStrategyResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionStrategy_proto_rawDescGZIP(), []int{4}
}

func (x *QotGetOptionStrategyResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_QotGetOptionStrategyResponse_Internal_RetType
}

func (x *QotGetOptionStrategyResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *QotGetOptionStrategyResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *QotGetOptionStrategyResponse_Internal) GetPayload() *QotGetOptionStrategyResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Qot_GetOptionStrategy_proto protoreflect.FileDescriptor

const file_Qot_GetOptionStrategy_proto_rawDesc = "" +
	"\n" +
	"\x1bQot_GetOptionStrategy.proto\x12\x06futupb\x1a\vTypes.proto\"\xe5\x01\n" +
	"\x12OptionStrategyItem\x12\x12\n" +
	"\x04code\x18\x01 \x02(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12C\n" +
	"\x0foption_strategy\x18\x03 \x02(\x0e2\x1a.futupb.OptionStrategyTypeR\x0eoptionStrategy\x121\n" +
	"\vstock_owner\x18\x04 \x02(\v2\x10.futupb.SecurityR\n" +
	"stockOwner\x12/\n" +
	"\n" +
	"multi_legs\x18\x05 \x03(\v2\x10.futupb.ComboLegR\tmultiLegs\"\xb3\x03\n" +
	"\x1bQotGetOptionStrategyRequest\x12&\n" +
	"\x05owner\x18\x01 \x02(\v2\x10.futupb.SecurityR\x05owner\x12C\n" +
	"\x0foption_strategy\x18\x02 \x02(\x0e2\x1a.futupb.OptionStrategyTypeR\x0eoptionStrategy\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\tR\n" +
	"expireTime\x12&\n" +
	"\x0ffar_expire_time\x18\x04 \x01(\tR\rfarExpireTime\x12\x16\n" +
	"\x06spread\x18\x05 \x01(\x01R\x06spread\x123\n" +
	"\voption_type\x18\x06 \x01(\x0e2\x12.futupb.OptionTypeR\n" +
	"optionType\x12!\n" +
	"\fstrike_price\x18\a \x01(\x01R\vstrikePrice\x12C\n" +
	"\x11index_option_type\x18\b \x01(\x0e2\x17.futupb.IndexOptionTypeR\x0findexOptionType\x12)\n" +
	"\x06header\x18d \x01(\v2\x11.futupb.QotHeaderR\x06header\"^\n" +
	"\x1cQotGetOptionStrategyResponse\x12>\n" +
	"\fstrategyList\x18\x01 \x03(\v2\x1a.futupb.OptionStrategyItemR\fstrategyList\"e\n" +
	"$QotGetOptionStrategyRequest_Internal\x12=\n" +
	"\apayload\x18\x01 \x02(\v2#.futupb.QotGetOptionStrategyRequestR\apayload\"\xd5\x01\n" +
	"%QotGetOptionStrategyResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12>\n" +
	"\apayload\x18\x04 \x01(\v2$.futupb.QotGetOptionStrategyResponseR\apayloadB\x1fZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Qot_GetOptionStrategy_proto_rawDescOnce sync.Once
	file_Qot_GetOptionStrategy_proto_rawDescData []byte
)

func file_Qot_GetOptionStrategy_proto_rawDescGZIP() []byte {
	file_Qot_GetOptionStrategy_proto_rawDescOnce.Do(func() {
		file_Qot_GetOptionStrategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetOptionStrategy_proto_rawDesc), len(file_Qot_GetOptionStrategy_proto_rawDesc)))
	})
	return file_Qot_GetOptionStrategy_proto_rawDescData
}

var file_Qot_GetOptionStrategy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetOptionStrategy_proto_goTypes = []any{
	(*OptionStrategyItem)(nil),                    // 0: futupb.OptionStrategyItem
	(*QotGetOptionStrategyRequest)(nil),           // 1: futupb.QotGetOptionStrategyRequest
	(*QotGetOptionStrategyResponse)(nil),          // 2: futupb.QotGetOptionStrategyResponse
	(*QotGetOptionStrategyRequest_Internal)(nil),  // 3: futupb.QotGetOptionStrategyRequest_Internal
	(*QotGetOptionStrategyResponse_Internal)(nil), // 4: futupb.QotGetOptionStrategyResponse_Internal
	(OptionStrategyType)(0),                       // 5: futupb.OptionStrategyType
	(*Security)(nil),                              // 6: futupb.Security
	(*ComboLeg)(nil),                              // 7: futupb.ComboLeg
	(OptionType)(0),                               // 8: futupb.OptionType
	(IndexOptionType)(0),                          // 9: futupb.IndexOptionType
	(*QotHeader)(nil),                             // 10: futupb.QotHeader
	(RetType)(0),                                  // 11: futupb.RetType
}
var file_Qot_GetOptionStrategy_proto_depIdxs = []int32{
	5,  // 0: futupb.OptionStrategyItem.option_strategy:type_name -> futupb.OptionStrategyType
	6,  // 1: futupb.OptionStrategyItem.stock_owner:type_name -> futupb.Security
	7,  // 2: futupb.OptionStrategyItem.multi_legs:type_name -> futupb.ComboLeg
	6,  // 3: futupb.QotGetOptionStrategyRequest.owner:type_name -> futupb.Security
	5,  // 4: futupb.QotGetOptionStrategyRequest.option_strategy:type_name -> futupb.OptionStrategyType
	8,  // 5: futupb.QotGetOptionStrategyRequest.option_type:type_name -> futupb.OptionType
	9,  // 6: futupb.QotGetOptionStrategyRequest.index_option_type:type_name -> futupb.IndexOptionType
	10, // 7: futupb.QotGetOptionStrategyRequest.header:type_name -> futupb.QotHeader
	0,  // 8: futupb.QotGetOptionStrategyResponse.strategyList:type_name -> futupb.OptionStrategyItem
	1,  // 9: futupb.QotGetOptionStrategyRequest_Internal.payload:type_name -> futupb.QotGetOptionStrategyRequest
	11, // 10: futupb.QotGetOptionStrategyResponse_Internal.retType:type_name -> futupb.RetType
	2,  // 11: futupb.QotGetOptionStrategyResponse_Internal.payload:type_name -> futupb.QotGetOptionStrategyResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_Qot_GetOptionStrategy_proto_init() }
func file_Qot_GetOptionStrategy_proto_init() {
	if File_Qot_GetOptionStrategy_proto != nil {
		return
	}
	file_Types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetOptionStrategy_proto_rawDesc), len(file_Qot_GetOptionStrategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetOptionStrategy_proto_goTypes,
		DependencyIndexes: file_Qot_GetOptionStrategy_proto_depIdxs,
		MessageInfos:      file_Qot_GetOptionStrategy_proto_msgTypes,
	}.Build()
	File_Qot_GetOptionStrategy_proto = out.File
	file_Qot_GetOptionStrategy_proto_goTypes = nil
	file_Qot_GetOptionStrategy_proto_depIdxs = nil
}
