// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: TestCmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 内部使用
type TestCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           *string                `protobuf:"bytes,1,req,name=cmd" json:"cmd,omitempty"`
	Params        *string                `protobuf:"bytes,2,opt,name=params" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCmdRequest) Reset() {
	*x = TestCmdRequest{}
	mi := &file_TestCmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCmdRequest) ProtoMessage() {}

func (x *TestCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TestCmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCmdRequest.ProtoReflect.Descriptor instead.
func (*TestCmdRequest) Descriptor() ([]byte, []int) {
	return file_TestCmd_proto_rawDescGZIP(), []int{0}
}

func (x *TestCmdRequest) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

func (x *TestCmdRequest) GetParams() string {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	return ""
}

type TestCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           *string                `protobuf:"bytes,1,req,name=cmd" json:"cmd,omitempty"`
	Result        *string                `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCmdResponse) Reset() {
	*x = TestCmdResponse{}
	mi := &file_TestCmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCmdResponse) ProtoMessage() {}

func (x *TestCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TestCmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCmdResponse.ProtoReflect.Descriptor instead.
func (*TestCmdResponse) Descriptor() ([]byte, []int) {
	return file_TestCmd_proto_rawDescGZIP(), []int{1}
}

func (x *TestCmdResponse) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

func (x *TestCmdResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type TestCmdRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TestCmdRequest        `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCmdRequest_Internal) Reset() {
	*x = TestCmdRequest_Internal{}
	mi := &file_TestCmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCmdRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCmdRequest_Internal) ProtoMessage() {}

func (x *TestCmdRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_TestCmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCmdRequest_Internal.ProtoReflect.Descriptor instead.
func (*TestCmdRequest_Internal) Descriptor() ([]byte, []int) {
	return file_TestCmd_proto_rawDescGZIP(), []int{2}
}

func (x *TestCmdRequest_Internal) GetPayload() *TestCmdRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TestCmdResponse_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //返回结果，参见Common.RetType的枚举定义
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`             //返回结果描述
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`          //错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
	Payload       *TestCmdResponse       `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TestCmdResponse_Internal fields.
const (
	Default_TestCmdResponse_Internal_RetType = int32(-400)
)

func (x *TestCmdResponse_Internal) Reset() {
	*x = TestCmdResponse_Internal{}
	mi := &file_TestCmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCmdResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCmdResponse_Internal) ProtoMessage() {}

func (x *TestCmdResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_TestCmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCmdResponse_Internal.ProtoReflect.Descriptor instead.
func (*TestCmdResponse_Internal) Descriptor() ([]byte, []int) {
	return file_TestCmd_proto_rawDescGZIP(), []int{3}
}

func (x *TestCmdResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_TestCmdResponse_Internal_RetType
}

func (x *TestCmdResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *TestCmdResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *TestCmdResponse_Internal) GetPayload() *TestCmdResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_TestCmd_proto protoreflect.FileDescriptor

const file_TestCmd_proto_rawDesc = "" +
	"\n" +
	"\rTestCmd.proto\x12\x06futupb\":\n" +
	"\x0eTestCmdRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x02(\tR\x03cmd\x12\x16\n" +
	"\x06params\x18\x02 \x01(\tR\x06params\";\n" +
	"\x0fTestCmdResponse\x12\x10\n" +
	"\x03cmd\x18\x01 \x02(\tR\x03cmd\x12\x16\n" +
	"\x06result\x18\x02 \x02(\tR\x06result\"K\n" +
	"\x17TestCmdRequest_Internal\x120\n" +
	"\apayload\x18\x01 \x02(\v2\x16.futupb.TestCmdRequestR\apayload\"\x9f\x01\n" +
	"\x18TestCmdResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.futupb.TestCmdResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_TestCmd_proto_rawDescOnce sync.Once
	file_TestCmd_proto_rawDescData []byte
)

func file_TestCmd_proto_rawDescGZIP() []byte {
	file_TestCmd_proto_rawDescOnce.Do(func() {
		file_TestCmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TestCmd_proto_rawDesc), len(file_TestCmd_proto_rawDesc)))
	})
	return file_TestCmd_proto_rawDescData
}

var file_TestCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_TestCmd_proto_goTypes = []any{
	(*TestCmdRequest)(nil),           // 0: futupb.TestCmdRequest
	(*TestCmdResponse)(nil),          // 1: futupb.TestCmdResponse
	(*TestCmdRequest_Internal)(nil),  // 2: futupb.TestCmdRequest_Internal
	(*TestCmdResponse_Internal)(nil), // 3: futupb.TestCmdResponse_Internal
}
var file_TestCmd_proto_depIdxs = []int32{
	0, // 0: futupb.TestCmdRequest_Internal.payload:type_name -> futupb.TestCmdRequest
	1, // 1: futupb.TestCmdResponse_Internal.payload:type_name -> futupb.TestCmdResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TestCmd_proto_init() }
func file_TestCmd_proto_init() {
	if File_TestCmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TestCmd_proto_rawDesc), len(file_TestCmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TestCmd_proto_goTypes,
		DependencyIndexes: file_TestCmd_proto_depIdxs,
		MessageInfos:      file_TestCmd_proto_msgTypes,
	}.Build()
	File_TestCmd_proto = out.File
	file_TestCmd_proto_goTypes = nil
	file_TestCmd_proto_depIdxs = nil
}
