// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Trd_GetHistoryOrderList.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrdGetHistoryOrderListRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Header           *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`                                              //交易公共参数头
	FilterConditions *TrdFilterConditions   `protobuf:"bytes,2,req,name=filterConditions" json:"filterConditions,omitempty"`                          //过滤条件
	FilterStatusList []OrderStatus          `protobuf:"varint,3,rep,name=filterStatusList,enum=futupb.OrderStatus" json:"filterStatusList,omitempty"` //需要过滤的订单状态列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrdGetHistoryOrderListRequest) Reset() {
	*x = TrdGetHistoryOrderListRequest{}
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetHistoryOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetHistoryOrderListRequest) ProtoMessage() {}

func (x *TrdGetHistoryOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetHistoryOrderListRequest.ProtoReflect.Descriptor instead.
func (*TrdGetHistoryOrderListRequest) Descriptor() ([]byte, []int) {
	return file_Trd_GetHistoryOrderList_proto_rawDescGZIP(), []int{0}
}

func (x *TrdGetHistoryOrderListRequest) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdGetHistoryOrderListRequest) GetFilterConditions() *TrdFilterConditions {
	if x != nil {
		return x.FilterConditions
	}
	return nil
}

func (x *TrdGetHistoryOrderListRequest) GetFilterStatusList() []OrderStatus {
	if x != nil {
		return x.FilterStatusList
	}
	return nil
}

type TrdGetHistoryOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`       //交易公共参数头
	OrderList     []*Order               `protobuf:"bytes,2,rep,name=orderList" json:"orderList,omitempty"` //历史订单列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdGetHistoryOrderListResponse) Reset() {
	*x = TrdGetHistoryOrderListResponse{}
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetHistoryOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetHistoryOrderListResponse) ProtoMessage() {}

func (x *TrdGetHistoryOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetHistoryOrderListResponse.ProtoReflect.Descriptor instead.
func (*TrdGetHistoryOrderListResponse) Descriptor() ([]byte, []int) {
	return file_Trd_GetHistoryOrderList_proto_rawDescGZIP(), []int{1}
}

func (x *TrdGetHistoryOrderListResponse) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdGetHistoryOrderListResponse) GetOrderList() []*Order {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type TrdGetHistoryOrderListRequest_Internal struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payload       *TrdGetHistoryOrderListRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdGetHistoryOrderListRequest_Internal) Reset() {
	*x = TrdGetHistoryOrderListRequest_Internal{}
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetHistoryOrderListRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetHistoryOrderListRequest_Internal) ProtoMessage() {}

func (x *TrdGetHistoryOrderListRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetHistoryOrderListRequest_Internal.ProtoReflect.Descriptor instead.
func (*TrdGetHistoryOrderListRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_GetHistoryOrderList_proto_rawDescGZIP(), []int{2}
}

func (x *TrdGetHistoryOrderListRequest_Internal) GetPayload() *TrdGetHistoryOrderListRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrdGetHistoryOrderListResponse_Internal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *RetType                        `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                         `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                          `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *TrdGetHistoryOrderListResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TrdGetHistoryOrderListResponse_Internal fields.
const (
	Default_TrdGetHistoryOrderListResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *TrdGetHistoryOrderListResponse_Internal) Reset() {
	*x = TrdGetHistoryOrderListResponse_Internal{}
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetHistoryOrderListResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetHistoryOrderListResponse_Internal) ProtoMessage() {}

func (x *TrdGetHistoryOrderListResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetHistoryOrderList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetHistoryOrderListResponse_Internal.ProtoReflect.Descriptor instead.
func (*TrdGetHistoryOrderListResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_GetHistoryOrderList_proto_rawDescGZIP(), []int{3}
}

func (x *TrdGetHistoryOrderListResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_TrdGetHistoryOrderListResponse_Internal_RetType
}

func (x *TrdGetHistoryOrderListResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *TrdGetHistoryOrderListResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *TrdGetHistoryOrderListResponse_Internal) GetPayload() *TrdGetHistoryOrderListResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Trd_GetHistoryOrderList_proto protoreflect.FileDescriptor

const file_Trd_GetHistoryOrderList_proto_rawDesc = "" +
	"\n" +
	"\x1dTrd_GetHistoryOrderList.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Trd_Common.proto\"\xd4\x01\n" +
	"\x1dTrdGetHistoryOrderListRequest\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12G\n" +
	"\x10filterConditions\x18\x02 \x02(\v2\x1b.futupb.TrdFilterConditionsR\x10filterConditions\x12?\n" +
	"\x10filterStatusList\x18\x03 \x03(\x0e2\x13.futupb.OrderStatusR\x10filterStatusList\"x\n" +
	"\x1eTrdGetHistoryOrderListResponse\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12+\n" +
	"\torderList\x18\x02 \x03(\v2\r.futupb.OrderR\torderList\"i\n" +
	"&TrdGetHistoryOrderListRequest_Internal\x12?\n" +
	"\apayload\x18\x01 \x02(\v2%.futupb.TrdGetHistoryOrderListRequestR\apayload\"\xd9\x01\n" +
	"'TrdGetHistoryOrderListResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12@\n" +
	"\apayload\x18\x04 \x01(\v2&.futupb.TrdGetHistoryOrderListResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Trd_GetHistoryOrderList_proto_rawDescOnce sync.Once
	file_Trd_GetHistoryOrderList_proto_rawDescData []byte
)

func file_Trd_GetHistoryOrderList_proto_rawDescGZIP() []byte {
	file_Trd_GetHistoryOrderList_proto_rawDescOnce.Do(func() {
		file_Trd_GetHistoryOrderList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_GetHistoryOrderList_proto_rawDesc), len(file_Trd_GetHistoryOrderList_proto_rawDesc)))
	})
	return file_Trd_GetHistoryOrderList_proto_rawDescData
}

var file_Trd_GetHistoryOrderList_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trd_GetHistoryOrderList_proto_goTypes = []any{
	(*TrdGetHistoryOrderListRequest)(nil),           // 0: futupb.TrdGetHistoryOrderListRequest
	(*TrdGetHistoryOrderListResponse)(nil),          // 1: futupb.TrdGetHistoryOrderListResponse
	(*TrdGetHistoryOrderListRequest_Internal)(nil),  // 2: futupb.TrdGetHistoryOrderListRequest_Internal
	(*TrdGetHistoryOrderListResponse_Internal)(nil), // 3: futupb.TrdGetHistoryOrderListResponse_Internal
	(*TrdHeader)(nil),                               // 4: futupb.TrdHeader
	(*TrdFilterConditions)(nil),                     // 5: futupb.TrdFilterConditions
	(OrderStatus)(0),                                // 6: futupb.OrderStatus
	(*Order)(nil),                                   // 7: futupb.Order
	(RetType)(0),                                    // 8: futupb.RetType
}
var file_Trd_GetHistoryOrderList_proto_depIdxs = []int32{
	4, // 0: futupb.TrdGetHistoryOrderListRequest.header:type_name -> futupb.TrdHeader
	5, // 1: futupb.TrdGetHistoryOrderListRequest.filterConditions:type_name -> futupb.TrdFilterConditions
	6, // 2: futupb.TrdGetHistoryOrderListRequest.filterStatusList:type_name -> futupb.OrderStatus
	4, // 3: futupb.TrdGetHistoryOrderListResponse.header:type_name -> futupb.TrdHeader
	7, // 4: futupb.TrdGetHistoryOrderListResponse.orderList:type_name -> futupb.Order
	0, // 5: futupb.TrdGetHistoryOrderListRequest_Internal.payload:type_name -> futupb.TrdGetHistoryOrderListRequest
	8, // 6: futupb.TrdGetHistoryOrderListResponse_Internal.retType:type_name -> futupb.RetType
	1, // 7: futupb.TrdGetHistoryOrderListResponse_Internal.payload:type_name -> futupb.TrdGetHistoryOrderListResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Trd_GetHistoryOrderList_proto_init() }
func file_Trd_GetHistoryOrderList_proto_init() {
	if File_Trd_GetHistoryOrderList_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Trd_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_GetHistoryOrderList_proto_rawDesc), len(file_Trd_GetHistoryOrderList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_GetHistoryOrderList_proto_goTypes,
		DependencyIndexes: file_Trd_GetHistoryOrderList_proto_depIdxs,
		MessageInfos:      file_Trd_GetHistoryOrderList_proto_msgTypes,
	}.Build()
	File_Trd_GetHistoryOrderList_proto = out.File
	file_Trd_GetHistoryOrderList_proto_goTypes = nil
	file_Trd_GetHistoryOrderList_proto_depIdxs = nil
}
