// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Trd_FlowSummary.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrdCashFlowDirection int32

const (
	TrdCashFlowDirection_TrdCashFlowDirection_Unknown TrdCashFlowDirection = 0 //未知
	TrdCashFlowDirection_TrdCashFlowDirection_In      TrdCashFlowDirection = 1 //现金流入
	TrdCashFlowDirection_TrdCashFlowDirection_Out     TrdCashFlowDirection = 2 //现金流出
)

// Enum value maps for TrdCashFlowDirection.
var (
	TrdCashFlowDirection_name = map[int32]string{
		0: "TrdCashFlowDirection_Unknown",
		1: "TrdCashFlowDirection_In",
		2: "TrdCashFlowDirection_Out",
	}
	TrdCashFlowDirection_value = map[string]int32{
		"TrdCashFlowDirection_Unknown": 0,
		"TrdCashFlowDirection_In":      1,
		"TrdCashFlowDirection_Out":     2,
	}
)

func (x TrdCashFlowDirection) Enum() *TrdCashFlowDirection {
	p := new(TrdCashFlowDirection)
	*p = x
	return p
}

func (x TrdCashFlowDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrdCashFlowDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_Trd_FlowSummary_proto_enumTypes[0].Descriptor()
}

func (TrdCashFlowDirection) Type() protoreflect.EnumType {
	return &file_Trd_FlowSummary_proto_enumTypes[0]
}

func (x TrdCashFlowDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TrdCashFlowDirection) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TrdCashFlowDirection(num)
	return nil
}

// Deprecated: Use TrdCashFlowDirection.Descriptor instead.
func (TrdCashFlowDirection) EnumDescriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{0}
}

type FlowSummaryInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClearingDate      *string                `protobuf:"bytes,1,opt,name=clearingDate" json:"clearingDate,omitempty"`            //清算日期
	SettlementDate    *string                `protobuf:"bytes,2,opt,name=settlementDate" json:"settlementDate,omitempty"`        //结算日期
	Currency          *int32                 `protobuf:"varint,3,opt,name=currency" json:"currency,omitempty"`                   //币种
	CashFlowType      *string                `protobuf:"bytes,4,opt,name=cashFlowType" json:"cashFlowType,omitempty"`            //现金流类型
	CashFlowDirection *int32                 `protobuf:"varint,5,opt,name=cashFlowDirection" json:"cashFlowDirection,omitempty"` //现金流方向 TrdCashFlowDirection
	CashFlowAmount    *float64               `protobuf:"fixed64,6,opt,name=cashFlowAmount" json:"cashFlowAmount,omitempty"`      //金额
	CashFlowRemark    *string                `protobuf:"bytes,7,opt,name=cashFlowRemark" json:"cashFlowRemark,omitempty"`        // 备注
	CashFlowID        *uint64                `protobuf:"varint,8,opt,name=cashFlowID" json:"cashFlowID,omitempty"`               // 现金流ID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlowSummaryInfo) Reset() {
	*x = FlowSummaryInfo{}
	mi := &file_Trd_FlowSummary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSummaryInfo) ProtoMessage() {}

func (x *FlowSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_FlowSummary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSummaryInfo.ProtoReflect.Descriptor instead.
func (*FlowSummaryInfo) Descriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{0}
}

func (x *FlowSummaryInfo) GetClearingDate() string {
	if x != nil && x.ClearingDate != nil {
		return *x.ClearingDate
	}
	return ""
}

func (x *FlowSummaryInfo) GetSettlementDate() string {
	if x != nil && x.SettlementDate != nil {
		return *x.SettlementDate
	}
	return ""
}

func (x *FlowSummaryInfo) GetCurrency() int32 {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return 0
}

func (x *FlowSummaryInfo) GetCashFlowType() string {
	if x != nil && x.CashFlowType != nil {
		return *x.CashFlowType
	}
	return ""
}

func (x *FlowSummaryInfo) GetCashFlowDirection() int32 {
	if x != nil && x.CashFlowDirection != nil {
		return *x.CashFlowDirection
	}
	return 0
}

func (x *FlowSummaryInfo) GetCashFlowAmount() float64 {
	if x != nil && x.CashFlowAmount != nil {
		return *x.CashFlowAmount
	}
	return 0
}

func (x *FlowSummaryInfo) GetCashFlowRemark() string {
	if x != nil && x.CashFlowRemark != nil {
		return *x.CashFlowRemark
	}
	return ""
}

func (x *FlowSummaryInfo) GetCashFlowID() uint64 {
	if x != nil && x.CashFlowID != nil {
		return *x.CashFlowID
	}
	return 0
}

type TrdFlowSummaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`                        //交易公共参数头
	ClearingDate      *string                `protobuf:"bytes,2,req,name=clearingDate" json:"clearingDate,omitempty"`            //清算日期，格式 "2017-05-20"
	CashFlowDirection *int32                 `protobuf:"varint,3,opt,name=cashFlowDirection" json:"cashFlowDirection,omitempty"` //现金流方向 TrdCashFlowDirection
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrdFlowSummaryRequest) Reset() {
	*x = TrdFlowSummaryRequest{}
	mi := &file_Trd_FlowSummary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdFlowSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdFlowSummaryRequest) ProtoMessage() {}

func (x *TrdFlowSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_FlowSummary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdFlowSummaryRequest.ProtoReflect.Descriptor instead.
func (*TrdFlowSummaryRequest) Descriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{1}
}

func (x *TrdFlowSummaryRequest) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdFlowSummaryRequest) GetClearingDate() string {
	if x != nil && x.ClearingDate != nil {
		return *x.ClearingDate
	}
	return ""
}

func (x *TrdFlowSummaryRequest) GetCashFlowDirection() int32 {
	if x != nil && x.CashFlowDirection != nil {
		return *x.CashFlowDirection
	}
	return 0
}

type TrdFlowSummaryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Header              *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`                           //交易公共参数头
	FlowSummaryInfoList []*FlowSummaryInfo     `protobuf:"bytes,2,rep,name=flowSummaryInfoList" json:"flowSummaryInfoList,omitempty"` //账户资金
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrdFlowSummaryResponse) Reset() {
	*x = TrdFlowSummaryResponse{}
	mi := &file_Trd_FlowSummary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdFlowSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdFlowSummaryResponse) ProtoMessage() {}

func (x *TrdFlowSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_FlowSummary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdFlowSummaryResponse.ProtoReflect.Descriptor instead.
func (*TrdFlowSummaryResponse) Descriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{2}
}

func (x *TrdFlowSummaryResponse) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdFlowSummaryResponse) GetFlowSummaryInfoList() []*FlowSummaryInfo {
	if x != nil {
		return x.FlowSummaryInfoList
	}
	return nil
}

type TrdFlowSummaryRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TrdFlowSummaryRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdFlowSummaryRequest_Internal) Reset() {
	*x = TrdFlowSummaryRequest_Internal{}
	mi := &file_Trd_FlowSummary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdFlowSummaryRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdFlowSummaryRequest_Internal) ProtoMessage() {}

func (x *TrdFlowSummaryRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_FlowSummary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdFlowSummaryRequest_Internal.ProtoReflect.Descriptor instead.
func (*TrdFlowSummaryRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{3}
}

func (x *TrdFlowSummaryRequest_Internal) GetPayload() *TrdFlowSummaryRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrdFlowSummaryResponse_Internal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *int32                  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                 `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *TrdFlowSummaryResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TrdFlowSummaryResponse_Internal fields.
const (
	Default_TrdFlowSummaryResponse_Internal_RetType = int32(-400)
)

func (x *TrdFlowSummaryResponse_Internal) Reset() {
	*x = TrdFlowSummaryResponse_Internal{}
	mi := &file_Trd_FlowSummary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdFlowSummaryResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdFlowSummaryResponse_Internal) ProtoMessage() {}

func (x *TrdFlowSummaryResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_FlowSummary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdFlowSummaryResponse_Internal.ProtoReflect.Descriptor instead.
func (*TrdFlowSummaryResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_FlowSummary_proto_rawDescGZIP(), []int{4}
}

func (x *TrdFlowSummaryResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_TrdFlowSummaryResponse_Internal_RetType
}

func (x *TrdFlowSummaryResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *TrdFlowSummaryResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *TrdFlowSummaryResponse_Internal) GetPayload() *TrdFlowSummaryResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Trd_FlowSummary_proto protoreflect.FileDescriptor

const file_Trd_FlowSummary_proto_rawDesc = "" +
	"\n" +
	"\x15Trd_FlowSummary.proto\x12\x06futupb\x1a\x10Trd_Common.proto\"\xbb\x02\n" +
	"\x0fFlowSummaryInfo\x12\"\n" +
	"\fclearingDate\x18\x01 \x01(\tR\fclearingDate\x12&\n" +
	"\x0esettlementDate\x18\x02 \x01(\tR\x0esettlementDate\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\x05R\bcurrency\x12\"\n" +
	"\fcashFlowType\x18\x04 \x01(\tR\fcashFlowType\x12,\n" +
	"\x11cashFlowDirection\x18\x05 \x01(\x05R\x11cashFlowDirection\x12&\n" +
	"\x0ecashFlowAmount\x18\x06 \x01(\x01R\x0ecashFlowAmount\x12&\n" +
	"\x0ecashFlowRemark\x18\a \x01(\tR\x0ecashFlowRemark\x12\x1e\n" +
	"\n" +
	"cashFlowID\x18\b \x01(\x04R\n" +
	"cashFlowID\"\x94\x01\n" +
	"\x15TrdFlowSummaryRequest\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12\"\n" +
	"\fclearingDate\x18\x02 \x02(\tR\fclearingDate\x12,\n" +
	"\x11cashFlowDirection\x18\x03 \x01(\x05R\x11cashFlowDirection\"\x8e\x01\n" +
	"\x16TrdFlowSummaryResponse\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12I\n" +
	"\x13flowSummaryInfoList\x18\x02 \x03(\v2\x17.futupb.FlowSummaryInfoR\x13flowSummaryInfoList\"Y\n" +
	"\x1eTrdFlowSummaryRequest_Internal\x127\n" +
	"\apayload\x18\x01 \x02(\v2\x1d.futupb.TrdFlowSummaryRequestR\apayload\"\xad\x01\n" +
	"\x1fTrdFlowSummaryResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x128\n" +
	"\apayload\x18\x04 \x01(\v2\x1e.futupb.TrdFlowSummaryResponseR\apayload*s\n" +
	"\x14TrdCashFlowDirection\x12 \n" +
	"\x1cTrdCashFlowDirection_Unknown\x10\x00\x12\x1b\n" +
	"\x17TrdCashFlowDirection_In\x10\x01\x12\x1c\n" +
	"\x18TrdCashFlowDirection_Out\x10\x02B4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Trd_FlowSummary_proto_rawDescOnce sync.Once
	file_Trd_FlowSummary_proto_rawDescData []byte
)

func file_Trd_FlowSummary_proto_rawDescGZIP() []byte {
	file_Trd_FlowSummary_proto_rawDescOnce.Do(func() {
		file_Trd_FlowSummary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_FlowSummary_proto_rawDesc), len(file_Trd_FlowSummary_proto_rawDesc)))
	})
	return file_Trd_FlowSummary_proto_rawDescData
}

var file_Trd_FlowSummary_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Trd_FlowSummary_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Trd_FlowSummary_proto_goTypes = []any{
	(TrdCashFlowDirection)(0),               // 0: futupb.TrdCashFlowDirection
	(*FlowSummaryInfo)(nil),                 // 1: futupb.FlowSummaryInfo
	(*TrdFlowSummaryRequest)(nil),           // 2: futupb.TrdFlowSummaryRequest
	(*TrdFlowSummaryResponse)(nil),          // 3: futupb.TrdFlowSummaryResponse
	(*TrdFlowSummaryRequest_Internal)(nil),  // 4: futupb.TrdFlowSummaryRequest_Internal
	(*TrdFlowSummaryResponse_Internal)(nil), // 5: futupb.TrdFlowSummaryResponse_Internal
	(*TrdHeader)(nil),                       // 6: futupb.TrdHeader
}
var file_Trd_FlowSummary_proto_depIdxs = []int32{
	6, // 0: futupb.TrdFlowSummaryRequest.header:type_name -> futupb.TrdHeader
	6, // 1: futupb.TrdFlowSummaryResponse.header:type_name -> futupb.TrdHeader
	1, // 2: futupb.TrdFlowSummaryResponse.flowSummaryInfoList:type_name -> futupb.FlowSummaryInfo
	2, // 3: futupb.TrdFlowSummaryRequest_Internal.payload:type_name -> futupb.TrdFlowSummaryRequest
	3, // 4: futupb.TrdFlowSummaryResponse_Internal.payload:type_name -> futupb.TrdFlowSummaryResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Trd_FlowSummary_proto_init() }
func file_Trd_FlowSummary_proto_init() {
	if File_Trd_FlowSummary_proto != nil {
		return
	}
	file_Trd_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_FlowSummary_proto_rawDesc), len(file_Trd_FlowSummary_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_FlowSummary_proto_goTypes,
		DependencyIndexes: file_Trd_FlowSummary_proto_depIdxs,
		EnumInfos:         file_Trd_FlowSummary_proto_enumTypes,
		MessageInfos:      file_Trd_FlowSummary_proto_msgTypes,
	}.Build()
	File_Trd_FlowSummary_proto = out.File
	file_Trd_FlowSummary_proto_goTypes = nil
	file_Trd_FlowSummary_proto_depIdxs = nil
}
