// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Trd_PlaceOrder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrdPlaceOrderRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PacketID  *PacketID              `protobuf:"bytes,1,req,name=packetID" json:"packetID,omitempty"`    //交易写操作防重放攻击
	Header    *TrdHeader             `protobuf:"bytes,2,req,name=header" json:"header,omitempty"`        //交易公共参数头
	TrdSide   *int32                 `protobuf:"varint,3,req,name=trdSide" json:"trdSide,omitempty"`     //交易方向, 参见Trd_Common.TrdSide的枚举定义
	OrderType *int32                 `protobuf:"varint,4,req,name=orderType" json:"orderType,omitempty"` //订单类型, 参见Trd_Common.OrderType的枚举定义
	Code      *string                `protobuf:"bytes,5,req,name=code" json:"code,omitempty"`            //代码，港股必须是5位数字，A股必须是6位数字，美股没限制
	Qty       *float64               `protobuf:"fixed64,6,req,name=qty" json:"qty,omitempty"`            //数量，期权单位是"张"（精确到小数点后 0 位，超出部分会被舍弃。期权期货单位是"张"）
	Price     *float64               `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`        //价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）
	// 以下2个为调整价格使用，都传才有效，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
	AdjustPrice        *bool    `protobuf:"varint,8,opt,name=adjustPrice" json:"adjustPrice,omitempty"`                //是否调整价格，如果价格不合法，是否调整到合法价位，true调整，false不调整
	AdjustSideAndLimit *float64 `protobuf:"fixed64,9,opt,name=adjustSideAndLimit" json:"adjustSideAndLimit,omitempty"` //调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
	SecMarket          *int32   `protobuf:"varint,10,opt,name=secMarket" json:"secMarket,omitempty"`                   //证券所属市场，参见TrdSecMarket的枚举定义
	Remark             *string  `protobuf:"bytes,11,opt,name=remark" json:"remark,omitempty"`                          //用户备注字符串，最多只能传64字节。可用于标识订单唯一信息等，下单填上，订单结构就会带上。
	TimeInForce        *int32   `protobuf:"varint,12,opt,name=timeInForce" json:"timeInForce,omitempty"`               //订单有效期限，参见TrdCommon_TimeInForce的枚举定义
	FillOutsideRTH     *bool    `protobuf:"varint,13,opt,name=fillOutsideRTH" json:"fillOutsideRTH,omitempty"`         //是否允许盘前盘后成交。仅适用于美股限价单。默认false
	AuxPrice           *float64 `protobuf:"fixed64,14,opt,name=auxPrice" json:"auxPrice,omitempty"`                    //触发价格
	TrailType          *int32   `protobuf:"varint,15,opt,name=trailType" json:"trailType,omitempty"`                   //跟踪类型, 参见Trd_Common.TrailType的枚举定义
	TrailValue         *float64 `protobuf:"fixed64,16,opt,name=trailValue" json:"trailValue,omitempty"`                //跟踪金额/百分比
	TrailSpread        *float64 `protobuf:"fixed64,17,opt,name=trailSpread" json:"trailSpread,omitempty"`              //指定价差
	Session            *int32   `protobuf:"varint,18,opt,name=session" json:"session,omitempty"`                       //美股订单时段, 参见Common.Session的枚举定义
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TrdPlaceOrderRequest) Reset() {
	*x = TrdPlaceOrderRequest{}
	mi := &file_Trd_PlaceOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdPlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdPlaceOrderRequest) ProtoMessage() {}

func (x *TrdPlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdPlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*TrdPlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceOrder_proto_rawDescGZIP(), []int{0}
}

func (x *TrdPlaceOrderRequest) GetPacketID() *PacketID {
	if x != nil {
		return x.PacketID
	}
	return nil
}

func (x *TrdPlaceOrderRequest) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdPlaceOrderRequest) GetTrdSide() int32 {
	if x != nil && x.TrdSide != nil {
		return *x.TrdSide
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetOrderType() int32 {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *TrdPlaceOrderRequest) GetQty() float64 {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetAdjustPrice() bool {
	if x != nil && x.AdjustPrice != nil {
		return *x.AdjustPrice
	}
	return false
}

func (x *TrdPlaceOrderRequest) GetAdjustSideAndLimit() float64 {
	if x != nil && x.AdjustSideAndLimit != nil {
		return *x.AdjustSideAndLimit
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetSecMarket() int32 {
	if x != nil && x.SecMarket != nil {
		return *x.SecMarket
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *TrdPlaceOrderRequest) GetTimeInForce() int32 {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetFillOutsideRTH() bool {
	if x != nil && x.FillOutsideRTH != nil {
		return *x.FillOutsideRTH
	}
	return false
}

func (x *TrdPlaceOrderRequest) GetAuxPrice() float64 {
	if x != nil && x.AuxPrice != nil {
		return *x.AuxPrice
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetTrailType() int32 {
	if x != nil && x.TrailType != nil {
		return *x.TrailType
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetTrailValue() float64 {
	if x != nil && x.TrailValue != nil {
		return *x.TrailValue
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetTrailSpread() float64 {
	if x != nil && x.TrailSpread != nil {
		return *x.TrailSpread
	}
	return 0
}

func (x *TrdPlaceOrderRequest) GetSession() int32 {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return 0
}

type TrdPlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`       //交易公共参数头
	OrderID       *uint64                `protobuf:"varint,2,opt,name=orderID" json:"orderID,omitempty"`    //订单号
	OrderIDEx     *string                `protobuf:"bytes,3,opt,name=orderIDEx" json:"orderIDEx,omitempty"` //表示服务器订单id，可以用来代替orderID，和orderID二选一
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdPlaceOrderResponse) Reset() {
	*x = TrdPlaceOrderResponse{}
	mi := &file_Trd_PlaceOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdPlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdPlaceOrderResponse) ProtoMessage() {}

func (x *TrdPlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdPlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*TrdPlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceOrder_proto_rawDescGZIP(), []int{1}
}

func (x *TrdPlaceOrderResponse) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdPlaceOrderResponse) GetOrderID() uint64 {
	if x != nil && x.OrderID != nil {
		return *x.OrderID
	}
	return 0
}

func (x *TrdPlaceOrderResponse) GetOrderIDEx() string {
	if x != nil && x.OrderIDEx != nil {
		return *x.OrderIDEx
	}
	return ""
}

type TrdPlaceOrderRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TrdPlaceOrderRequest  `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdPlaceOrderRequest_Internal) Reset() {
	*x = TrdPlaceOrderRequest_Internal{}
	mi := &file_Trd_PlaceOrder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdPlaceOrderRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdPlaceOrderRequest_Internal) ProtoMessage() {}

func (x *TrdPlaceOrderRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceOrder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdPlaceOrderRequest_Internal.ProtoReflect.Descriptor instead.
func (*TrdPlaceOrderRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceOrder_proto_rawDescGZIP(), []int{2}
}

func (x *TrdPlaceOrderRequest_Internal) GetPayload() *TrdPlaceOrderRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrdPlaceOrderResponse_Internal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *TrdPlaceOrderResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TrdPlaceOrderResponse_Internal fields.
const (
	Default_TrdPlaceOrderResponse_Internal_RetType = int32(-400)
)

func (x *TrdPlaceOrderResponse_Internal) Reset() {
	*x = TrdPlaceOrderResponse_Internal{}
	mi := &file_Trd_PlaceOrder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdPlaceOrderResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdPlaceOrderResponse_Internal) ProtoMessage() {}

func (x *TrdPlaceOrderResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceOrder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdPlaceOrderResponse_Internal.ProtoReflect.Descriptor instead.
func (*TrdPlaceOrderResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceOrder_proto_rawDescGZIP(), []int{3}
}

func (x *TrdPlaceOrderResponse_Internal) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_TrdPlaceOrderResponse_Internal_RetType
}

func (x *TrdPlaceOrderResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *TrdPlaceOrderResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *TrdPlaceOrderResponse_Internal) GetPayload() *TrdPlaceOrderResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Trd_PlaceOrder_proto protoreflect.FileDescriptor

const file_Trd_PlaceOrder_proto_rawDesc = "" +
	"\n" +
	"\x14Trd_PlaceOrder.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Trd_Common.proto\"\xcb\x04\n" +
	"\x14TrdPlaceOrderRequest\x12,\n" +
	"\bpacketID\x18\x01 \x02(\v2\x10.futupb.PacketIDR\bpacketID\x12)\n" +
	"\x06header\x18\x02 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12\x18\n" +
	"\atrdSide\x18\x03 \x02(\x05R\atrdSide\x12\x1c\n" +
	"\torderType\x18\x04 \x02(\x05R\torderType\x12\x12\n" +
	"\x04code\x18\x05 \x02(\tR\x04code\x12\x10\n" +
	"\x03qty\x18\x06 \x02(\x01R\x03qty\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12 \n" +
	"\vadjustPrice\x18\b \x01(\bR\vadjustPrice\x12.\n" +
	"\x12adjustSideAndLimit\x18\t \x01(\x01R\x12adjustSideAndLimit\x12\x1c\n" +
	"\tsecMarket\x18\n" +
	" \x01(\x05R\tsecMarket\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12 \n" +
	"\vtimeInForce\x18\f \x01(\x05R\vtimeInForce\x12&\n" +
	"\x0efillOutsideRTH\x18\r \x01(\bR\x0efillOutsideRTH\x12\x1a\n" +
	"\bauxPrice\x18\x0e \x01(\x01R\bauxPrice\x12\x1c\n" +
	"\ttrailType\x18\x0f \x01(\x05R\ttrailType\x12\x1e\n" +
	"\n" +
	"trailValue\x18\x10 \x01(\x01R\n" +
	"trailValue\x12 \n" +
	"\vtrailSpread\x18\x11 \x01(\x01R\vtrailSpread\x12\x18\n" +
	"\asession\x18\x12 \x01(\x05R\asession\"z\n" +
	"\x15TrdPlaceOrderResponse\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12\x18\n" +
	"\aorderID\x18\x02 \x01(\x04R\aorderID\x12\x1c\n" +
	"\torderIDEx\x18\x03 \x01(\tR\torderIDEx\"W\n" +
	"\x1dTrdPlaceOrderRequest_Internal\x126\n" +
	"\apayload\x18\x01 \x02(\v2\x1c.futupb.TrdPlaceOrderRequestR\apayload\"\xab\x01\n" +
	"\x1eTrdPlaceOrderResponse_Internal\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x127\n" +
	"\apayload\x18\x04 \x01(\v2\x1d.futupb.TrdPlaceOrderResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Trd_PlaceOrder_proto_rawDescOnce sync.Once
	file_Trd_PlaceOrder_proto_rawDescData []byte
)

func file_Trd_PlaceOrder_proto_rawDescGZIP() []byte {
	file_Trd_PlaceOrder_proto_rawDescOnce.Do(func() {
		file_Trd_PlaceOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_PlaceOrder_proto_rawDesc), len(file_Trd_PlaceOrder_proto_rawDesc)))
	})
	return file_Trd_PlaceOrder_proto_rawDescData
}

var file_Trd_PlaceOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trd_PlaceOrder_proto_goTypes = []any{
	(*TrdPlaceOrderRequest)(nil),           // 0: futupb.TrdPlaceOrderRequest
	(*TrdPlaceOrderResponse)(nil),          // 1: futupb.TrdPlaceOrderResponse
	(*TrdPlaceOrderRequest_Internal)(nil),  // 2: futupb.TrdPlaceOrderRequest_Internal
	(*TrdPlaceOrderResponse_Internal)(nil), // 3: futupb.TrdPlaceOrderResponse_Internal
	(*PacketID)(nil),                       // 4: futupb.PacketID
	(*TrdHeader)(nil),                      // 5: futupb.TrdHeader
}
var file_Trd_PlaceOrder_proto_depIdxs = []int32{
	4, // 0: futupb.TrdPlaceOrderRequest.packetID:type_name -> futupb.PacketID
	5, // 1: futupb.TrdPlaceOrderRequest.header:type_name -> futupb.TrdHeader
	5, // 2: futupb.TrdPlaceOrderResponse.header:type_name -> futupb.TrdHeader
	0, // 3: futupb.TrdPlaceOrderRequest_Internal.payload:type_name -> futupb.TrdPlaceOrderRequest
	1, // 4: futupb.TrdPlaceOrderResponse_Internal.payload:type_name -> futupb.TrdPlaceOrderResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Trd_PlaceOrder_proto_init() }
func file_Trd_PlaceOrder_proto_init() {
	if File_Trd_PlaceOrder_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Trd_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_PlaceOrder_proto_rawDesc), len(file_Trd_PlaceOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_PlaceOrder_proto_goTypes,
		DependencyIndexes: file_Trd_PlaceOrder_proto_depIdxs,
		MessageInfos:      file_Trd_PlaceOrder_proto_msgTypes,
	}.Build()
	File_Trd_PlaceOrder_proto = out.File
	file_Trd_PlaceOrder_proto_goTypes = nil
	file_Trd_PlaceOrder_proto_depIdxs = nil
}
