// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Trd_GetPositionList.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrdGetPositionListRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Header           *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`                       //交易公共参数头
	FilterConditions *TrdFilterConditions   `protobuf:"bytes,2,opt,name=filterConditions" json:"filterConditions,omitempty"`   //过滤条件
	FilterPLRatioMin *float64               `protobuf:"fixed64,3,opt,name=filterPLRatioMin" json:"filterPLRatioMin,omitempty"` //过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
	FilterPLRatioMax *float64               `protobuf:"fixed64,4,opt,name=filterPLRatioMax" json:"filterPLRatioMax,omitempty"` //过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
	RefreshCache     *bool                  `protobuf:"varint,5,opt,name=refreshCache" json:"refreshCache,omitempty"`          //立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrdGetPositionListRequest) Reset() {
	*x = TrdGetPositionListRequest{}
	mi := &file_Trd_GetPositionList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetPositionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetPositionListRequest) ProtoMessage() {}

func (x *TrdGetPositionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetPositionList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetPositionListRequest.ProtoReflect.Descriptor instead.
func (*TrdGetPositionListRequest) Descriptor() ([]byte, []int) {
	return file_Trd_GetPositionList_proto_rawDescGZIP(), []int{0}
}

func (x *TrdGetPositionListRequest) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdGetPositionListRequest) GetFilterConditions() *TrdFilterConditions {
	if x != nil {
		return x.FilterConditions
	}
	return nil
}

func (x *TrdGetPositionListRequest) GetFilterPLRatioMin() float64 {
	if x != nil && x.FilterPLRatioMin != nil {
		return *x.FilterPLRatioMin
	}
	return 0
}

func (x *TrdGetPositionListRequest) GetFilterPLRatioMax() float64 {
	if x != nil && x.FilterPLRatioMax != nil {
		return *x.FilterPLRatioMax
	}
	return 0
}

func (x *TrdGetPositionListRequest) GetRefreshCache() bool {
	if x != nil && x.RefreshCache != nil {
		return *x.RefreshCache
	}
	return false
}

type TrdGetPositionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`             //交易公共参数头
	PositionList  []*Position            `protobuf:"bytes,2,rep,name=positionList" json:"positionList,omitempty"` //持仓列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdGetPositionListResponse) Reset() {
	*x = TrdGetPositionListResponse{}
	mi := &file_Trd_GetPositionList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetPositionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetPositionListResponse) ProtoMessage() {}

func (x *TrdGetPositionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetPositionList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetPositionListResponse.ProtoReflect.Descriptor instead.
func (*TrdGetPositionListResponse) Descriptor() ([]byte, []int) {
	return file_Trd_GetPositionList_proto_rawDescGZIP(), []int{1}
}

func (x *TrdGetPositionListResponse) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TrdGetPositionListResponse) GetPositionList() []*Position {
	if x != nil {
		return x.PositionList
	}
	return nil
}

type TrdGetPositionListRequest_Internal struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Payload       *TrdGetPositionListRequest `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrdGetPositionListRequest_Internal) Reset() {
	*x = TrdGetPositionListRequest_Internal{}
	mi := &file_Trd_GetPositionList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetPositionListRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetPositionListRequest_Internal) ProtoMessage() {}

func (x *TrdGetPositionListRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetPositionList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetPositionListRequest_Internal.ProtoReflect.Descriptor instead.
func (*TrdGetPositionListRequest_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_GetPositionList_proto_rawDescGZIP(), []int{2}
}

func (x *TrdGetPositionListRequest_Internal) GetPayload() *TrdGetPositionListRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrdGetPositionListResponse_Internal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *RetType                    `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                     `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                      `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *TrdGetPositionListResponse `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TrdGetPositionListResponse_Internal fields.
const (
	Default_TrdGetPositionListResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *TrdGetPositionListResponse_Internal) Reset() {
	*x = TrdGetPositionListResponse_Internal{}
	mi := &file_Trd_GetPositionList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrdGetPositionListResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrdGetPositionListResponse_Internal) ProtoMessage() {}

func (x *TrdGetPositionListResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetPositionList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrdGetPositionListResponse_Internal.ProtoReflect.Descriptor instead.
func (*TrdGetPositionListResponse_Internal) Descriptor() ([]byte, []int) {
	return file_Trd_GetPositionList_proto_rawDescGZIP(), []int{3}
}

func (x *TrdGetPositionListResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_TrdGetPositionListResponse_Internal_RetType
}

func (x *TrdGetPositionListResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *TrdGetPositionListResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *TrdGetPositionListResponse_Internal) GetPayload() *TrdGetPositionListResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Trd_GetPositionList_proto protoreflect.FileDescriptor

const file_Trd_GetPositionList_proto_rawDesc = "" +
	"\n" +
	"\x19Trd_GetPositionList.proto\x12\x06futupb\x1a\fCommon.proto\x1a\x10Trd_Common.proto\"\x8b\x02\n" +
	"\x19TrdGetPositionListRequest\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x12G\n" +
	"\x10filterConditions\x18\x02 \x01(\v2\x1b.futupb.TrdFilterConditionsR\x10filterConditions\x12*\n" +
	"\x10filterPLRatioMin\x18\x03 \x01(\x01R\x10filterPLRatioMin\x12*\n" +
	"\x10filterPLRatioMax\x18\x04 \x01(\x01R\x10filterPLRatioMax\x12\"\n" +
	"\frefreshCache\x18\x05 \x01(\bR\frefreshCache\"}\n" +
	"\x1aTrdGetPositionListResponse\x12)\n" +
	"\x06header\x18\x01 \x02(\v2\x11.futupb.TrdHeaderR\x06header\x124\n" +
	"\fpositionList\x18\x02 \x03(\v2\x10.futupb.PositionR\fpositionList\"a\n" +
	"\"TrdGetPositionListRequest_Internal\x12;\n" +
	"\apayload\x18\x01 \x02(\v2!.futupb.TrdGetPositionListRequestR\apayload\"\xd1\x01\n" +
	"#TrdGetPositionListResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12<\n" +
	"\apayload\x18\x04 \x01(\v2\".futupb.TrdGetPositionListResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_Trd_GetPositionList_proto_rawDescOnce sync.Once
	file_Trd_GetPositionList_proto_rawDescData []byte
)

func file_Trd_GetPositionList_proto_rawDescGZIP() []byte {
	file_Trd_GetPositionList_proto_rawDescOnce.Do(func() {
		file_Trd_GetPositionList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_GetPositionList_proto_rawDesc), len(file_Trd_GetPositionList_proto_rawDesc)))
	})
	return file_Trd_GetPositionList_proto_rawDescData
}

var file_Trd_GetPositionList_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trd_GetPositionList_proto_goTypes = []any{
	(*TrdGetPositionListRequest)(nil),           // 0: futupb.TrdGetPositionListRequest
	(*TrdGetPositionListResponse)(nil),          // 1: futupb.TrdGetPositionListResponse
	(*TrdGetPositionListRequest_Internal)(nil),  // 2: futupb.TrdGetPositionListRequest_Internal
	(*TrdGetPositionListResponse_Internal)(nil), // 3: futupb.TrdGetPositionListResponse_Internal
	(*TrdHeader)(nil),                           // 4: futupb.TrdHeader
	(*TrdFilterConditions)(nil),                 // 5: futupb.TrdFilterConditions
	(*Position)(nil),                            // 6: futupb.Position
	(RetType)(0),                                // 7: futupb.RetType
}
var file_Trd_GetPositionList_proto_depIdxs = []int32{
	4, // 0: futupb.TrdGetPositionListRequest.header:type_name -> futupb.TrdHeader
	5, // 1: futupb.TrdGetPositionListRequest.filterConditions:type_name -> futupb.TrdFilterConditions
	4, // 2: futupb.TrdGetPositionListResponse.header:type_name -> futupb.TrdHeader
	6, // 3: futupb.TrdGetPositionListResponse.positionList:type_name -> futupb.Position
	0, // 4: futupb.TrdGetPositionListRequest_Internal.payload:type_name -> futupb.TrdGetPositionListRequest
	7, // 5: futupb.TrdGetPositionListResponse_Internal.retType:type_name -> futupb.RetType
	1, // 6: futupb.TrdGetPositionListResponse_Internal.payload:type_name -> futupb.TrdGetPositionListResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_Trd_GetPositionList_proto_init() }
func file_Trd_GetPositionList_proto_init() {
	if File_Trd_GetPositionList_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Trd_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_GetPositionList_proto_rawDesc), len(file_Trd_GetPositionList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_GetPositionList_proto_goTypes,
		DependencyIndexes: file_Trd_GetPositionList_proto_depIdxs,
		MessageInfos:      file_Trd_GetPositionList_proto_msgTypes,
	}.Build()
	File_Trd_GetPositionList_proto = out.File
	file_Trd_GetPositionList_proto_goTypes = nil
	file_Trd_GetPositionList_proto_depIdxs = nil
}
