// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: UsedQuota.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsedQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsedQuotaRequest) Reset() {
	*x = UsedQuotaRequest{}
	mi := &file_UsedQuota_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsedQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsedQuotaRequest) ProtoMessage() {}

func (x *UsedQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UsedQuota_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsedQuotaRequest.ProtoReflect.Descriptor instead.
func (*UsedQuotaRequest) Descriptor() ([]byte, []int) {
	return file_UsedQuota_proto_rawDescGZIP(), []int{0}
}

type UsedQuotaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UsedSubQuota   *int32                 `protobuf:"varint,1,opt,name=used_sub_quota,json=usedSubQuota" json:"used_sub_quota,omitempty"`       // 已使用订阅额度
	UsedKlineQuota *int32                 `protobuf:"varint,2,opt,name=used_kline_quota,json=usedKlineQuota" json:"used_kline_quota,omitempty"` // 已使用历史K线额度
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsedQuotaResponse) Reset() {
	*x = UsedQuotaResponse{}
	mi := &file_UsedQuota_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsedQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsedQuotaResponse) ProtoMessage() {}

func (x *UsedQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UsedQuota_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsedQuotaResponse.ProtoReflect.Descriptor instead.
func (*UsedQuotaResponse) Descriptor() ([]byte, []int) {
	return file_UsedQuota_proto_rawDescGZIP(), []int{1}
}

func (x *UsedQuotaResponse) GetUsedSubQuota() int32 {
	if x != nil && x.UsedSubQuota != nil {
		return *x.UsedSubQuota
	}
	return 0
}

func (x *UsedQuotaResponse) GetUsedKlineQuota() int32 {
	if x != nil && x.UsedKlineQuota != nil {
		return *x.UsedKlineQuota
	}
	return 0
}

type UsedQuotaRequest_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *UsedQuotaRequest      `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsedQuotaRequest_Internal) Reset() {
	*x = UsedQuotaRequest_Internal{}
	mi := &file_UsedQuota_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsedQuotaRequest_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsedQuotaRequest_Internal) ProtoMessage() {}

func (x *UsedQuotaRequest_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_UsedQuota_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsedQuotaRequest_Internal.ProtoReflect.Descriptor instead.
func (*UsedQuotaRequest_Internal) Descriptor() ([]byte, []int) {
	return file_UsedQuota_proto_rawDescGZIP(), []int{2}
}

func (x *UsedQuotaRequest_Internal) GetPayload() *UsedQuotaRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UsedQuotaResponse_Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *RetType               `protobuf:"varint,1,req,name=retType,enum=futupb.RetType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	Payload       *UsedQuotaResponse     `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for UsedQuotaResponse_Internal fields.
const (
	Default_UsedQuotaResponse_Internal_RetType = RetType_RetType_Unknown
)

func (x *UsedQuotaResponse_Internal) Reset() {
	*x = UsedQuotaResponse_Internal{}
	mi := &file_UsedQuota_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsedQuotaResponse_Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsedQuotaResponse_Internal) ProtoMessage() {}

func (x *UsedQuotaResponse_Internal) ProtoReflect() protoreflect.Message {
	mi := &file_UsedQuota_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsedQuotaResponse_Internal.ProtoReflect.Descriptor instead.
func (*UsedQuotaResponse_Internal) Descriptor() ([]byte, []int) {
	return file_UsedQuota_proto_rawDescGZIP(), []int{3}
}

func (x *UsedQuotaResponse_Internal) GetRetType() RetType {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_UsedQuotaResponse_Internal_RetType
}

func (x *UsedQuotaResponse_Internal) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *UsedQuotaResponse_Internal) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *UsedQuotaResponse_Internal) GetPayload() *UsedQuotaResponse {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_UsedQuota_proto protoreflect.FileDescriptor

const file_UsedQuota_proto_rawDesc = "" +
	"\n" +
	"\x0fUsedQuota.proto\x12\x06futupb\x1a\fCommon.proto\"\x12\n" +
	"\x10UsedQuotaRequest\"c\n" +
	"\x11UsedQuotaResponse\x12$\n" +
	"\x0eused_sub_quota\x18\x01 \x01(\x05R\fusedSubQuota\x12(\n" +
	"\x10used_kline_quota\x18\x02 \x01(\x05R\x0eusedKlineQuota\"O\n" +
	"\x19UsedQuotaRequest_Internal\x122\n" +
	"\apayload\x18\x01 \x02(\v2\x18.futupb.UsedQuotaRequestR\apayload\"\xbf\x01\n" +
	"\x1aUsedQuotaResponse_Internal\x12:\n" +
	"\aretType\x18\x01 \x02(\x0e2\x0f.futupb.RetType:\x0fRetType_UnknownR\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x123\n" +
	"\apayload\x18\x04 \x01(\v2\x19.futupb.UsedQuotaResponseR\apayloadB4\n" +
	"\x13com.futu.openapi.pbZ\x1dgithub.com/santsai/futu-go/pb"

var (
	file_UsedQuota_proto_rawDescOnce sync.Once
	file_UsedQuota_proto_rawDescData []byte
)

func file_UsedQuota_proto_rawDescGZIP() []byte {
	file_UsedQuota_proto_rawDescOnce.Do(func() {
		file_UsedQuota_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UsedQuota_proto_rawDesc), len(file_UsedQuota_proto_rawDesc)))
	})
	return file_UsedQuota_proto_rawDescData
}

var file_UsedQuota_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_UsedQuota_proto_goTypes = []any{
	(*UsedQuotaRequest)(nil),           // 0: futupb.UsedQuotaRequest
	(*UsedQuotaResponse)(nil),          // 1: futupb.UsedQuotaResponse
	(*UsedQuotaRequest_Internal)(nil),  // 2: futupb.UsedQuotaRequest_Internal
	(*UsedQuotaResponse_Internal)(nil), // 3: futupb.UsedQuotaResponse_Internal
	(RetType)(0),                       // 4: futupb.RetType
}
var file_UsedQuota_proto_depIdxs = []int32{
	0, // 0: futupb.UsedQuotaRequest_Internal.payload:type_name -> futupb.UsedQuotaRequest
	4, // 1: futupb.UsedQuotaResponse_Internal.retType:type_name -> futupb.RetType
	1, // 2: futupb.UsedQuotaResponse_Internal.payload:type_name -> futupb.UsedQuotaResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_UsedQuota_proto_init() }
func file_UsedQuota_proto_init() {
	if File_UsedQuota_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UsedQuota_proto_rawDesc), len(file_UsedQuota_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UsedQuota_proto_goTypes,
		DependencyIndexes: file_UsedQuota_proto_depIdxs,
		MessageInfos:      file_UsedQuota_proto_msgTypes,
	}.Build()
	File_UsedQuota_proto = out.File
	file_UsedQuota_proto_goTypes = nil
	file_UsedQuota_proto_depIdxs = nil
}
